[workspace]
members = [
    "desktop",
    "shared",
    "secure",
    "nonsecure",
    "bip39",
    "zk-test",
    "bls12_381_pka",
    "dbgen",
]
resolver = "2"

[workspace.package]
edition = "2021"

[profile.dev]
opt-level = 2

[profile.dev.package.slh-dsa]
opt-level = 3

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = "debuginfo"
overflow-checks = true

[profile.release.package.slh-dsa]
opt-level = 3
