use super::*;
use sha2::{Digest, Sha256};

fn array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}
fn reference_adrs(ht: u32, tree: u32, height: u32, idx: u32) -> [u8; 32] {
    let mut a = [0; 32];
    a[4..12].copy_from_slice(&u64::from(ht).to_be_bytes());
    a[12..16].copy_from_slice(&3u32.to_be_bytes());
    a[16..20].copy_from_slice(&tree.to_be_bytes());
    a[24..28].copy_from_slice(&height.to_be_bytes());
    a[28..32].copy_from_slice(&idx.to_be_bytes());
    a
}
fn reference(
    seed: &[u8; 32],
    ht: u32,
    tree: u32,
    idx: u32,
    secret: &[u8; 16],
    auth: &[[u8; 16]; 11],
) -> [u8; 16] {
    let mut initial = Vec::from(*seed);
    initial.extend_from_slice(&reference_adrs(ht, tree, 0, idx));
    initial.extend_from_slice(secret);
    initial.extend_from_slice(&[0; 16]);
    let mut node: [u8; 16] = Sha256::digest(initial)[..16].try_into().unwrap();
    for (h, sibling) in auth.iter().enumerate() {
        let mut bytes = Vec::from(*seed);
        bytes.extend_from_slice(&reference_adrs(
            ht,
            tree,
            h as u32 + 1,
            idx / (1u32 << (h + 1)),
        ));
        let (left, right) = if (idx / (1u32 << h)) % 2 == 0 {
            (&node, sibling)
        } else {
            (sibling, &node)
        };
        bytes.extend_from_slice(left);
        bytes.extend_from_slice(&[0; 16]);
        bytes.extend_from_slice(right);
        bytes.extend_from_slice(&[0; 16]);
        node = Sha256::digest(bytes)[..16].try_into().unwrap();
    }
    node
}
#[test]
fn fors_recovery_corpus() {
    let seed = std::array::from_fn(|i| (i * 17 + 3) as u8);
    let secret = std::array::from_fn(|i| (i * 23 + 7) as u8);
    let auth: [[u8; 16]; 11] =
        std::array::from_fn(|i| std::array::from_fn(|j| (i * 53 + j * 31 + 11) as u8));
    let mut out = String::from("-- Generated by tools/fors-recovery-corpus from the unchanged private Rust helper.\nset_option maxRecDepth 8192\nnamespace ForsRecoveryDiff\n");
    out.push_str(&format!(
        "def seed : Array UInt8 := {}\ndef secret : Array UInt8 := {}\n",
        array(&seed),
        array(&secret)
    ));
    out.push_str(&format!(
        "def auth : Array (Array UInt8) := #[{}]\n",
        auth.iter()
            .map(|n| array(n))
            .collect::<Vec<_>>()
            .join(",\n  ")
    ));
    let mut cases = (0..2048).map(|i| (0x0102_0304, 12, i)).collect::<Vec<_>>();
    for (ht, tree) in [(0, 0), (u32::MAX, u32::MAX)] {
        for idx in [
            2048,
            2049,
            65535,
            65536,
            0x7fff_ffff,
            0x8000_0000,
            u32::MAX - 1,
            u32::MAX,
        ] {
            cases.push((ht, tree, idx));
        }
    }
    assert_eq!(cases.len(), 2064);
    for (case_number, (ht, tree, idx)) in cases.into_iter().enumerate() {
        if case_number % 128 == 0 {
            if case_number != 0 {
                out.push_str("]\n");
            }
            out.push_str(&format!(
                "def vectors{} : Array (Nat × Nat × Nat × Array UInt8) := #[\n",
                case_number / 128
            ));
        }
        let expected = reference(&seed, ht, tree, idx, &secret, &auth);
        assert_eq!(
            reconstruct_fors_root(&seed, ht, tree, idx, &secret, &auth),
            expected
        );
        out.push_str(&format!("  ({ht}, {tree}, {idx}, {}),\n", array(&expected)));
    }
    out.push_str("]\ndef vectors : Array (Nat × Nat × Nat × Array UInt8) := ");
    out.push_str(
        &(0..17)
            .map(|i| format!("vectors{i}"))
            .collect::<Vec<_>>()
            .join(" ++ "),
    );
    out.push_str("\nend ForsRecoveryDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../extracted/Extracted/ForsRecoveryDiffVectors.lean");
    if std::env::var("PQ_FORS_RECOVERY_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(
            std::fs::read_to_string(dest).unwrap(),
            out,
            "FORS recovery corpus drift"
        );
    }
    println!("FORS recovery corpus: 2048 branch patterns + 16 full-width cases");
}
