// Forest components executed from the unchanged production source. `reference`
// is the independent byte-construction oracle in corpus.rs.
#[test]
fn fors_forest_corpus() {
    let seed: [u8; 32] = std::array::from_fn(|i| (i * 17 + 3) as u8);
    let secrets: [[u8; 16]; 13] =
        std::array::from_fn(|t| std::array::from_fn(|i| (t * 29 + i * 23 + 7) as u8));
    let paths: [[[u8; 16]; 11]; 12] = std::array::from_fn(|t| {
        std::array::from_fn(|h| std::array::from_fn(|i| (t * 47 + h * 53 + i * 31 + 11) as u8))
    });
    let initial: [[u8; 16]; 13] =
        std::array::from_fn(|t| std::array::from_fn(|i| (t * 7 + i * 3 + 1) as u8));
    let nodes = |xs: &[[u8; 16]]| {
        format!(
            "#[{}]",
            xs.iter().map(|n| array(n)).collect::<Vec<_>>().join(",\n")
        )
    };
    let mut out = String::from("-- Generated by the unchanged production FORS components and verifier.\nset_option maxRecDepth 8192\nnamespace ForsForestDiff\n");
    out.push_str(&format!("def seed : Array UInt8 := {}\ndef secrets : Array (Array UInt8) := {}\ndef initial : Array (Array UInt8) := {}\n", array(&seed), nodes(&secrets), nodes(&initial)));
    out.push_str(&format!(
        "def paths : Array (Array (Array UInt8)) := #[{}]\n",
        paths
            .iter()
            .map(|p| nodes(p))
            .collect::<Vec<_>>()
            .join(",\n")
    ));
    let positions = [0, 1, 511, 512, 262143, 262144, 0x01020304, u32::MAX];
    for c in 0..32u32 {
        if c % 8 == 0 {
            if c != 0 {
                out.push_str("]\n");
            }
            out.push_str(&format!("def vectors{} : Array (Nat × Array Nat × Array (Array UInt8) × Array UInt8) := #[\n", c/8));
        }
        let ht = positions[c as usize % positions.len()];
        let indices: [u32; 13] = std::array::from_fn(|t| match c / 8 {
            0 => ((t as u32 * 137) + c) % 2048,
            1 => (1u32 << (t % 11)) ^ (c & 7),
            2 => 2048 + t as u32 * 65537 + c,
            _ => u32::MAX - t as u32 * 257 - c,
        });
        let mut roots = initial;
        for t in 0..12 {
            roots[t] =
                reconstruct_fors_root(&seed, ht, t as u32, indices[t], &secrets[t], &paths[t]);
            assert_eq!(
                roots[t],
                reference(&seed, ht, t as u32, indices[t], &secrets[t], &paths[t])
            );
        }
        assert_eq!(roots[12], initial[12]);
        let mut preimage = Vec::from(seed);
        let mut adrs = [0u8; 32];
        adrs[4..12].copy_from_slice(&u64::from(ht).to_be_bytes());
        adrs[12..16].copy_from_slice(&4u32.to_be_bytes());
        preimage.extend_from_slice(&adrs);
        for node in roots {
            preimage.extend_from_slice(&node);
            preimage.extend_from_slice(&[0; 16]);
        }
        let pk: [u8; 16] = Sha256::digest(preimage)[..16].try_into().unwrap();
        assert_eq!(crate::fors::compute_fors_pk(&seed, ht, &roots), pk);
        let ins = format!(
            "#[{}]",
            indices
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join(", ")
        );
        out.push_str(&format!(
            "({ht}, {ins}, {}, {}),\n",
            nodes(&roots),
            array(&pk)
        ));
    }
    out.push_str("]\ndef vectors := vectors0 ++ vectors1 ++ vectors2 ++ vectors3\ndef rejectVectors : Array (Nat × Nat) := #[\n");
    let pk_seed: [u8; 16] = std::array::from_fn(|i| (i * 7 + 2) as u8);
    let pk_root: [u8; 16] = std::array::from_fn(|i| (i * 11 + 5) as u8);
    for c in 0..16usize {
        let msg: [u8; 32] = std::array::from_fn(|i| (c * 19 + i * 13) as u8);
        let sig: [u8; SIGNATURE_LEN] = std::array::from_fn(|i| (c * 29 + i * 37 + 3) as u8);
        let mut input = Vec::from(pk_seed);
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&pk_root);
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&sig[..16]);
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&msg);
        input.extend_from_slice(&[255; 32]);
        let digest: [u8; 32] = Sha256::digest(input).into();
        let last = ((u32::from(digest[15]) >> 4) | (u32::from(digest[14]) << 4)) & 2047;
        assert_ne!(last, 0); // Avoid accidentally treating the other branch as exercised.
        assert!(!verify(&pk_seed, &pk_root, &msg, &sig));
        out.push_str(&format!("({c}, {last}),\n"));
    }
    out.push_str("]\nend ForsForestDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../extracted/Extracted/ForsForestDiffVectors.lean");
    if std::env::var("PQ_FORS_FOREST_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!(
        "OK: 32 production forest/compression cases and 16 actual verifier forced-zero refusals"
    );
}
