// Execute the unchanged full verifier on both genuine signatures and synthetic
// signatures that pass the FORS digest gate. The independent byte oracle below
// records the prefix result, not an assumption about WOTS acceptance.
fn prefix_hex(xs: &[u8]) -> String {
    xs.iter().map(|b| format!("{b:02x}")).collect()
}
fn prefix_unhex(s: &str) -> Vec<u8> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    assert_eq!(s.len() % 2, 0);
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}
fn prefix_digest(
    seed: &[u8; 16],
    root: &[u8; 16],
    msg: &[u8; 32],
    sig: &[u8; SIGNATURE_LEN],
) -> [u8; 32] {
    let mut input = Vec::from(*seed);
    input.extend_from_slice(&[0; 16]);
    input.extend_from_slice(root);
    input.extend_from_slice(&[0; 16]);
    input.extend_from_slice(&sig[..16]);
    input.extend_from_slice(&[0; 16]);
    input.extend_from_slice(msg);
    input.extend_from_slice(&[255; 32]);
    Sha256::digest(input).into()
}
fn prefix_bits(d: &[u8; 32], start: usize, width: usize) -> u32 {
    (0..width)
        .map(|j| u32::from((d[31 - (start + j) / 8] >> ((start + j) % 8)) & 1) << j)
        .sum()
}
fn prefix_cases() -> Vec<(
    String,
    [u8; 16],
    [u8; 16],
    [u8; 32],
    [u8; SIGNATURE_LEN],
    bool,
)> {
    let mut cases = Vec::new();
    let source = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../smart-wallet/test/c10_test_vectors.json");
    let kats: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(source).unwrap()).unwrap();
    for v in kats["vectors"].as_array().unwrap() {
        let label = v["label"].as_str().unwrap();
        if !(label.starts_with("valid-")
            || label == "mutated-FORS-auth"
            || label == "near-miss-WOTS-digit-sum")
        {
            continue;
        }
        let seed: [u8; 16] = prefix_unhex(v["pkSeed"].as_str().unwrap())[..16]
            .try_into()
            .unwrap();
        let root: [u8; 16] = prefix_unhex(v["pkRoot"].as_str().unwrap())[..16]
            .try_into()
            .unwrap();
        let msg: [u8; 32] = prefix_unhex(v["message"].as_str().unwrap())
            .try_into()
            .unwrap();
        let sig: [u8; SIGNATURE_LEN] = prefix_unhex(v["signature"].as_str().unwrap())
            .try_into()
            .unwrap();
        cases.push((
            label.to_owned(),
            seed,
            root,
            msg,
            sig,
            v["expectValid"].as_bool().unwrap(),
        ));
    }
    assert_eq!(cases.len(), 6);
    for c in 0..16usize {
        let seed = std::array::from_fn(|i| (c * 31 + i * 17 + 1) as u8);
        let root = std::array::from_fn(|i| (c * 23 + i * 7 + 3) as u8);
        let msg = std::array::from_fn(|i| (c * 19 + i * 11 + 5) as u8);
        let mut sig = std::array::from_fn(|i| (c * 13 + i * 37 + 9) as u8);
        let nonce = (0..1_000_000u32)
            .find(|n| {
                sig[..4].copy_from_slice(&n.to_be_bytes());
                prefix_bits(&prefix_digest(&seed, &root, &msg, &sig), 132, 11) == 0
            })
            .expect("bounded deterministic fixture search exhausted");
        assert_eq!(&sig[..4], &nonce.to_be_bytes());
        cases.push((format!("synthetic-{c}"), seed, root, msg, sig, false));
    }
    cases
}
#[test]
fn fors_prefix_corpus() {
    let cases = prefix_cases();
    let mut out = String::from("-- Generated by fors_prefix_corpus from production Rust and an independent byte oracle.\nnamespace ForsPrefixDiff\nstructure Vector where\n  label : String\n  seed : String\n  root : String\n  msg : String\n  sig : String\n  digest : String\n  ht : Nat\n  pk : String\n  accepted : Bool\n  deriving Inhabited\ndef vectors : List Vector := [\n");
    let mut accepted = 0;
    for (label, seed, root, msg, sig, expected) in cases {
        let digest = prefix_digest(&seed, &root, &msg, &sig);
        assert_eq!(
            prefix_bits(&digest, 132, 11),
            0,
            "{label} must execute the FORS branch"
        );
        let ht = prefix_bits(&digest, 143, 18);
        let pk = prefix_fors_pk(&seed, &digest, &sig);
        let actual = verify(&seed, &root, &msg, &sig);
        assert_eq!(actual, expected, "whole production verifier: {label}");
        accepted += usize::from(actual);
        out.push_str(&format!("{{ label := \"{label}\", seed := \"{}\", root := \"{}\", msg := \"{}\", sig := \"{}\", digest := \"{}\", ht := {ht}, pk := \"{}\", accepted := {actual} }},\n", prefix_hex(&seed), prefix_hex(&root), prefix_hex(&msg), prefix_hex(&sig), prefix_hex(&digest), prefix_hex(&pk)));
    }
    assert_eq!(accepted, 4);
    out.push_str("]\nend ForsPrefixDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../extracted/Extracted/ForsPrefixDiffVectors.lean");
    if std::env::var("PQ_FORS_PREFIX_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!("OK: 22 complete production verifier executions through FORS; 4 valid KATs, 2 negative KATs, 16 synthetic forced-zero cases");
}

fn prefix_fors_pk(seed: &[u8; 16], digest: &[u8; 32], sig: &[u8; SIGNATURE_LEN]) -> [u8; 16] {
    let ht = prefix_bits(digest, 143, 18);
    let indices: [u32; 13] = std::array::from_fn(|t| prefix_bits(&digest, t * 11, 11));
    assert_eq!(crate::fors::extract_fors_indices(&digest), indices);
    assert_eq!(crate::fors::extract_ht_index(&digest), ht);
    let mut padded = [0u8; 32];
    padded[..16].copy_from_slice(seed);
    let secrets: [[u8; 16]; 13] =
        std::array::from_fn(|t| sig[16 + 16 * t..32 + 16 * t].try_into().unwrap());
    let paths: [[[u8; 16]; 11]; 12] = std::array::from_fn(|t| {
        std::array::from_fn(|h| {
            sig[224 + 176 * t + 16 * h..240 + 176 * t + 16 * h]
                .try_into()
                .unwrap()
        })
    });
    let mut roots = [[0u8; 16]; 13];
    for t in 0..12 {
        roots[t] = reference(&padded, ht, t as u32, indices[t], &secrets[t], &paths[t]);
        assert_eq!(
            reconstruct_fors_root(&padded, ht, t as u32, indices[t], &secrets[t], &paths[t]),
            roots[t]
        );
    }
    let mut last = Vec::from(padded);
    last.extend_from_slice(&reference_adrs(ht, 12, 0, 0));
    last.extend_from_slice(&secrets[12]);
    last.extend_from_slice(&[0; 16]);
    roots[12] = Sha256::digest(last)[..16].try_into().unwrap();
    let mut compression = Vec::from(padded);
    let mut adrs = [0; 32];
    adrs[4..12].copy_from_slice(&u64::from(ht).to_be_bytes());
    adrs[12..16].copy_from_slice(&4u32.to_be_bytes());
    compression.extend_from_slice(&adrs);
    for r in roots {
        compression.extend_from_slice(&r);
        compression.extend_from_slice(&[0; 16]);
    }
    let pk: [u8; 16] = Sha256::digest(compression)[..16].try_into().unwrap();
    assert_eq!(crate::fors::compute_fors_pk(&padded, ht, &roots), pk);
    pk
}
