// Whole production verification against an independent byte-level oracle.
#[test]
fn whole_verifier_corpus() {
    let mut cases = prefix_cases();
    let source = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../smart-wallet/test/c10_test_vectors.json");
    let kats: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(source).unwrap()).unwrap();
    for v in kats["vectors"].as_array().unwrap() {
        let label = v["label"].as_str().unwrap();
        if cases.iter().any(|c| c.0 == label) {
            continue;
        }
        cases.push((
            label.to_owned(),
            prefix_unhex(v["pkSeed"].as_str().unwrap())[..16]
                .try_into()
                .unwrap(),
            prefix_unhex(v["pkRoot"].as_str().unwrap())[..16]
                .try_into()
                .unwrap(),
            prefix_unhex(v["message"].as_str().unwrap())
                .try_into()
                .unwrap(),
            prefix_unhex(v["signature"].as_str().unwrap())
                .try_into()
                .unwrap(),
            v["expectValid"].as_bool().unwrap(),
        ));
    }
    assert_eq!(cases.len(), 28);
    let template = cases.iter().find(|c| c.5).unwrap().clone();
    for layer in 0..2 {
        for count in [
            0u32,
            1,
            255,
            256,
            65535,
            65536,
            9_999_999,
            10_000_000,
            0x8000_0000,
            u32::MAX,
        ] {
            let mut c = template.clone();
            c.0 = format!("counter-{layer}-{count}");
            c.4[3024 + 836 * layer..3028 + 836 * layer].copy_from_slice(&count.to_be_bytes());
            cases.push(c);
        }
    }
    let mut out = String::from("-- Generated by whole_verifier_corpus from whole Rust calls and an independent byte oracle.\nnamespace WholeVerifierDiff\nstructure Vector where\n  label : String\n  seed : String\n  root : String\n  msg : String\n  sig : String\n  digest : String\n  lastField : Nat\n  actual : Bool\n  strict : Bool\n  deriving Inhabited\ndef vectors : List Vector := [\n");
    let mut accepted = 0;
    let mut forced_refusal = 0;
    let mut wots_refusal = [0; 2];
    assert_eq!(cases.len(), 48);
    for (position, (label, seed, root, msg, sig, expected)) in cases.into_iter().enumerate() {
        let digest = prefix_digest(&seed, &root, &msg, &sig);
        let last_field = prefix_bits(&digest, 132, 11);
        let (raw, strict) = if last_field != 0 {
            forced_refusal += 1;
            (false, false)
        } else {
            let pk = prefix_fors_pk(&seed, &digest, &sig);
            let mut padded = [0; 32];
            padded[..16].copy_from_slice(&seed);
            let (tail, ok, _) =
                continuation_oracle(&padded, &sig, prefix_bits(&digest, 143, 18), pk);
            for layer in 0..2 {
                wots_refusal[layer] += usize::from(!ok[layer]);
            }
            (tail == root, tail == root && ok[0] && ok[1])
        };
        let actual = verify(&seed, &root, &msg, &sig);
        assert_eq!(actual, raw, "whole verifier versus byte oracle: {label}");
        if position < 28 {
            assert_eq!(actual, expected, "KAT/synthetic expectation: {label}");
        }
        assert!(
            !strict || actual,
            "strict acceptance must imply Rust acceptance"
        );
        accepted += usize::from(actual);
        out.push_str(&format!("{{ label := \"{label}\", seed := \"{}\", root := \"{}\", msg := \"{}\", sig := \"{}\", digest := \"{}\", lastField := {last_field}, actual := {actual}, strict := {strict} }},\n",
            prefix_hex(&seed), prefix_hex(&root), prefix_hex(&msg), prefix_hex(&sig), prefix_hex(&digest)));
    }
    assert!(accepted >= 4 && forced_refusal > 0 && wots_refusal[0] > 0 && wots_refusal[1] > 0);
    out.push_str("]\nend WholeVerifierDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../extracted/Extracted/WholeVerifierDiffVectors.lean");
    if std::env::var("PQ_WHOLE_VERIFIER_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!("OK: 48 whole production verifier calls; all 12 KATs, 16 synthetic signatures, 20 counter boundaries; accepting, forced-zero refusal and both WOTS refusal branches");
}
