-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.ForsRecovery.Types
import Extracted.ForsRecovery.FunsExternal
import Extracted.Adrs
import Extracted.Fors.Funs
import Extracted.Hash.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::ADRS_FORS_TREE]
    Source: 'sphincs-c10/src/params.rs', lines 100:0-100:34
    Visibility: public -/
@[global_simps, irreducible] def params.ADRS_FORS_TREE : Std.U32 := 3#u32

/-- [sphincs_c10::hypertree::reconstruct_fors_root]: loop body 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 509:4-527:5 -/
@[rust_loop_body]
def hypertree.reconstruct_fors_root_loop.body
  (seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (auth_path : Array (Array Std.U8 16#usize) 11#usize)
  (iter : core.ops.range.Range Std.Usize) (node : Array Std.U8 16#usize)
  (path_idx : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    16#usize) × Std.U32) (Array Std.U8 16#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done node)
  | some h =>
    let parent_idx ← path_idx >>> 1#i32
    let i ← lift (core.convert.num.FromU64U32.from ht_idx)
    let i1 ← h + 1#usize
    let i2 ← lift (UScalar.cast .U32 i1)
    let adrs ←
      address.make_adrs 0#u32 i params.ADRS_FORS_TREE tree_idx 0#u32 i2
        parent_idx
    let sibling ← Array.index_usize auth_path h
    let i3 ← lift (path_idx &&& 1#u32)
    let node1 ←
      if i3 = 0#u32
      then
        do
        let a ← hash.pad16 node
        let a1 ← hash.pad16 sibling
        hash.th_pair seed adrs a a1
      else
        do
        let a ← hash.pad16 sibling
        let a1 ← hash.pad16 node
        hash.th_pair seed adrs a a1
    ok (cont (iter1, node1, parent_idx))

/-- [sphincs_c10::hypertree::reconstruct_fors_root]: loop 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 509:4-527:5 -/
@[rust_loop]
def hypertree.reconstruct_fors_root_loop
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (ht_idx : Std.U32) (tree_idx : Std.U32)
  (auth_path : Array (Array Std.U8 16#usize) 11#usize)
  (node : Array Std.U8 16#usize) (path_idx : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  loop
    (fun (iter1, node1, path_idx1) => hypertree.reconstruct_fors_root_loop.body
      seed ht_idx tree_idx auth_path iter1 node1 path_idx1)
    (iter, node, path_idx)

/-- [sphincs_c10::hypertree::reconstruct_fors_root]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 497:0-529:1 -/
def hypertree.reconstruct_fors_root
  (seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (leaf_idx : Std.U32) (secret : Array Std.U8 16#usize)
  (auth_path : Array (Array Std.U8 16#usize) 11#usize) :
  Result (Array Std.U8 16#usize)
  := do
  let i ← lift (core.convert.num.FromU64U32.from ht_idx)
  let leaf_adrs ←
    address.make_adrs 0#u32 i params.ADRS_FORS_TREE tree_idx 0#u32 0#u32
      leaf_idx
  let a ← hash.pad16 secret
  let node ← hash.th seed leaf_adrs a
  hypertree.reconstruct_fors_root_loop
    { start := 0#usize, «end» := params.A } seed ht_idx tree_idx auth_path
    node leaf_idx

end sphincs_c10
