-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.ForsSecret.Types
import Extracted.ForsSecret.FunsExternal
import Extracted.Hash.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::hash::fors_secret]:
    Source: 'sphincs-c10/src/hash.rs', lines 410:0-419:1
    Visibility: public -/
def hash.fors_secret
  (sk_seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (leaf_idx : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let s ← lift (Array.to_slice sk_seed)
  let s1 ←
    lift (Array.to_slice
      (Array.make 4#usize [ 102#u8, 111#u8, 114#u8, 115#u8 ]))
  let a ← lift (core.num.U32.to_be_bytes ht_idx)
  let s2 ← lift (Array.to_slice a)
  let a1 ← lift (core.num.U32.to_be_bytes tree_idx)
  let s3 ← lift (Array.to_slice a1)
  let a2 ← lift (core.num.U32.to_be_bytes leaf_idx)
  let s4 ← lift (Array.to_slice a2)
  let s5 ← lift (Array.to_slice (Array.make 5#usize [ s, s1, s2, s3, s4 ]))
  let a3 ← hash.sha256_parts s5
  hash.truncate a3

end sphincs_c10
