/*
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_port.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_i2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitBUTTONSPeripheral functional group */
/* Alias for GPIOC peripheral */
#define BOARD_SW3_GPIO GPIOC
/* Alias for GPIOA peripheral */
#define BOARD_SW2_GPIO GPIOA

/* Definitions for BOARD_InitLEDsPeripheral functional group */
/* Alias for GPIOC peripheral */
#define BOARD_LEDS_GPIO GPIOC

/* Definitions for BOARD_InitDEBUG_UARTPeripheral functional group */
/* Definition of peripheral ID */
#define BOARD_DEBUG_UART_PERIPHERAL LPUART4
/* Definition of the clock source frequency */
#define BOARD_DEBUG_UART_CLOCK_SOURCE 12000000UL

/* Definitions for BOARD_InitACCELPeripheral functional group */
/* BOARD_InitACCELPeripheral defines for I2C3 */
/* Definition of peripheral ID */
#define BOARD_ACCEL_PERIPHERAL I2C3
/* Definition of the clock source */
#define BOARD_ACCEL_CLOCK_SOURCE I2C3_CLK_SRC
/* Definition of the clock source frequency */
#define BOARD_ACCEL_CLK_FREQ CLOCK_GetFreq(BOARD_ACCEL_CLOCK_SOURCE)
/* Alias for GPIOC peripheral */
#define BOARD_ACCEL_INT1_GPIO GPIOC

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t BOARD_DEBUG_UART_config;
extern const i2c_master_config_t BOARD_ACCEL_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);
void BOARD_InitBUTTONSPeripheral(void);
void BOARD_InitLEDsPeripheral(void);
void BOARD_InitDEBUG_UARTPeripheral(void);
void BOARD_InitACCELPeripheral(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
