//! Fault-sweep target ELF for `tools/sca/fault_sweep_fw_verify.py`: thin
//! `#[no_mangle]` wrappers around each step of `fw_manifest::ManifestRef`'s
//! verification chain, plus a `sca_fw_verify_all` that mirrors the FSBL's
//! canonical call order.
//!
//! Fixtures (baked at build.rs time, deterministic vendor keypair):
//!   - `MANIFEST_VALID`      — fully valid; every `verify_*` returns `Ok`.
//!   - `MANIFEST_BAD_SIG`    — signature replaced with all-zeros; `verify_signature`
//!                             rejects, but `verify_structural` / `verify_crc` /
//!                             `verify_digest` / `verify_vendor_fpr` still pass.
//!                             **This is the attacker's vector**: legitimate-
//!                             looking manifest, attacker-controlled image,
//!                             attacker-supplied bogus signature.
//!   - `MANIFEST_BAD_DIGEST` — `manifest_digest` field flipped; both
//!                             `verify_digest` AND `verify_signature` reject
//!                             (the sig was signed over the *original* digest).
//!
//! Each entry-point returns:
//!   - `0`  on `Ok(())`
//!   - non-zero `VerifyError` discriminant on `Err(_)`
//!     (the harness only cares about 0 vs non-zero — any non-zero is "rejected").
//!
//! Build:  cargo build --release --target thumbv8m.main-none-eabi
//!         (or: make -C tools/sca build-fw-verify)
#![no_std]
#![no_main]

use cortex_m_rt::entry;
use fw_manifest::{MANIFEST_SIZE, ManifestRef, VerifyError};
use panic_halt as _;
use sphincs_c10::params::N;

// ---------------------------------------------------------------------------
// Baked-in fixtures (generated by build.rs)
// ---------------------------------------------------------------------------

#[used]
#[link_section = ".rodata.fw_verify.valid"]
static MANIFEST_VALID: [u8; MANIFEST_SIZE] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/fixture_valid.bin"));

#[used]
#[link_section = ".rodata.fw_verify.bad_sig"]
static MANIFEST_BAD_SIG: [u8; MANIFEST_SIZE] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/fixture_bad_sig.bin"));

#[used]
#[link_section = ".rodata.fw_verify.bad_digest"]
static MANIFEST_BAD_DIGEST: [u8; MANIFEST_SIZE] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/fixture_bad_digest.bin"));

#[used]
static VENDOR_PK_SEED: [u8; N] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/vendor_pk_seed.bin"));

#[used]
static VENDOR_PK_ROOT: [u8; N] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/vendor_pk_root.bin"));

/// Rollback floor used by `verify_rollback`. The valid fixture has
/// `fw_version=100`; this floor of `0` means the rollback check always
/// passes on the valid fixture.
const ROLLBACK_FLOOR: u32 = 0;

// ---------------------------------------------------------------------------
// VerifyError → u32 discriminant. The harness only cares about 0 vs non-zero.
// ---------------------------------------------------------------------------

#[inline(always)]
fn err_code(e: VerifyError) -> u32 {
    match e {
        VerifyError::BadMagic => 1,
        VerifyError::BadVersion => 2,
        VerifyError::BadSlot => 3,
        VerifyError::BadCrc => 4,
        VerifyError::BadDigest => 5,
        VerifyError::BadSignature => 6,
        VerifyError::WrongVendor => 7,
        VerifyError::BelowRollback => 8,
        VerifyError::SecureHashMismatch => 9,
        VerifyError::NonsecureHashMismatch => 10,
    }
}

#[inline(always)]
fn flatten(r: Result<(), VerifyError>) -> u32 {
    match r {
        Ok(()) => 0,
        Err(e) => err_code(e),
    }
}

// ---------------------------------------------------------------------------
// Per-step entry points. `manifest_ptr` lets the harness swap fixtures at
// emulation time (it sets r0 to the address of MANIFEST_VALID, _BAD_SIG, etc.).
// ---------------------------------------------------------------------------

/// `verify_structural` — magic + version + slot. Cheap; no hashing.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_structural(manifest_ptr: *const u8) -> u32 {
    // SAFETY: harness maps `MANIFEST_SIZE` (=8192) bytes at this address.
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_structural())
}

/// `verify_crc` — CRC-32 over `[0..8188)`.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_crc(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_crc())
}

/// `verify_digest` — recompute SHA-256 over (`fw_version`, secure_hash, ns_hash)
/// and compare against the stored `manifest_digest`.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_digest(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_digest())
}

/// `verify_vendor_fpr` — SHA-256(pk_seed || pk_root) == stored fpr.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_vendor_fpr(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_vendor_fpr(&VENDOR_PK_SEED, &VENDOR_PK_ROOT))
}

/// `verify_signature` — SPHINCS+C10 verify of `signature` over `manifest_digest`
/// with the vendor public key. This is the heavy step.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_signature(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_signature(&VENDOR_PK_SEED, &VENDOR_PK_ROOT))
}

/// `verify_rollback` — `fw_version > rollback_floor`.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_rollback(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    flatten(ManifestRef::new(bytes).verify_rollback(ROLLBACK_FLOOR))
}

/// Full chain — mirrors the FSBL's call order. Reject as early as possible:
///   structural → crc → vendor_fpr → digest → signature → rollback.
/// (vendor_fpr is cheap and before digest so a wrong-vendor manifest gets
///  short-circuited without paying the SHA-256.)
///
/// Returns 0 only if EVERY step passed. **The FI-success criterion**: any
/// single skip that converts the bad fixture's non-zero return into 0 is a
/// security finding.
#[inline(never)]
#[no_mangle]
pub extern "C" fn sca_fw_verify_all(manifest_ptr: *const u8) -> u32 {
    let bytes: &[u8; MANIFEST_SIZE] = unsafe { &*(manifest_ptr as *const [u8; MANIFEST_SIZE]) };
    let m = ManifestRef::new(bytes);
    if let Err(e) = m.verify_structural() {
        return err_code(e);
    }
    if let Err(e) = m.verify_crc() {
        return err_code(e);
    }
    if let Err(e) = m.verify_vendor_fpr(&VENDOR_PK_SEED, &VENDOR_PK_ROOT) {
        return err_code(e);
    }
    if let Err(e) = m.verify_digest() {
        return err_code(e);
    }
    if let Err(e) = m.verify_signature(&VENDOR_PK_SEED, &VENDOR_PK_ROOT) {
        return err_code(e);
    }
    if let Err(e) = m.verify_rollback(ROLLBACK_FLOOR) {
        return err_code(e);
    }
    0
}

// ---------------------------------------------------------------------------
// Keep-statics so cortex-m-rt's link.x doesn't `--gc-sections` away the
// `#[no_mangle]` exports. (Re-iterates the lesson from fi_target/c10v_target.)
// ---------------------------------------------------------------------------

#[used]
static _KEEP_STRUCT: extern "C" fn(*const u8) -> u32 = sca_fw_verify_structural;
#[used]
static _KEEP_CRC: extern "C" fn(*const u8) -> u32 = sca_fw_verify_crc;
#[used]
static _KEEP_DIGEST: extern "C" fn(*const u8) -> u32 = sca_fw_verify_digest;
#[used]
static _KEEP_VENDOR: extern "C" fn(*const u8) -> u32 = sca_fw_verify_vendor_fpr;
#[used]
static _KEEP_SIG: extern "C" fn(*const u8) -> u32 = sca_fw_verify_signature;
#[used]
static _KEEP_ROLLBACK: extern "C" fn(*const u8) -> u32 = sca_fw_verify_rollback;
#[used]
static _KEEP_ALL: extern "C" fn(*const u8) -> u32 = sca_fw_verify_all;

#[entry]
fn main() -> ! {
    // Keep symbols + fixture statics alive against --gc-sections + LLVM CSE.
    core::hint::black_box(&_KEEP_STRUCT);
    core::hint::black_box(&_KEEP_CRC);
    core::hint::black_box(&_KEEP_DIGEST);
    core::hint::black_box(&_KEEP_VENDOR);
    core::hint::black_box(&_KEEP_SIG);
    core::hint::black_box(&_KEEP_ROLLBACK);
    core::hint::black_box(&_KEEP_ALL);
    core::hint::black_box(&MANIFEST_VALID[0]);
    core::hint::black_box(&MANIFEST_BAD_SIG[0]);
    core::hint::black_box(&MANIFEST_BAD_DIGEST[0]);
    core::hint::black_box(&VENDOR_PK_SEED[0]);
    core::hint::black_box(&VENDOR_PK_ROOT[0]);
    loop {
        cortex_m::asm::nop();
    }
}
