/- Corpus evidence complementing the universal ForsSpecBridge theorems.
   Expected outputs are generated by executing the shipped Rust. This tests
   the Aeneas translation on these inputs; it is not translation soundness. -/
import Extracted.ForsSpecBridge
import Extracted.ForsExtractDiffVectors

namespace ForsExtractDiff
open Aeneas Aeneas.Std Extracted.Equiv

def decode (bytes : Array UInt8) : Option (Nat × Array Nat × Nat × Array Nat) := do
  let l := bytes.toList.map (fun b => (⟨BitVec.ofNat 8 b.toNat⟩ : Std.U8))
  if h : l.length = 32 then
    let digest : Std.Array Std.U8 32#usize := ⟨l, by simpa using h⟩
    match sphincs_c10.fors.extract_ht_index digest,
        sphincs_c10.fors.extract_fors_indices digest with
    | .ok ht, .ok indices =>
      some (ht.val, (indices.val.map (·.val)).toArray,
        SphincsCVerify.Util.extractHtIndex (toSpecDigest digest),
        SphincsCVerify.Util.extractForsIndices (toSpecDigest digest))
    | _, _ => none
  else none

def agreesWith (d : Array UInt8) (ht : Nat) (indices : Array Nat) : Bool :=
  match decode d with
  | some (h, f, vh, vf) => h == ht && f == indices && vh == ht && vf == indices
  | none => false

def check : IO Unit := do
  unless vectors.length == 262 do
    throw (IO.userError "FORS differential inventory changed")
  for (d, ht, indices) in vectors do
    unless d.size == 32 && indices.size == 13 && agreesWith d ht indices do
      throw (IO.userError "Rust / extracted / vendored digest decoder mismatch")
    -- Every changed expectation must be rejected, independently for HT and FORS.
    if agreesWith d (ht + 1) indices || agreesWith d ht (indices.set! 12 (indices[12]! + 1)) then
      throw (IO.userError "FORS differential failed to reject a changed expectation")
  unless decode #[] == none do
    throw (IO.userError "FORS differential accepted a wrong-length input")
  IO.println "OK: 262 Rust/extracted/vendored digest vectors; 524 wrong-field controls; wrong-length control"

#eval check
end ForsExtractDiff
