"""Generic flow renderer — `python -m flows [name]` (see flows/__init__.py)."""
import argparse
import os
import sys

import flows
from pq1 import flow as pqflow
from pq1 import layout, status


def _list():
    ns = flows.names()
    w = max((len(n) for n in ns), default=0)
    for n in ns:
        mod = flows.get(n)
        ends = ", ".join(sorted(getattr(mod, "ENDS", {})))
        smp = ", ".join(flows.sample_names(n))
        print(f"{n:{w}s} {len(mod.SCREENS)} screens"
              + (f"   ends: {ends}" if ends else "")
              + (f"   samples: {smp}" if smp else ""))


# ----------------------------------------------------------------- manifest --

def _line_md(ln):
    s = layout.line_str(ln)          # a SemiBold name line reads bold here
    return f"**{s}**" if layout.line_weight(ln) == "semibold" else s


def _screen_text(s):
    if s["kind"] in ("detail", "value"):
        if s.get("words"):   # a word grid: the words in reading order
            body = " · ".join(s["words"])
        else:
            pages = s.get("pages") or [s.get("lines", [])]   # a paged value: ‖ between pages
            body = " ‖ ".join(" / ".join(_line_md(ln) for ln in p) for p in pages)
        lab = s.get("label", "")
        return f"{lab}: {body}" if lab else body
    return s.get("bottom", "")


def _status_bits(s):
    anim = s["anim"] if "anim" in s else status.default_anim(s)
    bits = []
    lead = s.get("lead")
    if lead:   # a film played first (status.LedAnim)
        lb = f"lead {lead['anim']}"
        if lead.get("severity"):
            lb += f" {lead['severity']}"
        if lead.get("busy"):
            lb += f' busy "{lead["busy"]}"'
        bits.append(lb)
    bits.append(f"{anim} → {s.get('result', 'check')}")
    for k in ("miss", "match"):     # an entry's verdict tails (pin_entering)
        tail = s.get(k)
        if tail:
            bits.append(f"{k} {tail.get('anim')} → {tail.get('bottom', '')}")
    if s.get("state", "done") != "done":
        bits.append(s["state"])
    if s.get("busy"):
        bits.append(f'busy "{s["busy"]}"')
    return bits


def _screen_extras(s):
    ex = []
    if s.get("pulse"):
        ex.append("**pulse**")
    if s.get("pages"):
        ex.append(f"{len(s['pages'])} pages")
    if s["kind"] == "status":
        ex.append(", ".join(_status_bits(s)))
    if s["kind"] == "hero" and s.get("hint"):
        ex.append("hint")
    if s["kind"] == "hero" and s.get("band_chev"):
        ex.append("band chevron ▸, no corner chevrons")
    if s["kind"] == "confirm":
        ex.append("early exit — OR VIEW MORE ▸ / ◂ TO GO BACK")
    if s.get("commit"):
        ex.append("commit")
    if s.get("dwell"):
        ex.append(f"dwell {s['dwell']}")
    return ", ".join(ex)


def _defaults_summary(mod):
    d = getattr(mod, "DEFAULTS", None) or {}
    bits = []
    if "icon" in d:
        bits.append(f"icon `{d['icon']}`")
    tok = d.get("token") or {}
    if "fill" in tok:
        bits.append("token fill `#%02x%02x%02x`" % tuple(tok["fill"]))
    if "palette" in tok:
        bits.append(f"trail palette `{tok['palette']}`")
    return ", ".join(bits)


def _manifest():
    """rewrite flows/MANIFEST.md — which screen types each flow uses"""
    lines = ["<!-- generated by `python -m flows --manifest` — do not edit -->",
             "# Flow manifest", ""]
    for n in flows.names():
        mod = flows.get(n)
        scr = flows.screens(n)
        lines.append(f"## {n} — {len(scr)} screens")
        d = _defaults_summary(mod)
        if d:
            lines.append(f"defaults: {d}")
        smp = flows.sample_names(n)
        if smp:                       # the renders cycle the samples by slot
            ends_ = sorted(getattr(mod, "ENDS", {}))
            slots = [(e, False) for e in ends_]
            if any(s.get("kind") == "confirm" for s in scr):
                slots += [(e, True) for e in ends_]
            lines.append("samples (table = the first): " + ", ".join(
                f"{smp[flows.sample_slot(n, e, early)]} → "
                f"{'early' if early else 'full'}/{e}" for e, early in slots))
        lines += ["", "| # | id | kind | text | extras |",
                  "|---|----|------|------|--------|"]
        for i, s in enumerate(scr, 1):
            lines.append(f"| {i} | {s.get('id', '')} | {s['kind']} "
                         f"| {_screen_text(s)} | {_screen_extras(s)} |")
        ends = getattr(mod, "ENDS", {})
        if ends:
            lines += ["", "ends: " + ", ".join(
                f"{k} ({', '.join(_status_bits(e))})"
                for k, e in sorted(ends.items()))]
        lines.append("")
    out = os.path.join(os.path.dirname(flows.__file__), "MANIFEST.md")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(len(flows.names()), "flows ->", out)


# --------------------------------------------------------------------- main --

def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="python -m flows", description="Render a flow to GIF / frame PNGs")
    ap.add_argument("flow", nargs="?", help="flow name (omit to list the flows)")
    ap.add_argument("--end", help="ending from the flow's ENDS, or 'all'")
    ap.add_argument("--early", action="store_true",
                    help="take the mid-flow Confirm? early exit: commit "
                         "straight to the ending, skipping the remaining "
                         "details (long flows only)")
    ap.add_argument("-o", "--out", help="output GIF (default with --end: "
                                        "renders/flows/<flow>/{success,cancel}/"
                                        "<leaf>_{full,early}_<end>.gif; without: "
                                        "renders/flows/<flow>_flow.gif, family flows "
                                        "renders/flows/<family>/<leaf>/<leaf>.gif)")
    ap.add_argument("--fps", type=int, default=30, help="30 preview, 14 = panel rate")
    ap.add_argument("--frames", help="directory for per-frame PNGs (panel playback)")
    ap.add_argument("--loops", type=int, default=1, help="full passes to render")
    ap.add_argument("--sample", help="example token from the flow's SAMPLES "
                                     "(a symbol), or 'all'; default: the "
                                     "variant's slot in the ending matrix "
                                     "cycles through them")
    ap.add_argument("--manifest", action="store_true",
                    help="rewrite flows/MANIFEST.md from the registry and exit")
    a = ap.parse_args(argv)

    if a.manifest:
        _manifest()
        return

    if not a.flow:
        _list()
        return

    if a.end == "all":
        ends = sorted(getattr(flows.get(a.flow), "ENDS", {}))
        if not ends:
            raise SystemExit(f"flow {a.flow!r} declares no ENDS")
        if a.out or a.frames:
            raise SystemExit("--end all renders several GIFs; drop -o/--frames")
    else:
        ends = [a.end]

    names = flows.sample_names(a.flow)
    if a.sample and not names:
        raise SystemExit(f"flow {a.flow!r} declares no SAMPLES")
    if a.sample == "all":
        if a.out or a.frames:
            raise SystemExit("--sample all renders several GIFs; drop -o/--frames")
        samples = list(names)
    elif a.sample:
        samples = [a.sample]
    else:
        samples = [None]        # the variant's slot cycles the samples

    for end in ends:
        for sample in samples:
            # a flow with SAMPLES: the variant's matrix slot picks the
            # example token unless --sample names one
            picked = sample
            if picked is None and names:
                picked = names[flows.sample_slot(a.flow, end, a.early)]
            try:
                scr = flows.screens(a.flow, end, early=a.early, sample=picked)
            except ValueError as e:
                raise SystemExit(str(e))
            tag = f"_{picked.lower()}" if picked else ""
            if a.out:
                out = a.out
            elif end:
                # ending renders get a folder per flow, split by outcome:
                # success/ = the ending resolves done; cancel/ = declined/failed
                leaf = a.flow.rsplit("/", 1)[1] if "/" in a.flow else a.flow
                oc = ("success" if flows.get(a.flow).ENDS[end].get("state", "done")
                      == "done" else "cancel")
                mode = "early" if a.early else "full"
                out = f"renders/flows/{a.flow}/{oc}/{leaf}_{mode}_{end}{tag}.gif"
            elif "/" in a.flow:                     # family flow: one folder per flow
                leaf = a.flow.rsplit("/", 1)[1]
                out = f"renders/flows/{a.flow}/{leaf}{'_early' if a.early else ''}{tag}.gif"
            else:
                out = f"renders/flows/{a.flow}_flow{'_early' if a.early else ''}{tag}.gif"
            frames = pqflow.render_flow(scr, fps=a.fps, loops=a.loops)
            pqflow.save_gif(frames, out, a.fps, a.frames)


if __name__ == "__main__":
    main()
