//! Build script for the secure-miri-tests mount crate.
//!
//! Replicates `secure/build.rs::generate_font_flat` BYTE-IDENTICALLY so the
//! mounted `secure/src/ui/secret_text.rs` can `include!(concat!(env!("OUT_DIR"),
//! "/font_flat.rs"))` exactly as it does inside the firmware crate. The only
//! change is the input path (`../secure/assets/font_5x8.raw` instead of
//! `assets/font_5x8.raw`, because this crate's package root differs); the raw
//! path string is never embedded in the generated output, so the emitted
//! `font_flat.rs` is the same bytes the firmware build produces.
//!
//! KEEP THIS FUNCTION IN SYNC WITH `secure/build.rs` — if the firmware
//! generator changes, copy the new version here verbatim.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    generate_font_flat(&out_dir);
}

/// Decode the vendored `assets/font_5x8.raw` (embedded-graphics'
/// `MonoFont::FONT_5X8` ASCII variant) into a flat `[[u8; 5]; 96]` table
/// emitted to `OUT_DIR/font_flat.rs`. Consumed by `secure/src/ui/
/// secret_text.rs` for the F-24 constant-time glyph blit.
///
/// The raw file is a 1-bit-per-pixel 80×48 bitmap (480 bytes) laid out
/// as 16 columns × 6 rows of 5×8 glyphs covering ASCII 0x20..=0x7F (96
/// printable chars including DEL). Pixel rows are packed MSB-first
/// into 10 bytes per row (80 / 8). Glyph (ch-0x20) sits at
/// `(px = ((ch-0x20) % 16) * 5, py = ((ch-0x20) / 16) * 8)`.
///
/// Output column-byte format: bit `r` of byte `c` = pixel at column `c`,
/// row `r` (0 = top). Matches the SSD1306 page layout used by
/// `Framebuf::draw_iter`, so the constant-time blit ORs column-bytes
/// directly into the framebuffer.
fn generate_font_flat(out_dir: &PathBuf) {
    let raw_path = "../secure/assets/font_5x8.raw";
    println!("cargo:rerun-if-changed={raw_path}");

    let raw = fs::read(raw_path)
        .unwrap_or_else(|e| panic!("vendored {raw_path} missing or unreadable: {e}"));

    const BITMAP_W: usize = 80;
    const BITMAP_H: usize = 48;
    const BYTES_PER_ROW: usize = BITMAP_W / 8; // 10
    assert_eq!(
        raw.len(),
        BITMAP_W * BITMAP_H / 8,
        "FONT_5X8 raw must be exactly {} bytes ({}×{}@1bpp); got {}",
        BITMAP_W * BITMAP_H / 8,
        BITMAP_W,
        BITMAP_H,
        raw.len()
    );

    const GLYPH_W: usize = 5;
    const GLYPH_H: usize = 8;
    const CHARS_PER_ROW: usize = 16;
    const FIRST_CHAR: u8 = 0x20;
    const LAST_CHAR: u8 = 0x7F;
    const N_GLYPHS: usize = (LAST_CHAR - FIRST_CHAR + 1) as usize; // 96

    // Helper: pixel (px, py) of the bitmap = MSB-first bit in
    // `raw[py * BYTES_PER_ROW + px/8]`.
    let pixel = |px: usize, py: usize| -> bool {
        let byte = raw[py * BYTES_PER_ROW + px / 8];
        (byte >> (7 - (px % 8))) & 1 != 0
    };

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by secure/build.rs — do not edit.\n");
    out.push_str(&format!(
        "// Source: secure/assets/font_5x8.raw (MIT, embedded-graphics v0.8.2,\n\
         //         `fonts/raw/ascii/font_5x8.raw` upstream; vendored verbatim).\n\
         //         See secure/assets/font_5x8.LICENSE for attribution.\n\
         //\n\
         // Layout: glyph for ASCII 0x{FIRST_CHAR:02x}+i at FONT_FLAT_5X8[i].\n\
         //   Each glyph is GLYPH_W (=5) column-bytes; each byte's bit `r`\n\
         //   is the pixel at column .x, row .y=r. Matches SSD1306 page\n\
         //   format so the CT blit can OR directly into the framebuffer.\n\n",
    ));
    out.push_str(&format!(
        "pub const FONT_FIRST_CHAR: u8 = 0x{FIRST_CHAR:02x};\n"
    ));
    out.push_str(&format!(
        "pub const FONT_LAST_CHAR: u8  = 0x{LAST_CHAR:02x};\n"
    ));
    out.push_str(&format!("pub const FONT_GLYPH_W: usize = {GLYPH_W};\n"));
    out.push_str(&format!("pub const FONT_GLYPH_H: usize = {GLYPH_H};\n"));
    out.push_str(&format!("pub const FONT_N_GLYPHS: usize = {N_GLYPHS};\n\n"));
    out.push_str("pub static FONT_FLAT_5X8: [[u8; FONT_GLYPH_W]; FONT_N_GLYPHS] = [\n");

    for ch in FIRST_CHAR..=LAST_CHAR {
        let glyph_idx = (ch - FIRST_CHAR) as usize;
        let glyph_x = (glyph_idx % CHARS_PER_ROW) * GLYPH_W;
        let glyph_y = (glyph_idx / CHARS_PER_ROW) * GLYPH_H;

        let mut cols = [0u8; GLYPH_W];
        for cc in 0..GLYPH_W {
            let mut col_byte: u8 = 0;
            for row in 0..GLYPH_H {
                if pixel(glyph_x + cc, glyph_y + row) {
                    col_byte |= 1u8 << row;
                }
            }
            cols[cc] = col_byte;
        }

        let printable = if ch == b'\\' {
            "\\\\".to_string()
        } else if ch == 0x7F {
            "DEL".to_string()
        } else {
            format!("{}", ch as char)
        };
        out.push_str(&format!(
            "    /* 0x{ch:02x} {printable:>3} */ [0x{:02x}, 0x{:02x}, 0x{:02x}, 0x{:02x}, 0x{:02x}],\n",
            cols[0], cols[1], cols[2], cols[3], cols[4]
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("font_flat.rs"), out).expect("writing font_flat.rs");
}
