-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqsigner_domain]: function definitions
import Aeneas
import Extracted.SlotKdf.Types
import Extracted.SlotKdf.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqsigner_domain

/-- Trait implementation: [zeroize::{impl zeroize::Zeroize for Z}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.8.2/src/lib.rs', lines 297:0-299:23
    Name pattern: [zeroize::Zeroize<@Z>] -/
@[reducible, rust_trait_impl "zeroize::Zeroize<@Z>"]
def zeroize.Zeroize.Blanket {Z : Type} (DefaultIsZeroesInst :
  zeroize.DefaultIsZeroes Z) : zeroize.Zeroize Z := {
  zeroize := zeroize.Zeroize.Blanket.zeroize DefaultIsZeroesInst
}

/-- Trait implementation: [zeroize::{impl zeroize::DefaultIsZeroes for u8}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zeroize-1.8.2/src/lib.rs', lines 309:10-309:40
    Name pattern: [zeroize::DefaultIsZeroes<u8>] -/
@[reducible, rust_trait_impl "zeroize::DefaultIsZeroes<u8>"]
def U8.Insts.ZeroizeDefaultIsZeroes : zeroize.DefaultIsZeroes Std.U8 := {
  coremarkerCopyInst := core.marker.CopyU8
  coredefaultDefaultInst := core.default.DefaultU8
}

/-- [pqsigner_domain::slot_master_entropy_from_bip39]:
    Source: 'domain/src/lib.rs', lines 482:0-507:1
    Visibility: public -/
def slot_master_entropy_from_bip39
  (bip39_seed : Array Std.U8 64#usize) (account_index : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  if account_index = 0#u32
  then
    let buf := Array.repeat 85#usize 0#u8
    let (s, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
        { start := 0#usize, «end» := 20#usize }
    let s1 ←
      lift (Array.to_slice
        (Array.make 20#usize [
          112#u8, 113#u8, 119#u8, 97#u8, 108#u8, 108#u8, 101#u8, 116#u8, 45#u8,
          115#u8, 108#u8, 111#u8, 116#u8, 45#u8, 109#u8, 97#u8, 115#u8, 116#u8,
          101#u8, 114#u8
          ]))
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let buf1 := index_mut_back s2
    let (s3, index_mut_back1) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
        { start := 20#usize, «end» := 84#usize }
    let s4 ← lift (Array.to_slice bip39_seed)
    let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
    let buf2 := index_mut_back1 s5
    let buf3 ← Array.update buf2 84#usize 0#u8
    let s6 ← lift (Array.to_slice buf3)
    let out ← sha256_bytes s6
    let _ ←
      Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
        U8.Insts.ZeroizeDefaultIsZeroes) buf3
    ok out
  else
    let buf := Array.repeat 93#usize 0#u8
    let (s, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
        { start := 0#usize, «end» := 25#usize }
    let s1 ←
      lift (Array.to_slice
        (Array.make 25#usize [
          112#u8, 113#u8, 119#u8, 97#u8, 108#u8, 108#u8, 101#u8, 116#u8, 45#u8,
          115#u8, 108#u8, 111#u8, 116#u8, 45#u8, 109#u8, 97#u8, 115#u8, 116#u8,
          101#u8, 114#u8, 45#u8, 97#u8, 99#u8, 99#u8, 116#u8
          ]))
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let buf1 := index_mut_back s2
    let (s3, index_mut_back1) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
        { start := 25#usize, «end» := 89#usize }
    let s4 ← lift (Array.to_slice bip39_seed)
    let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
    let buf2 := index_mut_back1 s5
    let (s6, index_mut_back2) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
        { start := 89#usize, «end» := 93#usize }
    let a ← lift (core.num.U32.to_be_bytes account_index)
    let s7 ← lift (Array.to_slice a)
    let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
    let buf3 := index_mut_back2 s8
    let s9 ← lift (Array.to_slice buf3)
    let out ← sha256_bytes s9
    let _ ←
      Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
        U8.Insts.ZeroizeDefaultIsZeroes) buf3
    ok out

/-- [pqsigner_domain::derive_c10_master_from_bip39_seed]:
    Source: 'domain/src/lib.rs', lines 563:0-620:1
    Visibility: public -/
def derive_c10_master_from_bip39_seed
  (bip39_seed : Array Std.U8 64#usize) (account_index : Std.U32) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize))
  := do
  let domain ←
    if account_index = 0#u32
    then
      ok (Array.to_slice
        (Array.make 13#usize [
          115#u8, 112#u8, 104#u8, 105#u8, 110#u8, 99#u8, 115#u8, 45#u8, 99#u8,
          54#u8, 45#u8, 118#u8, 49#u8
          ]))
    else
      ok (Array.to_slice
        (Array.make 18#usize [
          115#u8, 112#u8, 104#u8, 105#u8, 110#u8, 99#u8, 115#u8, 45#u8, 99#u8,
          54#u8, 45#u8, 118#u8, 49#u8, 45#u8, 97#u8, 99#u8, 99#u8, 116#u8
          ]))
  let master ←
    if account_index = 0#u32
    then
      do
      let s ← lift (Array.to_slice bip39_seed)
      hmac_sha512_bytes domain s
    else
      do
      let msg := Array.repeat 68#usize 0#u8
      let (s, index_mut_back) ←
        core.array.Array.index_mut (core.ops.index.IndexMutSlice
          (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) msg
          { start := 0#usize, «end» := 64#usize }
      let s1 ← lift (Array.to_slice bip39_seed)
      let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
      let msg1 := index_mut_back s2
      let (s3, index_mut_back1) ←
        core.array.Array.index_mut (core.ops.index.IndexMutSlice
          (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) msg1
          { start := 64#usize, «end» := 68#usize }
      let a ← lift (core.num.U32.to_be_bytes account_index)
      let s4 ← lift (Array.to_slice a)
      let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
      let msg2 := index_mut_back1 s5
      let s6 ← lift (Array.to_slice msg2)
      let m ← hmac_sha512_bytes domain s6
      let _ ←
        Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
          U8.Insts.ZeroizeDefaultIsZeroes) msg2
      ok m
  let master_lo ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) master
      { «end» := 32#usize }
  let pk_buf := Array.repeat 39#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) pk_buf
      { start := 0#usize, «end» := 7#usize }
  let s1 ←
    lift (Array.to_slice
      (Array.make 7#usize [
        112#u8, 107#u8, 95#u8, 115#u8, 101#u8, 101#u8, 100#u8
        ]))
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let pk_buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) pk_buf1
      { start := 7#usize, «end» := 39#usize }
  let s4 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 master_lo
  let pk_buf2 := index_mut_back1 s4
  let s5 ← lift (Array.to_slice pk_buf2)
  let pk_digest ← sha256_bytes s5
  let pk_seed := Array.repeat 32#usize 0#u8
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) pk_seed
      { «end» := 16#usize }
  let s7 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) pk_digest
      { «end» := 16#usize }
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let sk_buf := Array.repeat 39#usize 0#u8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sk_buf
      { start := 0#usize, «end» := 7#usize }
  let s10 ←
    lift (Array.to_slice
      (Array.make 7#usize [
        115#u8, 107#u8, 95#u8, 115#u8, 101#u8, 101#u8, 100#u8
        ]))
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let sk_buf1 := index_mut_back3 s11
  let (s12, index_mut_back4) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sk_buf1
      { start := 7#usize, «end» := 39#usize }
  let s13 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s12 master_lo
  let sk_buf2 := index_mut_back4 s13
  let s14 ← lift (Array.to_slice sk_buf2)
  let sk_seed ← sha256_bytes s14
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) pk_buf2
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) sk_buf2
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) master
  let pk_seed1 := index_mut_back2 s8
  ok (pk_seed1, sk_seed)

/-- [pqsigner_domain::slot_entropy]:
    Source: 'domain/src/lib.rs', lines 727:0-737:1
    Visibility: public -/
def slot_entropy
  (master_entropy : Array Std.U8 32#usize) (chain_id : Std.U64)
  (slot_index : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 56#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice master_entropy)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 44#usize }
  let s4 ←
    lift (Array.to_slice
      (Array.make 12#usize [
        115#u8, 108#u8, 111#u8, 116#u8, 95#u8, 101#u8, 110#u8, 116#u8, 114#u8,
        111#u8, 112#u8, 121#u8
        ]))
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 44#usize, «end» := 52#usize }
  let a ← lift (core.num.U64.to_be_bytes chain_id)
  let s7 ← lift (Array.to_slice a)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := 52#usize, «end» := 56#usize }
  let a1 ← lift (core.num.U32.to_be_bytes slot_index)
  let s10 ← lift (Array.to_slice a1)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let s12 ← lift (Array.to_slice buf4)
  let out ← sha256_bytes s12
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) buf4
  ok out

/-- [pqsigner_domain::derive_c10_slot_seeds]:
    Source: 'domain/src/lib.rs', lines 742:0-762:1 -/
def derive_c10_slot_seeds
  (slot_entropy1 : Array Std.U8 32#usize) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize))
  := do
  let sk_buf := Array.repeat 48#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sk_buf
      { start := 0#usize, «end» := 16#usize }
  let s1 ←
    lift (Array.to_slice
      (Array.make 16#usize [
        115#u8, 108#u8, 111#u8, 116#u8, 95#u8, 99#u8, 49#u8, 48#u8, 95#u8,
        115#u8, 107#u8, 95#u8, 115#u8, 101#u8, 101#u8, 100#u8
        ]))
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let sk_buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sk_buf1
      { start := 16#usize, «end» := 48#usize }
  let s4 ← lift (Array.to_slice slot_entropy1)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let sk_buf2 := index_mut_back1 s5
  let s6 ← lift (Array.to_slice sk_buf2)
  let sk_seed ← sha256_bytes s6
  let pk_buf := Array.repeat 48#usize 0#u8
  let (s7, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) pk_buf
      { start := 0#usize, «end» := 16#usize }
  let s8 ←
    lift (Array.to_slice
      (Array.make 16#usize [
        115#u8, 108#u8, 111#u8, 116#u8, 95#u8, 99#u8, 49#u8, 48#u8, 95#u8,
        112#u8, 107#u8, 95#u8, 115#u8, 101#u8, 101#u8, 100#u8
        ]))
  let s9 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s7 s8
  let pk_buf1 := index_mut_back2 s9
  let (s10, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) pk_buf1
      { start := 16#usize, «end» := 48#usize }
  let s11 ← lift (Array.to_slice slot_entropy1)
  let s12 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s10 s11
  let pk_buf2 := index_mut_back3 s12
  let s13 ← lift (Array.to_slice pk_buf2)
  let pk_digest ← sha256_bytes s13
  let pk_seed := Array.repeat 32#usize 0#u8
  let (s14, index_mut_back4) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) pk_seed
      { «end» := 16#usize }
  let s15 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) pk_digest
      { «end» := 16#usize }
  let s16 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s14 s15
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) sk_buf2
  let _ ←
    Array.Insts.ZeroizeZeroize.zeroize (zeroize.Zeroize.Blanket
      U8.Insts.ZeroizeDefaultIsZeroes) pk_buf2
  let pk_seed1 := index_mut_back4 s16
  ok (sk_seed, pk_seed1)

end pqsigner_domain
