//! Executed Rust evidence for the WOTS digest/digit version bridges.
#![cfg(feature = "sim-internals")]
use sha2::{Digest, Sha256};
use sphincs_c10::sim_internals::{extract_digits, wots_digest};

fn lean_array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn checked_digits(d: &[u8; 32]) -> [u8; 43] {
    let got = extract_digits(d);
    let expected = std::array::from_fn(|i| {
        (0..3)
            .map(|j| ((d[31 - (3 * i + j) / 8] >> ((3 * i + j) % 8)) & 1) << j)
            .sum()
    });
    assert_eq!(got, expected);
    got
}

#[test]
fn gen_wots_bridge_vectors() {
    let pattern: [[u8; 32]; 3] =
        std::array::from_fn(|i| std::array::from_fn(|j| (32 * i + j) as u8));
    let counts = [
        0,
        1,
        255,
        256,
        65535,
        65536,
        0x00ff_ffff,
        0x0100_0000,
        9_999_999,
        10_000_000,
        0x8000_0000,
        u32::MAX,
    ];
    let mut inputs: Vec<_> = counts.into_iter().map(|c| (pattern, c)).collect();
    for i in 0..32 {
        inputs.push((pattern, 1u32 << i));
    }
    for i in 0..96 {
        let mut words = [[0u8; 32]; 3];
        words[i / 32][i % 32] = 0x81;
        inputs.push((words, 0x0102_0304));
    }
    assert_eq!(inputs.len(), 140);
    let mut out = String::from(
        "-- Generated by sphincs-c10/tests/gen_wots_bridge_vectors.rs.\nnamespace WotsBridgeDiff\n",
    );
    let mut blocks = Vec::new();
    for (n, block) in inputs.chunks(8).enumerate() {
        blocks.push(format!("hashBlock{n}"));
        out.push_str(&format!(
            "private def hashBlock{n} : List (Array (Array UInt8) × Nat × Array UInt8) := [\n"
        ));
        for (words, count) in block {
            let got = wots_digest(&words[0], &words[1], &words[2], *count);
            let mut preimage = words.concat();
            preimage.extend_from_slice(&[0u8; 28]);
            preimage.extend_from_slice(&count.to_be_bytes());
            assert_eq!(got.as_slice(), Sha256::digest(&preimage).as_slice());
            out.push_str(&format!(
                "  (#[{}], {count}, {}),\n",
                words
                    .iter()
                    .map(|w| lean_array(w))
                    .collect::<Vec<_>>()
                    .join(", "),
                lean_array(&got)
            ));
        }
        out.push_str("]\n");
    }
    out.push_str(&format!(
        "def hashVectors : List (Array (Array UInt8) × Nat × Array UInt8) :=\n  {}\n",
        blocks.join(" ++ ")
    ));
    let mut digests = vec![
        [0u8; 32],
        [255u8; 32],
        std::array::from_fn(|i| i as u8),
        std::array::from_fn(|i| (255 - i) as u8),
    ];
    for i in 0..256 {
        let mut d = [0u8; 32];
        d[31 - i / 8] = 1 << (i % 8);
        digests.push(d);
    }
    // 29 digits of 7, then 2: sum 205. Adjacent rejection sums to 204.
    let mut accepted = [0u8; 32];
    for i in 0..29 {
        for j in 0..3 {
            let b = 3 * i + j;
            accepted[31 - b / 8] |= 1 << (b % 8);
        }
    }
    let b = 3 * 29 + 1;
    accepted[31 - b / 8] |= 1 << (b % 8);
    assert_eq!(
        checked_digits(&accepted)
            .iter()
            .map(|x| *x as usize)
            .sum::<usize>(),
        205
    );
    digests.push(accepted);
    accepted[31] ^= 1;
    assert_eq!(
        checked_digits(&accepted)
            .iter()
            .map(|x| *x as usize)
            .sum::<usize>(),
        204
    );
    digests.push(accepted);
    assert_eq!(digests.len(), 262);
    blocks.clear();
    for (n, block) in digests.chunks(8).enumerate() {
        blocks.push(format!("digitBlock{n}"));
        out.push_str(&format!(
            "private def digitBlock{n} : List (Array UInt8 × Array Nat) := [\n"
        ));
        for d in block {
            out.push_str(&format!(
                "  ({}, {}),\n",
                lean_array(d),
                lean_array(&checked_digits(d))
            ));
        }
        out.push_str("]\n");
    }
    out.push_str(&format!(
        "def digitVectors : List (Array UInt8 × Array Nat) :=\n  {}\nend WotsBridgeDiff\n",
        blocks.join(" ++ ")
    ));
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/WotsBridgeDiffVectors.lean");
    if std::env::var_os("PQ_WOTS_BRIDGE_CHECK").is_some() {
        assert_eq!(
            std::fs::read_to_string(dest).unwrap(),
            out,
            "executed WOTS outputs differ from the committed corpus"
        );
    } else {
        std::fs::write(dest, out).unwrap();
    }
    println!("gen_wots_bridge_vectors: 140 full-counter hash cases and 262 digit cases");
}
