//! Execute the actual private recovery source without widening the public API.
//! All internal modules below are the production files, not copied algorithms.
//! The separately written reference assembles preimages and walks chains itself.
#![allow(dead_code)]
#![cfg(not(feature = "hw-sha256"))]
#[path = "../src/address.rs"]
mod address;
#[path = "../src/fors.rs"]
mod fors;
#[path = "../src/hash.rs"]
mod hash;
#[path = "../src/hypertree.rs"]
mod hypertree;
#[path = "../src/merkle.rs"]
mod merkle;
#[path = "../src/wots.rs"]
mod wots;
use sha2::{Digest, Sha256};
use sphincs_c10::{params, shuffle};

fn array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn ref_adrs(layer: u32, tree: u64, kind: u32, kp: u32, chain: u32, pos: u32) -> [u8; 32] {
    let mut out = [0u8; 32];
    out[..4].copy_from_slice(&layer.to_be_bytes());
    out[4..12].copy_from_slice(&tree.to_be_bytes());
    out[12..16].copy_from_slice(&kind.to_be_bytes());
    out[16..20].copy_from_slice(&kp.to_be_bytes());
    out[20..24].copy_from_slice(&chain.to_be_bytes());
    out[24..28].copy_from_slice(&pos.to_be_bytes());
    out
}

fn ref_digits(
    seed: &[u8; 32],
    layer: u32,
    tree: u64,
    kp: u32,
    msg: &[u8; 16],
    count: u32,
) -> [u8; 43] {
    let mut preimage = seed.to_vec();
    preimage.extend_from_slice(&ref_adrs(layer, tree, 0, kp, 0, 0));
    preimage.extend_from_slice(msg);
    preimage.extend_from_slice(&[0; 44]); // node padding and counter high bytes
    preimage.extend_from_slice(&count.to_be_bytes());
    let digest = Sha256::digest(&preimage);
    std::array::from_fn(|i| {
        (0..3)
            .map(|b| ((digest[31 - (3 * i + b) / 8] >> ((3 * i + b) % 8)) & 1) << b)
            .sum()
    })
}

fn ref_chain(
    seed: &[u8; 32],
    adrs: &[u8; 32],
    node: &[u8; 16],
    start: u32,
    steps: u32,
) -> [u8; 16] {
    let mut current = *node;
    for position in start..start.checked_add(steps).unwrap() {
        let mut a = *adrs;
        a[24..28].copy_from_slice(&position.to_be_bytes());
        let mut preimage = seed.to_vec();
        preimage.extend_from_slice(&a);
        preimage.extend_from_slice(&current);
        preimage.extend_from_slice(&[0; 16]);
        current.copy_from_slice(&Sha256::digest(&preimage)[..16]);
    }
    current
}

fn ref_compress(seed: &[u8; 32], adrs: &[u8; 32], nodes: &[[u8; 16]]) -> [u8; 16] {
    let mut preimage = seed.to_vec();
    preimage.extend_from_slice(adrs);
    for node in nodes {
        preimage.extend_from_slice(node);
        preimage.extend_from_slice(&[0; 16]);
    }
    Sha256::digest(&preimage)[..16].try_into().unwrap()
}

#[test]
fn gen_wots_recovery_vectors() {
    let seed = std::array::from_fn(|i| (i as u8).wrapping_mul(7).wrapping_add(3));
    let nodes: [[u8; 16]; 43] =
        std::array::from_fn(|i| std::array::from_fn(|j| (i * 19 + j * 37 + 5) as u8));
    let counts = [
        0,
        1,
        255,
        256,
        65535,
        65536,
        9_999_999,
        10_000_000,
        0x8000_0000,
        u32::MAX,
    ];
    let mut out = String::from("-- Generated by sphincs-c10/tests/gen_wots_recovery_vectors.rs.\nnamespace WotsRecoveryDiff\n");
    out.push_str(&format!("def seed : Array UInt8 := {}\n", array(&seed)));
    out.push_str(&format!(
        "def nodes : Array (Array UInt8) := #[{}]\n",
        nodes
            .iter()
            .map(|n| array(n))
            .collect::<Vec<_>>()
            .join(",\n  ")
    ));
    out.push_str("def recoveryVectors : List (Nat × Nat × Nat × Array UInt8 × Nat × Bool × Array UInt8) := [\n");
    for (i, count) in counts.into_iter().enumerate() {
        let layer = [0, 1, 0x8000_0000, u32::MAX][i % 4];
        let tree = [0, 511, 0x0102_0304_0506_0708, u64::MAX][i % 4];
        let kp = [0, 511, 0x8000_0000, u32::MAX][i % 4];
        let mut message = [0u8; 16];
        let mut found = false;
        // Search a fixture message while retaining the exact counter under test.
        for nonce in 0..2_000_000u32 {
            message[8..12].copy_from_slice(&(i as u32).to_be_bytes());
            message[12..].copy_from_slice(&nonce.to_be_bytes());
            if ref_digits(&seed, layer, tree, kp, &message, count)
                .iter()
                .map(|d| *d as usize)
                .sum::<usize>()
                == 205
            {
                found = true;
                break;
            }
        }
        assert!(found, "fixture search exhausted");
        for accepted in [true, false] {
            if !accepted {
                loop {
                    message[0] = message[0].checked_add(1).unwrap();
                    if ref_digits(&seed, layer, tree, kp, &message, count)
                        .iter()
                        .map(|d| *d as usize)
                        .sum::<usize>()
                        != 205
                    {
                        break;
                    }
                }
            }
            let digits = ref_digits(&seed, layer, tree, kp, &message, count);
            let expected = if accepted {
                let endpoints: [[u8; 16]; 43] = std::array::from_fn(|j| {
                    ref_chain(
                        &seed,
                        &ref_adrs(layer, tree, 0, kp, j as u32, 0),
                        &nodes[j],
                        u32::from(digits[j]),
                        7 - u32::from(digits[j]),
                    )
                });
                ref_compress(&seed, &ref_adrs(layer, tree, 1, kp, 0, 0), &endpoints)
            } else {
                [0u8; 16]
            };
            assert_eq!(
                wots::pk_from_sig(&seed, layer, tree, kp, &message, &nodes, count),
                expected
            );
            out.push_str(&format!(
                "  ({layer}, {tree}, {kp}, {}, {count}, {accepted}, {}),\n",
                array(&message),
                array(&expected)
            ));
        }
    }
    out.push_str("]\ndef chainVectors : List (Nat × Nat × Array UInt8) := [\n");
    let adrs = ref_adrs(u32::MAX, u64::MAX, 0, 511, 42, 19);
    let mut walks = Vec::new();
    for start in 0..8 {
        for steps in 0..=7 - start {
            walks.push((start, steps));
        }
    }
    walks.extend([(255, 2), (65535, 2), (u32::MAX - 1, 1), (u32::MAX, 0)]);
    assert_eq!(walks.len(), 40);
    for (start, steps) in walks {
        let expected = ref_chain(&seed, &adrs, &nodes[42], start, steps);
        assert_eq!(
            hash::chain_hash(&seed, &adrs, &nodes[42], start, steps),
            expected
        );
        out.push_str(&format!("  ({start}, {steps}, {}),\n", array(&expected)));
    }
    out.push_str(&format!(
        "]\ndef chainAdrs : Array UInt8 := {}\n",
        array(&adrs)
    ));
    out.push_str("def compressionVectors : List (Nat × Array UInt8) := [\n");
    for n in [0, 1, 13, 43] {
        let expected = ref_compress(&seed, &adrs, &nodes[..n]);
        assert_eq!(hash::th_multi(&seed, &adrs, &nodes[..n]), expected);
        out.push_str(&format!("  ({n}, {}),\n", array(&expected)));
    }
    out.push_str("]\nend WotsRecoveryDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/WotsRecoveryDiffVectors.lean");
    if std::env::var_os("PQ_WOTS_RECOVERY_CHECK").is_some() {
        assert_eq!(
            std::fs::read_to_string(dest).unwrap(),
            out,
            "recovery corpus drift"
        );
    } else {
        std::fs::write(dest, out).unwrap();
    }
    println!("gen_wots_recovery_vectors: 20 recovery, 40 chain, 4 compression cases");
}
