//! Actual FORS authentication paths versus independent recursive byte assembly.
#![cfg(feature = "sim-internals")]
use sha2::{Digest, Sha256};
use sphincs_c10::sim_internals::{compute_fors_root, sign_fors_tree};

fn digest16(input: &[u8]) -> [u8; 16] {
    Sha256::digest(input)[..16].try_into().unwrap()
}
fn secret(sk: &[u8; 32], ht: u32, tree: u32, leaf: u32) -> [u8; 16] {
    let mut input = sk.to_vec();
    input.extend_from_slice(b"fors");
    input.extend_from_slice(&ht.to_be_bytes());
    input.extend_from_slice(&tree.to_be_bytes());
    input.extend_from_slice(&leaf.to_be_bytes());
    digest16(&input)
}
fn node(seed: &[u8; 32], sk: &[u8; 32], ht: u32, tree: u32, height: u32, index: u32) -> [u8; 16] {
    let mut input = seed.to_vec();
    input.extend_from_slice(&0u32.to_be_bytes());
    input.extend_from_slice(&u64::from(ht).to_be_bytes());
    input.extend_from_slice(&3u32.to_be_bytes());
    input.extend_from_slice(&tree.to_be_bytes());
    input.extend_from_slice(&0u32.to_be_bytes());
    input.extend_from_slice(&height.to_be_bytes());
    input.extend_from_slice(&index.to_be_bytes());
    if height == 0 {
        input.extend_from_slice(&secret(sk, ht, tree, index));
        input.extend_from_slice(&[0; 16]);
    } else {
        input.extend_from_slice(&node(seed, sk, ht, tree, height - 1, 2 * index));
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&node(seed, sk, ht, tree, height - 1, 2 * index + 1));
        input.extend_from_slice(&[0; 16]);
    }
    digest16(&input)
}
fn lean_array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn auth(seed: &[u8; 32], sk: &[u8; 32], ht: u32, tree: u32, leaf: u32) -> [[u8; 16]; 11] {
    std::array::from_fn(|h| node(seed, sk, ht, tree, h as u32, (leaf >> h) ^ 1))
}
fn lean_path(xs: &[[u8; 16]; 11]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(|x| lean_array(x))
            .collect::<Vec<_>>()
            .join(", ")
    )
}
#[test]
fn gen_fors_auth_vectors() {
    let seed = std::array::from_fn(|i| (i * 11 + 7) as u8);
    let sk = std::array::from_fn(|i| (i * 7 + 3) as u8);
    let mut cases = vec![
        ([0; 32], [0; 32], 0, 0, 0),
        ([255; 32], [255; 32], u32::MAX, u32::MAX, 2047),
    ];
    for leaf in [0, 1, 2, 3, 511, 512, 1023, 1024, 1535, 1536, 2046, 2047] {
        cases.push((seed, sk, 0x8102_0304, 11, leaf));
    }
    for (ht, tree) in [
        (1, 1),
        (1 << 17, 12),
        (1 << 18, 13),
        (1 << 31, 1 << 31),
        (u32::MAX, u32::MAX),
    ] {
        cases.push((seed, sk, ht, tree, 0x555));
    }
    for i in [0, 15, 16, 31] {
        let mut s = seed;
        s[i] ^= 0x81;
        let mut k = sk;
        k[i] ^= 0x81;
        cases.push((s, k, 0x8102_0304, 11, 0x2aa));
    }
    assert_eq!(cases.len(), 23);
    let mut out=String::from("-- Generated by gen_fors_auth_vectors; actual Rust traversal versus independent recursive byte oracle.\nnamespace ForsAuthDiff\nstructure Vector where\n  seed : Array UInt8\n  sk : Array UInt8\n  ht : Nat\n  tree : Nat\n  leaf : Nat\n  secret : Array UInt8\n  path : Array (Array UInt8)\n  deriving Inhabited\ndef vectors : List Vector := [\n");
    for (seed, sk, ht, tree, leaf) in cases {
        let actual = sign_fors_tree(&seed, &sk, ht, tree, leaf);
        assert_eq!(actual.0, secret(&sk, ht, tree, leaf));
        assert_eq!(actual.1, auth(&seed, &sk, ht, tree, leaf));
        out.push_str(&format!("{{ seed := {}, sk := {}, ht := {ht}, tree := {tree}, leaf := {leaf}, secret := {}, path := {} }},\n",lean_array(&seed),lean_array(&sk),lean_array(&actual.0),lean_path(&actual.1)));
    }
    out.push_str("]\nend ForsAuthDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/ForsAuthDiffVectors.lean");
    if std::env::var("PQ_FORS_AUTH_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!("OK: 23 actual secrets and eleven-sibling paths versus independent recursive oracle");
}
#[test]
fn every_leaf_has_all_eleven_expected_siblings() {
    let seed = std::array::from_fn(|i| (i * 17 + 13) as u8);
    let sk = std::array::from_fn(|i| (i * 13 + 19) as u8);
    let (ht, tree) = (0x8102_0304, 11);
    // Compute the independent complete recursive tree once. Production uses a
    // height stack; this test oracle indexes each subtree directly.
    let levels: Vec<Vec<[u8; 16]>> = (0..11)
        .map(|h| {
            (0..(2048 >> h))
                .map(|i| node(&seed, &sk, ht, tree, h, i))
                .collect()
        })
        .collect();
    assert_eq!(
        compute_fors_root(&seed, &sk, ht, tree),
        node(&seed, &sk, ht, tree, 11, 0)
    );
    for leaf in 0..2048 {
        let (s, p) = sign_fors_tree(&seed, &sk, ht, tree, leaf);
        assert_eq!(s, secret(&sk, ht, tree, leaf));
        for h in 0..11 {
            assert_eq!(
                p[h],
                levels[h][((leaf >> h) ^ 1) as usize],
                "leaf={leaf}, level={h}"
            );
            assert_ne!(
                p[h],
                levels[h][(leaf >> h) as usize],
                "own node incorrectly accepted as sibling"
            );
        }
    }
    println!("OK: all 2048 leaves / 22528 siblings and secrets; own-node controls discriminate");
}
