//! Actual stack tree construction versus recursive independent byte assembly.
#![cfg(feature = "sim-internals")]
use sha2::{Digest, Sha256};
use sphincs_c10::sim_internals::compute_fors_root;
use sphincs_c10::SigningKey;

fn digest16(input: &[u8]) -> [u8; 16] {
    Sha256::digest(input)[..16].try_into().unwrap()
}
fn secret(sk: &[u8; 32], ht: u32, tree: u32, leaf: u32) -> [u8; 16] {
    let mut input = sk.to_vec();
    input.extend_from_slice(b"fors");
    input.extend_from_slice(&ht.to_be_bytes());
    input.extend_from_slice(&tree.to_be_bytes());
    input.extend_from_slice(&leaf.to_be_bytes());
    digest16(&input)
}
fn node(seed: &[u8; 32], sk: &[u8; 32], ht: u32, tree: u32, height: u32, index: u32) -> [u8; 16] {
    let mut input = seed.to_vec();
    input.extend_from_slice(&0u32.to_be_bytes());
    input.extend_from_slice(&u64::from(ht).to_be_bytes());
    input.extend_from_slice(&3u32.to_be_bytes());
    input.extend_from_slice(&tree.to_be_bytes());
    input.extend_from_slice(&0u32.to_be_bytes());
    input.extend_from_slice(&height.to_be_bytes());
    input.extend_from_slice(&index.to_be_bytes());
    if height == 0 {
        input.extend_from_slice(&secret(sk, ht, tree, index));
        input.extend_from_slice(&[0; 16]);
    } else {
        input.extend_from_slice(&node(seed, sk, ht, tree, height - 1, 2 * index));
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&node(seed, sk, ht, tree, height - 1, 2 * index + 1));
        input.extend_from_slice(&[0; 16]);
    }
    digest16(&input)
}
fn lean_array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}
#[test]
fn gen_fors_root_vectors() {
    let seed = std::array::from_fn(|i| (i * 11 + 7) as u8);
    let sk = std::array::from_fn(|i| (i * 7 + 3) as u8);
    let mut cases = vec![
        ([0; 32], [0; 32], 0, 0),
        ([255; 32], [255; 32], u32::MAX, u32::MAX),
        (seed, sk, 0x8102_0304, 12),
    ];
    for ht in [1, 1 << 17, 1 << 18, 1 << 31, u32::MAX] {
        cases.push((seed, sk, ht, 12));
    }
    for tree in [1, 12, 13, 1 << 31, u32::MAX] {
        cases.push((seed, sk, 0x8102_0304, tree));
    }
    for i in [0, 15, 16, 31] {
        let mut s = seed;
        s[i] ^= 0x81;
        cases.push((s, sk, 0x8102_0304, 12));
        let mut k = sk;
        k[i] ^= 0x81;
        cases.push((seed, k, 0x8102_0304, 12));
    }
    assert_eq!(cases.len(), 21);
    let mut out = String::from("-- Generated by gen_fors_root_vectors; actual Rust stack algorithm and independent recursive byte oracle.\nnamespace ForsRootDiff\nstructure Vector where\n  seed : Array UInt8\n  sk : Array UInt8\n  ht : Nat\n  tree : Nat\n  result : Array UInt8\n  deriving Inhabited\ndef vectors : List Vector := [\n");
    for (seed, sk, ht, tree) in cases {
        let actual = compute_fors_root(&seed, &sk, ht, tree);
        let expected = node(&seed, &sk, ht, tree, 11, 0);
        assert_eq!(actual, expected);
        // This is the old reference final-slot rule (#823), not a root.
        assert_ne!(actual, secret(&sk, ht, tree, 0));
        out.push_str(&format!(
            "{{ seed := {}, sk := {}, ht := {ht}, tree := {tree}, result := {} }},\n",
            lean_array(&seed),
            lean_array(&sk),
            lean_array(&actual)
        ));
    }
    out.push_str("]\nend ForsRootDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/ForsRootDiffVectors.lean");
    if std::env::var("PQ_FORS_ROOT_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!(
        "OK: 21 actual roots versus recursive byte oracle; all differ from old leaf-secret rule"
    );
}
#[test]
fn actual_signer_final_slot_carries_full_root() {
    let sk = [0x51; 32];
    let pk = [0x73; 16];
    let key = SigningKey::keygen(sk, pk);
    for msg in [[0x21; 32], [0x93; 32]] {
        let sig = key.sign(&msg, None);
        let mut seed = [0u8; 32];
        seed[..16].copy_from_slice(&pk);
        let mut input = seed.to_vec();
        input.extend_from_slice(key.pk_root());
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&sig[..16]);
        input.extend_from_slice(&[0; 16]);
        input.extend_from_slice(&msg);
        input.extend_from_slice(&[255; 32]);
        let digest = Sha256::digest(input);
        let bits = |start: usize, count: usize| -> u32 {
            (0..count)
                .map(|i| u32::from((digest[31 - (start + i) / 8] >> ((start + i) % 8)) & 1) << i)
                .sum()
        };
        assert_eq!(bits(132, 11), 0);
        let ht = bits(143, 18);
        let expected = node(&seed, &sk, ht, 12, 11, 0);
        assert_eq!(&sig[16 + 12 * 16..16 + 13 * 16], expected.as_slice());
        assert_ne!(expected, secret(&sk, ht, 12, 0));
        assert!(sphincs_c10::verify(
            key.pk_seed(),
            key.pk_root(),
            &msg,
            &sig
        ));
    }
}
