//! Actual FORS secret derivation versus a byte oracle. Hardware-feature builds
//! use host hooks to inspect the adapter transcript; no peripheral is exercised.
#![cfg(feature = "sim-internals")]
use sha2::{Digest, Sha256};
use sphincs_c10::sim_internals::fors_secret;

#[cfg(feature = "hw-sha256")]
mod backend {
    use super::*;
    use std::cell::RefCell;
    thread_local! {
        static INPUTS: RefCell<Vec<Vec<u8>>> = const { RefCell::new(Vec::new()) };
    }
    #[no_mangle]
    extern "C" fn pqsigner_sha256_init() {
        INPUTS.with(|s| s.borrow_mut().clear());
    }
    #[no_mangle]
    unsafe extern "C" fn pqsigner_sha256_update(ptr: *const u8, len: usize) {
        // SAFETY: the actual adapter supplies a readable input slice.
        let input = unsafe { std::slice::from_raw_parts(ptr, len) };
        INPUTS.with(|s| s.borrow_mut().push(input.to_vec()));
    }
    #[no_mangle]
    unsafe extern "C" fn pqsigner_sha256_final(out: *mut u8) {
        let input = INPUTS.with(|s| s.borrow().concat());
        let digest = Sha256::digest(input);
        // SAFETY: the actual adapter supplies a writable 32-byte output.
        unsafe { std::ptr::copy_nonoverlapping(digest.as_ptr(), out, 32) };
    }
    pub fn check(expected: &[u8]) {
        INPUTS.with(|s| {
            let s = s.borrow();
            assert_eq!(s.iter().map(Vec::len).collect::<Vec<_>>(), [32, 4, 4, 4, 4]);
            assert_eq!(s.concat(), expected);
        });
    }
}

fn lean_array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

#[test]
fn gen_fors_secret_vectors() {
    let pattern = std::array::from_fn(|i| (i * 7 + 3) as u8);
    let mut cases = vec![
        ([0; 32], 0u32, 0u32, 0u32),
        ([255; 32], u32::MAX, u32::MAX, u32::MAX),
        (pattern, 0x8102_0304, 0xfeab_cd00, 0x8102_03ff),
    ];
    for i in 0..32 {
        let mut seed = [0; 32];
        seed[i] = 0x81;
        cases.push((seed, 0, 0, 0));
    }
    for bit in 0..32 {
        cases.push((pattern, 1 << bit, 0, 0));
        cases.push((pattern, 0, 1 << bit, 0));
        cases.push((pattern, 0, 0, 1 << bit));
    }
    assert_eq!(cases.len(), 131);
    let mut out = String::from("-- Generated by gen_fors_secret_vectors from actual Rust and independent byte assembly.\nnamespace ForsSecretDiff\nstructure Vector where\n  sk : Array UInt8\n  ht : Nat\n  tree : Nat\n  leaf : Nat\n  result : Array UInt8\n  deriving Inhabited\ndef vectors : List Vector := [\n");
    for (sk, ht, tree, leaf) in cases {
        let mut input = sk.to_vec();
        input.extend_from_slice(b"fors");
        input.extend_from_slice(&ht.to_be_bytes());
        input.extend_from_slice(&tree.to_be_bytes());
        input.extend_from_slice(&leaf.to_be_bytes());
        assert_eq!(input.len(), 48);
        let actual = fors_secret(&sk, ht, tree, leaf);
        assert_eq!(actual.as_slice(), &Sha256::digest(&input)[..16]);
        #[cfg(feature = "hw-sha256")]
        backend::check(&input);
        out.push_str(&format!(
            "{{ sk := {}, ht := {ht}, tree := {tree}, leaf := {leaf}, result := {} }},\n",
            lean_array(&sk),
            lean_array(&actual)
        ));
    }
    out.push_str("]\nend ForsSecretDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/ForsSecretDiffVectors.lean");
    if std::env::var("PQ_FORS_SECRET_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(std::fs::read_to_string(dest).unwrap(), out);
    }
    println!("OK: 131 actual FORS-secret calls: all seed bytes and full-width hypertree/tree/leaf fields; independent 48-byte preimage and 16-byte digest");
}
