//! Executed H_msg outputs for the extracted/spec correspondence replay.
#![cfg(feature = "sim-internals")]
use sha2::{Digest, Sha256};
use sphincs_c10::sim_internals::h_msg;

fn lean_array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

// Exercise the actual hw-sha256 adapter on the host. These hooks check the
// sequence and byte contents; they do not simulate the STM32 HASH peripheral.
#[cfg(feature = "hw-sha256")]
mod hooks {
    use std::cell::RefCell;
    thread_local! { static PARTS: RefCell<Vec<Vec<u8>>> = const { RefCell::new(Vec::new()) }; }
    #[no_mangle]
    extern "C" fn pqsigner_sha256_init() {
        PARTS.with(|p| p.borrow_mut().clear());
    }
    #[no_mangle]
    unsafe extern "C" fn pqsigner_sha256_update(ptr: *const u8, len: usize) {
        // SAFETY: the crate's update adapter supplies a readable slice.
        let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
        PARTS.with(|p| p.borrow_mut().push(bytes.to_vec()));
    }
    #[no_mangle]
    unsafe extern "C" fn pqsigner_sha256_final(out: *mut u8) {
        use sha2::{Digest, Sha256};
        let digest = PARTS.with(|p| Sha256::digest(p.borrow().concat()));
        // SAFETY: the adapter provides a writable 32-byte result buffer.
        unsafe {
            std::ptr::copy_nonoverlapping(digest.as_ptr(), out, 32);
        }
    }
    pub fn assert_parts(expected: &[[u8; 32]; 4]) {
        PARTS.with(|p| {
            let p = p.borrow();
            assert_eq!(p.len(), 5);
            for i in 0..4 {
                assert_eq!(p[i], expected[i]);
            }
            assert_eq!(p[4], [255u8; 32]);
        });
    }
}

#[test]
fn gen_hmsg_vectors() {
    let mut inputs = vec![[[0u8; 32]; 4], [[255u8; 32]; 4]];
    inputs.push(std::array::from_fn(|i| {
        std::array::from_fn(|j| (32 * i + j) as u8)
    }));
    inputs.push(std::array::from_fn(|i| {
        std::array::from_fn(|j| (255 - 32 * i - j) as u8)
    }));
    // Distinguish every position in every input, including byte 31.
    for i in 0..128 {
        let mut words = [[0u8; 32]; 4];
        words[i / 32][i % 32] = 0x81;
        inputs.push(words);
    }
    assert_eq!(inputs.len(), 132);
    let mut out = String::from(
        "-- Generated by sphincs-c10/tests/gen_hmsg_vectors.rs.\nnamespace HMsgDiff\n",
    );
    let mut blocks = Vec::new();
    for (n, block) in inputs.chunks(8).enumerate() {
        blocks.push(format!("block{n}"));
        out.push_str(&format!(
            "private def block{n} : List (Array (Array UInt8) × Array UInt8) := [\n"
        ));
        for words in block {
            let actual = h_msg(&words[0], &words[1], &words[2], &words[3]);
            let mut preimage = words.concat();
            preimage.extend_from_slice(&[255u8; 32]);
            assert_eq!(actual.as_slice(), Sha256::digest(&preimage).as_slice());
            #[cfg(feature = "hw-sha256")]
            hooks::assert_parts(words);
            out.push_str(&format!(
                "  (#[{}], {}),\n",
                words
                    .iter()
                    .map(|w| lean_array(w))
                    .collect::<Vec<_>>()
                    .join(", "),
                lean_array(&actual)
            ));
        }
        out.push_str("]\n");
    }
    out.push_str(&format!(
        "def vectors : List (Array (Array UInt8) × Array UInt8) :=\n  {}\nend HMsgDiff\n",
        blocks.join(" ++ ")
    ));
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/HMsgDiffVectors.lean");
    if std::env::var_os("PQ_HMSG_CHECK").is_some() {
        assert_eq!(
            std::fs::read_to_string(dest).unwrap(),
            out,
            "executed H_msg output differs from the committed corpus"
        );
    } else {
        std::fs::write(dest, out).unwrap();
    }
    println!(
        "gen_hmsg_vectors: {} Rust-executed H_msg vectors",
        inputs.len()
    );
}
