//! Rust-executed inputs for the Aeneas / verifier-spec digest decoder bridge.
//! Regenerate with `make -C contracts/verification verify-extract-differential GEN=1`.
#![cfg(feature = "sim-internals")]

use sphincs_c10::sim_internals::{extract_fors_indices, extract_ht_index};

fn lean_array<T: std::fmt::Display>(xs: &[T]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

#[test]
fn gen_fors_extract_vectors() {
    let mut digests = vec![[0u8; 32], [255u8; 32], [0xaa; 32], [0x55; 32]];
    digests.push(std::array::from_fn(|i| i as u8));
    digests.push(std::array::from_fn(|i| (31 - i) as u8));
    // Every wire bit, including bits outside both decoded fields.
    for byte in 0..32 {
        for bit in 0..8 {
            let mut d = [0u8; 32];
            d[byte] = 1 << bit;
            digests.push(d);
        }
    }
    assert_eq!(digests.len(), 262);
    let mut out = String::from(
        "-- Generated by sphincs-c10/tests/gen_fors_extract_vectors.rs.\n\
         -- Expected outputs come from executing the shipped Rust decoders.\n\
         namespace ForsExtractDiff\n",
    );
    // Small declarations keep Lean elaboration below its recursion limit.
    let mut blocks = Vec::new();
    for (n, block) in digests.chunks(16).enumerate() {
        let name = format!("block{n}");
        blocks.push(name.clone());
        out.push_str(&format!(
            "private def {name} : List (Array UInt8 × Nat × Array Nat) := [\n"
        ));
        for d in block {
            out.push_str(&format!(
                "  ({}, {}, {}),\n",
                lean_array(d),
                extract_ht_index(d),
                lean_array(&extract_fors_indices(d)),
            ));
        }
        out.push_str("]\n");
    }
    out.push_str(&format!(
        "def vectors : List (Array UInt8 × Nat × Array Nat) :=\n  {}\n",
        blocks.join(" ++ ")
    ));
    out.push_str("end ForsExtractDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/ForsExtractDiffVectors.lean");
    std::fs::write(dest, out).unwrap();
    println!(
        "gen_fors_extract_vectors: {} Rust-executed vectors",
        digests.len()
    );
}
