//! Execute production Merkle recovery and pair hashes against an independent
//! preimage reference. Ordinary tests compare; fixture writes require opt-in.
#![allow(dead_code)]
#![cfg(not(feature = "hw-sha256"))]
#[path = "../src/address.rs"]
mod address;
#[path = "../src/fors.rs"]
mod fors;
#[path = "../src/hash.rs"]
mod hash;
#[path = "../src/hypertree.rs"]
mod hypertree;
#[path = "../src/merkle.rs"]
mod merkle;
#[path = "../src/wots.rs"]
mod wots;
use sha2::{Digest, Sha256};
use sphincs_c10::{params, shuffle};

fn array(xs: &[u8]) -> String {
    format!(
        "#[{}]",
        xs.iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn reference_adrs(layer: u32, tree: u64, height: u32, parent: u32) -> [u8; 32] {
    let mut out = [0u8; 32];
    out[0..4].copy_from_slice(&layer.to_be_bytes());
    out[4..12].copy_from_slice(&tree.to_be_bytes());
    out[12..16].copy_from_slice(&2u32.to_be_bytes());
    out[24..28].copy_from_slice(&height.to_be_bytes());
    out[28..32].copy_from_slice(&parent.to_be_bytes());
    out
}

fn reference_pair(seed: &[u8; 32], adrs: &[u8; 32], left: &[u8; 32], right: &[u8; 32]) -> [u8; 16] {
    let mut bytes = Vec::new();
    bytes.extend_from_slice(seed);
    bytes.extend_from_slice(adrs);
    bytes.extend_from_slice(left);
    bytes.extend_from_slice(right);
    Sha256::digest(bytes)[..16].try_into().unwrap()
}

fn reference_recover(
    seed: &[u8; 32],
    layer: u32,
    tree: u64,
    leaf: &[u8; 16],
    idx: u32,
    auth: &[[u8; 16]; 9],
) -> [u8; 16] {
    let mut node = *leaf;
    for (h, sibling) in auth.iter().enumerate() {
        // Re-derive each index from the original leaf, independently of Rust's
        // mutable idx walk. Node and sibling are separately zero-padded.
        let current_idx = idx / (1u32 << h);
        let adrs = reference_adrs(layer, tree, h as u32 + 1, idx / (1u32 << (h + 1)));
        let mut left = [0u8; 32];
        let mut right = [0u8; 32];
        if current_idx % 2 == 0 {
            left[..16].copy_from_slice(&node);
            right[..16].copy_from_slice(sibling);
        } else {
            left[..16].copy_from_slice(sibling);
            right[..16].copy_from_slice(&node);
        }
        node = reference_pair(seed, &adrs, &left, &right);
    }
    node
}

#[test]
fn gen_merkle_recovery_vectors() {
    let seed = std::array::from_fn(|i| (i * 17 + 3) as u8);
    let leaf = std::array::from_fn(|i| (i * 23 + 7) as u8);
    let auth: [[u8; 16]; 9] =
        std::array::from_fn(|i| std::array::from_fn(|j| (i * 53 + j * 31 + 11) as u8));
    let pair_adrs = reference_adrs(u32::MAX, u64::MAX, 9, u32::MAX);
    let mut out = String::from("-- Generated by sphincs-c10/tests/gen_merkle_recovery_vectors.rs.\nset_option maxRecDepth 16384\nnamespace MerkleRecoveryDiff\n");
    out.push_str(&format!("def seed : Array UInt8 := {}\n", array(&seed)));
    out.push_str(&format!("def leaf : Array UInt8 := {}\n", array(&leaf)));
    out.push_str(&format!(
        "def auth : Array (Array UInt8) := #[{}]\n",
        auth.iter()
            .map(|n| array(n))
            .collect::<Vec<_>>()
            .join(",\n  ")
    ));
    out.push_str(&format!(
        "def pairAdrs : Array UInt8 := {}\n",
        array(&pair_adrs)
    ));
    out.push_str("def pairVectors : List (Array UInt8 × Array UInt8 × Array UInt8) := [\n");
    for k in [0, 1, 2, 3, 254, 255] {
        let left = std::array::from_fn(|i| (i * 29 + k) as u8);
        let right = std::array::from_fn(|i| (i * 37 + k + 97) as u8);
        let expected = reference_pair(&seed, &pair_adrs, &left, &right);
        assert_eq!(hash::th_pair(&seed, &pair_adrs, &left, &right), expected);
        out.push_str(&format!(
            "  ({}, {}, {}),\n",
            array(&left),
            array(&right),
            array(&expected)
        ));
    }
    out.push_str("]\ndef recoveryVectors : Array (Nat × Nat × Nat × Array UInt8) := #[\n");
    let mut cases = (0..512)
        .map(|idx| (1, 0x0102_0304_0506_0708, idx))
        .collect::<Vec<_>>();
    for (layer, tree) in [(0, 0), (u32::MAX, u64::MAX)] {
        for idx in [
            512,
            513,
            65535,
            65536,
            0x7fff_ffff,
            0x8000_0000,
            u32::MAX - 1,
            u32::MAX,
        ] {
            cases.push((layer, tree, idx));
        }
    }
    assert_eq!(cases.len(), 528);
    for (layer, tree, idx) in cases {
        let expected = reference_recover(&seed, layer, tree, &leaf, idx, &auth);
        assert_eq!(
            merkle::verify_auth_path(&seed, layer, tree, &leaf, idx, &auth),
            expected
        );
        out.push_str(&format!(
            "  ({layer}, {tree}, {idx}, {}),\n",
            array(&expected)
        ));
    }
    out.push_str("]\nend MerkleRecoveryDiff\n");
    let dest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../contracts/verification/extracted/Extracted/MerkleRecoveryDiffVectors.lean");
    if std::env::var("PQ_MERKLE_RECOVERY_GENERATE").as_deref() == Ok("1") {
        std::fs::write(dest, out).unwrap();
    } else {
        assert_eq!(
            std::fs::read_to_string(dest).unwrap(),
            out,
            "Merkle recovery corpus drift"
        );
    }
    println!("gen_merkle_recovery_vectors: 528 recovery and 6 pair-hash cases");
}
