//! Build-time generator for the embedded ERC20 metadata DB and ZK
//! verification key DB consumed by the secure-world firmware.
//!
//! Reads:
//!   secure/data/erc20.json
//!   secure/data/vks.json
//!   secure/data/vks/<file>.bin
//!
//! Writes (checked into the repo, like the existing
//! tools/export_zk_constants.js outputs):
//!   secure/src/erc20/erc20_db.bin
//!   secure/src/zk/vk_db.bin
//!   secure/data/vks.review.txt
//!
//! Run manually after editing the JSON sources:
//!
//!   cargo run -p dbgen
//!
//! The runtime parser is in:
//!   secure/src/erc20/db.rs   (ERC20 metadata)
//!   secure/src/zk/vk_db.rs   (ZK clear-signing VKs)
//!
//! Both crates physically share the on-disk format definition via
//! sphincs_tz_shared::db_format, so any field-layout change here is a
//! single edit in shared/src/db_format.rs.

use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

mod erc20;
mod erc20_poseidon;
mod merkle;
#[path = "../../secure/src/zk/poseidon_constants.rs"]
mod poseidon_constants;
mod poseidon;
mod vks;

const REPO_ROOT_CARGO: &str = env!("CARGO_MANIFEST_DIR");

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is .../sphincs_rust/dbgen — go up one
    PathBuf::from(REPO_ROOT_CARGO).parent().unwrap().to_path_buf()
}

fn main() {
    let root = repo_root();
    println!("dbgen: workspace root = {}", root.display());

    // Source data lives under secure/data/ for historical reasons
    // (the curated JSON is the same regardless of which world hosts
    // the resulting blob).
    let erc20_json = root.join("secure/data/erc20.json");
    let vks_json = root.join("secure/data/vks.json");
    let vks_dir = root.join("secure/data/vks");

    // The full DB blobs ship in the NON-SECURE firmware image as
    // rodata. The secure firmware only embeds the Merkle root via
    // the generated `db_roots.rs` file below.
    let erc20_out = root.join("nonsecure/src/erc20_db.bin");
    let vk_out = root.join("nonsecure/src/vk_db.bin");
    let roots_out = root.join("secure/src/db_roots.rs");
    let review_out = root.join("secure/data/vks.review.txt");
    // The Poseidon-Merkle tree export is consumed by the off-device
    // witness generator that builds CowSwap EIP-712 v3 proofs. It's
    // committed into the repo so `make e2e-hw` remains deterministic
    // without requiring a live dbgen run.
    let poseidon_tree_out = root.join("circuits/generated/erc20_poseidon_tree.json");

    // ----- ERC20 metadata DB -----
    let erc20_res = erc20::build_db(&erc20_json).expect("erc20 db build failed");
    erc20::round_trip_check(&erc20_res.blob, &erc20_json, &erc20_res.root)
        .expect("erc20 round-trip failed");
    fs::write(&erc20_out, &erc20_res.blob).expect("write erc20_db.bin");
    println!(
        "dbgen: wrote {} ({} bytes, root = {})",
        erc20_out.display(),
        erc20_res.blob.len(),
        hex::encode(erc20_res.root),
    );
    // ERC20 Poseidon-Merkle companion artifact.
    if let Some(parent) = poseidon_tree_out.parent() {
        fs::create_dir_all(parent).expect("create circuits/generated");
    }
    fs::write(&poseidon_tree_out, &erc20_res.poseidon_tree_json)
        .expect("write erc20_poseidon_tree.json");
    println!(
        "dbgen: wrote {} (poseidon root = {})",
        poseidon_tree_out.display(),
        hex::encode(erc20_res.poseidon_root),
    );

    // ----- VK DB -----
    let vk_res = vks::build_db(&vks_json, &vks_dir).expect("vk db build failed");
    vks::round_trip_check(&vk_res.blob, &vks_json, &vks_dir, &vk_res.root)
        .expect("vk round-trip failed");
    fs::write(&vk_out, &vk_res.blob).expect("write vk_db.bin");
    fs::write(&review_out, &vk_res.review_text).expect("write vks.review.txt");
    println!(
        "dbgen: wrote {} ({} bytes, root = {})",
        vk_out.display(),
        vk_res.blob.len(),
        hex::encode(vk_res.root),
    );
    println!("dbgen: wrote {}", review_out.display());

    // ----- secure/src/db_roots.rs -----
    //
    // This is the only file the secure-world build sees from the DBs.
    // Three 32-byte Merkle roots are baked into the secure image: the
    // SHA-256 ERC-20 + VK roots (for the existing transfer display /
    // VK bundle verifier paths) and the Poseidon ERC-20 root (used as
    // the third public input for the CowSwap EIP-712 v3 Groth16 proof).
    let roots_rs = render_db_roots(&erc20_res.root, &vk_res.root, &erc20_res.poseidon_root);
    fs::write(&roots_out, &roots_rs).expect("write db_roots.rs");
    println!("dbgen: wrote {}", roots_out.display());

    println!("dbgen: ok");
}

fn render_db_roots(
    erc20_root: &[u8; 32],
    vk_root: &[u8; 32],
    erc20_poseidon_root: &[u8; 32],
) -> String {
    let mut s = String::new();
    s.push_str("//! Merkle roots of the embedded ERC20 + VK databases.\n");
    s.push_str("//!\n");
    s.push_str("//! Generated by `cargo run -p dbgen` from secure/data/erc20.json\n");
    s.push_str("//! and secure/data/vks.json. DO NOT EDIT BY HAND.\n");
    s.push_str("//!\n");
    s.push_str("//! The full DB blobs live in non-secure rodata. The secure world\n");
    s.push_str("//! only holds these roots; everything received from NS is\n");
    s.push_str("//! verified against them via `crate::erc20::merkle::verify_proof`.\n");
    s.push_str("//!\n");
    s.push_str("//! `ERC20_POSEIDON_ROOT` is the parallel BLS12-381 Poseidon-Merkle\n");
    s.push_str("//! tree over the same sorted (chain_id, contract) entry set that\n");
    s.push_str("//! the CowSwap EIP-712 v3 Groth16 circuit consumes as its third\n");
    s.push_str("//! public input. It's stored as the 32-byte little-endian canonical\n");
    s.push_str("//! encoding of the root scalar, ready to be fed into\n");
    s.push_str("//! `bls12_381::Scalar::from_bytes`.\n");
    s.push_str("\n");
    s.push_str("pub static ERC20_DB_ROOT: [u8; 32] = [");
    for (i, b) in erc20_root.iter().enumerate() {
        if i % 8 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("0x{:02x}, ", b));
    }
    s.push_str("\n];\n\n");
    s.push_str("pub static VK_DB_ROOT: [u8; 32] = [");
    for (i, b) in vk_root.iter().enumerate() {
        if i % 8 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("0x{:02x}, ", b));
    }
    s.push_str("\n];\n\n");
    s.push_str("pub static ERC20_POSEIDON_ROOT: [u8; 32] = [");
    for (i, b) in erc20_poseidon_root.iter().enumerate() {
        if i % 8 == 0 {
            s.push_str("\n    ");
        }
        s.push_str(&format!("0x{:02x}, ", b));
    }
    s.push_str("\n];\n");
    s
}

// === Helpers shared between erc20 and vks modules ============================

fn parse_hex_address(s: &str) -> Result<[u8; 20], String> {
    let s = s.strip_prefix("0x").unwrap_or(s);
    if s.len() != 40 {
        return Err(format!("address must be 40 hex chars, got {}", s.len()));
    }
    let bytes = hex::decode(s).map_err(|e| format!("hex decode: {e}"))?;
    let mut out = [0u8; 20];
    out.copy_from_slice(&bytes);
    Ok(out)
}

fn write_u32_le(buf: &mut Vec<u8>, v: u32) {
    buf.extend_from_slice(&v.to_le_bytes());
}

fn write_u64_le(buf: &mut Vec<u8>, v: u64) {
    buf.extend_from_slice(&v.to_le_bytes());
}

#[derive(Debug, Deserialize, Clone)]
pub struct Erc20Record {
    pub chain_id: u64,
    pub address: String,
    pub name: String,
    pub symbol: String,
    pub decimals: u8,
    #[serde(default)]
    pub flags: u8,
}

#[derive(Debug, Deserialize, Clone)]
pub struct VkProtocol {
    pub protocol: String,
    pub vk_file: String,
    pub deployments: Vec<VkDeployment>,
}

#[derive(Debug, Deserialize, Clone)]
pub struct VkDeployment {
    pub chain_id: u64,
    pub address: String,
    #[serde(default)]
    pub label: String,
}

pub fn load_erc20_records(path: &Path) -> Result<Vec<Erc20Record>, String> {
    let bytes = fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_slice(&bytes).map_err(|e| format!("parse {}: {e}", path.display()))
}

pub fn load_vk_protocols(path: &Path) -> Result<Vec<VkProtocol>, String> {
    let bytes = fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    serde_json::from_slice(&bytes).map_err(|e| format!("parse {}: {e}", path.display()))
}

pub fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(bytes);
    let result = h.finalize();
    let mut out = [0u8; 32];
    out.copy_from_slice(&result);
    out
}
