-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.PkFromSig.Types
import Extracted.PkFromSig.FunsExternal
import Extracted.Adrs
import Extracted.Wots.Funs
import Extracted.Merkle.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::TARGET_SUM]
    Source: 'sphincs-c10/src/params.rs', lines 52:0-52:34
    Visibility: public -/
@[global_simps, irreducible] def params.TARGET_SUM : Std.Usize := 205#usize

/-- [sphincs_c10::params::ADRS_WOTS]
    Source: 'sphincs-c10/src/params.rs', lines 97:0-97:29
    Visibility: public -/
@[global_simps, irreducible] def params.ADRS_WOTS : Std.U32 := 0#u32

/-- [sphincs_c10::params::ADRS_WOTS_PK]
    Source: 'sphincs-c10/src/params.rs', lines 98:0-98:32
    Visibility: public -/
@[global_simps, irreducible] def params.ADRS_WOTS_PK : Std.U32 := 1#u32

/-- [sphincs_c10::wots::pk_from_sig]: loop body 0:
    Source: 'sphincs-c10/src/wots.rs', lines 180:4-182:5
    Visibility: public -/
@[rust_loop_body]
def wots.pk_from_sig_loop0.body
  (digits : Array Std.U8 43#usize) (iter : core.ops.range.Range Std.Usize)
  (sum : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done sum)
  | some i =>
    let i1 ← Array.index_usize digits i
    let i2 ← lift (UScalar.cast .Usize i1)
    let sum1 ← sum + i2
    ok (cont (iter1, sum1))

/-- [sphincs_c10::wots::pk_from_sig]: loop 0:
    Source: 'sphincs-c10/src/wots.rs', lines 180:4-182:5
    Visibility: public -/
@[rust_loop]
def wots.pk_from_sig_loop0
  (iter : core.ops.range.Range Std.Usize) (digits : Array Std.U8 43#usize)
  (sum : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, sum1) => wots.pk_from_sig_loop0.body digits iter1 sum1)
    (iter, sum)

/-- [sphincs_c10::wots::pk_from_sig]: loop body 1:
    Source: 'sphincs-c10/src/wots.rs', lines 189:4-193:5
    Visibility: public -/
@[rust_loop_body]
def wots.pk_from_sig_loop1.body
  (seed : Array Std.U8 32#usize)
  (sigma : Array (Array Std.U8 16#usize) 43#usize)
  (digits : Array Std.U8 43#usize) (base_adrs : Array Std.U8 32#usize)
  (iter : core.ops.range.Range Std.Usize)
  (pk_elements : Array (Array Std.U8 16#usize) 43#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 43#usize)) (Array (Array Std.U8 16#usize) 43#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done pk_elements)
  | some i =>
    let i1 ← lift (UScalar.cast .U32 i)
    let chain_adrs ← address.set_chain_index base_adrs i1
    let i2 ← params.W - 1#usize
    let i3 ← lift (UScalar.cast .U32 i2)
    let i4 ← Array.index_usize digits i
    let i5 ← lift (UScalar.cast .U32 i4)
    let remaining ← i3 - i5
    let a ← Array.index_usize sigma i
    let i6 ← lift (UScalar.cast .U32 i4)
    let a1 ← hash.chain_hash seed chain_adrs a i6 remaining
    let a2 ← Array.update pk_elements i a1
    ok (cont (iter1, a2))

/-- [sphincs_c10::wots::pk_from_sig]: loop 1:
    Source: 'sphincs-c10/src/wots.rs', lines 189:4-193:5
    Visibility: public -/
@[rust_loop]
def wots.pk_from_sig_loop1
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (sigma : Array (Array Std.U8 16#usize) 43#usize)
  (digits : Array Std.U8 43#usize) (base_adrs : Array Std.U8 32#usize)
  (pk_elements : Array (Array Std.U8 16#usize) 43#usize) :
  Result (Array (Array Std.U8 16#usize) 43#usize)
  := do
  loop
    (fun (iter1, pk_elements1) => wots.pk_from_sig_loop1.body seed sigma digits
      base_adrs iter1 pk_elements1)
    (iter, pk_elements)

/-- [sphincs_c10::wots::pk_from_sig]:
    Source: 'sphincs-c10/src/wots.rs', lines 162:0-196:1
    Visibility: public -/
def wots.pk_from_sig
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (kp : Std.U32) (msg_hash : Array Std.U8 16#usize)
  (sigma : Array (Array Std.U8 16#usize) 43#usize) (count : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let padded ← hash.pad16 msg_hash
  let wots_adrs ←
    address.make_adrs layer tree params.ADRS_WOTS kp 0#u32 0#u32 0#u32
  let d ← hash.wots_digest seed wots_adrs padded count
  let digits ← wots.extract_digits d
  let sum ←
    wots.pk_from_sig_loop0 { start := 0#usize, «end» := params.L } digits
      0#usize
  if sum != params.TARGET_SUM
  then ok (Array.repeat 16#usize 0#u8)
  else
    let base_adrs ←
      address.make_adrs layer tree params.ADRS_WOTS kp 0#u32 0#u32 0#u32
    let a := Array.repeat 16#usize 0#u8
    let pk_elements := Array.repeat 43#usize a
    let pk_elements1 ←
      wots.pk_from_sig_loop1 { start := 0#usize, «end» := params.L } seed
        sigma digits base_adrs pk_elements
    let pk_adrs ←
      address.make_adrs layer tree params.ADRS_WOTS_PK kp 0#u32 0#u32 0#u32
    let s ← lift (Array.to_slice pk_elements1)
    hash.th_multi seed pk_adrs s

end sphincs_c10
