-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.Verify.Types
import Extracted.Verify.FunsExternal
import Extracted.Adrs
import Extracted.Fors.Funs
import Extracted.Wots.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::SIG_HT_LAYER]
    Source: 'sphincs-c10/src/params.rs', lines 76:0-76:58
    Visibility: public -/
@[global_simps, irreducible]
def params.SIG_HT_LAYER : Result Std.Usize := do
  let i ← params.L * params.N
  let i1 ← i + 4#usize
  let i2 ← params.SUBTREE_H
  let i3 ← i2 * params.N
  i1 + i3

/-- [sphincs_c10::params::SIG_FORS_AUTH]
    Source: 'sphincs-c10/src/params.rs', lines 70:0-70:45 -/
@[global_simps, irreducible]
def params.SIG_FORS_AUTH : Result Std.Usize := do
  let i ← params.K - 1#usize
  let i1 ← i * params.A
  i1 * params.N

/-- [sphincs_c10::params::SIG_FORS_SECRETS]
    Source: 'sphincs-c10/src/params.rs', lines 65:0-65:38 -/
@[global_simps, irreducible]
def params.SIG_FORS_SECRETS : Result Std.Usize := params.K * params.N

/-- [sphincs_c10::params::SIG_R]
    Source: 'sphincs-c10/src/params.rs', lines 62:0-62:23 -/
@[global_simps, irreducible] def params.SIG_R : Std.Usize := params.N

/-- [sphincs_c10::params::SIG_FORS_TOTAL]
    Source: 'sphincs-c10/src/params.rs', lines 73:0-73:75
    Visibility: public -/
@[global_simps, irreducible]
def params.SIG_FORS_TOTAL : Result Std.Usize := do
  let i ← params.SIG_FORS_SECRETS
  let i1 ← params.SIG_R + i
  let i2 ← params.SIG_FORS_AUTH
  i1 + i2

/-- [sphincs_c10::params::SIGNATURE_LEN]
    Source: 'sphincs-c10/src/params.rs', lines 79:0-79:67
    Visibility: public -/
@[global_simps, irreducible]
def params.SIGNATURE_LEN : Result Std.Usize := do
  let i ← params.SIG_HT_LAYER
  let i1 ← params.D * i
  let i2 ← params.SIG_FORS_TOTAL
  i2 + i1

/-- [sphincs_c10::hypertree::verify]: loop body 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 404:4-407:5
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop0.body
  (sig : Array Std.U8 4008#usize) (iter : core.ops.range.Range Std.Usize)
  (offset : Std.Usize) (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × (Array
    (Array Std.U8 16#usize) 13#usize)) (Std.Usize × (Array (Array Std.U8
    16#usize) 13#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (offset, fors_secrets))
  | some t =>
    let (a, index_mut_back) ← Array.index_mut_usize fors_secrets t
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut a)
    let i ← offset + params.N
    let s1 ←
      core.array.Array.index (core.ops.index.IndexSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
        { start := offset, «end» := i }
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let a1 := to_slice_mut_back s2
    let a2 := index_mut_back a1
    ok (cont (iter1, i, a2))

/-- [sphincs_c10::hypertree::verify]: loop 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 404:4-407:5
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop0
  (iter : core.ops.range.Range Std.Usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize) (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  :
  Result (Std.Usize × (Array (Array Std.U8 16#usize) 13#usize))
  := do
  loop
    (fun (iter1, offset1, fors_secrets1) => hypertree.verify_loop0.body sig
      iter1 offset1 fors_secrets1)
    (iter, offset, fors_secrets)

/-- [sphincs_c10::hypertree::verify]: loop body 2:
    Source: 'sphincs-c10/src/hypertree.rs', lines 412:8-415:9
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop1_loop0.body
  (sig : Array Std.U8 4008#usize) (t : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (offset : Std.Usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)) (Std.Usize × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (offset, auth_paths))
  | some h =>
    let (a, index_mut_back) ← Array.index_mut_usize auth_paths t
    let (a1, index_mut_back1) ← Array.index_mut_usize a h
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut a1)
    let i ← offset + params.N
    let s1 ←
      core.array.Array.index (core.ops.index.IndexSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
        { start := offset, «end» := i }
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let a2 := to_slice_mut_back s2
    let a3 := index_mut_back1 a2
    let a4 := index_mut_back a3
    ok (cont (iter1, i, a4))

/-- [sphincs_c10::hypertree::verify]: loop 2:
    Source: 'sphincs-c10/src/hypertree.rs', lines 412:8-415:9
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop1_loop0
  (iter : core.ops.range.Range Std.Usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (t : Std.Usize) :
  Result (Std.Usize × (Array (Array (Array Std.U8 16#usize) 11#usize)
    12#usize))
  := do
  loop
    (fun (iter1, offset1, auth_paths1) => hypertree.verify_loop1_loop0.body sig
      t iter1 offset1 auth_paths1)
    (iter, offset, auth_paths)

/-- [sphincs_c10::hypertree::verify]: loop body 1:
    Source: 'sphincs-c10/src/hypertree.rs', lines 411:4-416:5
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop1.body
  (sig : Array Std.U8 4008#usize) (iter : core.ops.range.Range Std.Usize)
  (offset : Std.Usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)) (Std.Usize × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (offset, auth_paths))
  | some t =>
    let (offset1, auth_paths1) ←
      hypertree.verify_loop1_loop0 { start := 0#usize, «end» := params.A }
        sig offset auth_paths t
    ok (cont (iter1, offset1, auth_paths1))

/-- [sphincs_c10::hypertree::verify]: loop 1:
    Source: 'sphincs-c10/src/hypertree.rs', lines 411:4-416:5
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop1
  (iter : core.ops.range.Range Std.Usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize) :
  Result (Std.Usize × (Array (Array (Array Std.U8 16#usize) 11#usize)
    12#usize))
  := do
  loop
    (fun (iter1, offset1, auth_paths1) => hypertree.verify_loop1.body sig iter1
      offset1 auth_paths1)
    (iter, offset, auth_paths)

/-- [sphincs_c10::hypertree::verify]: loop body 3:
    Source: 'sphincs-c10/src/hypertree.rs', lines 419:4-428:5
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop2.body
  (seed : Array Std.U8 32#usize) (fors_indices : Array Std.U32 13#usize)
  (ht_idx : Std.U32) (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (iter : core.ops.range.Range Std.Usize)
  (fors_roots : Array (Array Std.U8 16#usize) 13#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 13#usize)) (Array (Array Std.U8 16#usize) 13#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done fors_roots)
  | some t =>
    let i ← lift (UScalar.cast .U32 t)
    let i1 ← Array.index_usize fors_indices t
    let a ← Array.index_usize fors_secrets t
    let a1 ← Array.index_usize auth_paths t
    let a2 ← hypertree.reconstruct_fors_root seed ht_idx i i1 a a1
    let a3 ← Array.update fors_roots t a2
    ok (cont (iter1, a3))

/-- [sphincs_c10::hypertree::verify]: loop 3:
    Source: 'sphincs-c10/src/hypertree.rs', lines 419:4-428:5
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop2
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (fors_indices : Array Std.U32 13#usize) (ht_idx : Std.U32)
  (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  (fors_roots : Array (Array Std.U8 16#usize) 13#usize)
  (auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize) :
  Result (Array (Array Std.U8 16#usize) 13#usize)
  := do
  loop
    (fun (iter1, fors_roots1) => hypertree.verify_loop2.body seed fors_indices
      ht_idx fors_secrets auth_paths iter1 fors_roots1)
    (iter, fors_roots)

/-- [sphincs_c10::hypertree::verify]: loop body 5:
    Source: 'sphincs-c10/src/hypertree.rs', lines 447:8-450:9
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop3_loop0.body
  (sig : Array Std.U8 4008#usize) (iter : core.ops.range.Range Std.Usize)
  (offset : Std.Usize) (wots_sigma : Array (Array Std.U8 16#usize) 43#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × (Array
    (Array Std.U8 16#usize) 43#usize)) (Std.Usize × (Array (Array Std.U8
    16#usize) 43#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (offset, wots_sigma))
  | some i =>
    let (a, index_mut_back) ← Array.index_mut_usize wots_sigma i
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut a)
    let i1 ← offset + params.N
    let s1 ←
      core.array.Array.index (core.ops.index.IndexSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
        { start := offset, «end» := i1 }
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let a1 := to_slice_mut_back s2
    let a2 := index_mut_back a1
    ok (cont (iter1, i1, a2))

/-- [sphincs_c10::hypertree::verify]: loop 5:
    Source: 'sphincs-c10/src/hypertree.rs', lines 447:8-450:9
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop3_loop0
  (iter : core.ops.range.Range Std.Usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize) (wots_sigma : Array (Array Std.U8 16#usize) 43#usize) :
  Result (Std.Usize × (Array (Array Std.U8 16#usize) 43#usize))
  := do
  loop
    (fun (iter1, offset1, wots_sigma1) => hypertree.verify_loop3_loop0.body sig
      iter1 offset1 wots_sigma1)
    (iter, offset, wots_sigma)

/-- [sphincs_c10::hypertree::verify]: loop body 6:
    Source: 'sphincs-c10/src/hypertree.rs', lines 463:8-466:9
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop3_loop1.body
  (sig : Array Std.U8 4008#usize) (iter : core.ops.range.Range Std.Usize)
  (offset : Std.Usize) (auth_path : Array (Array Std.U8 16#usize) 9#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × (Array
    (Array Std.U8 16#usize) 9#usize)) (Std.Usize × (Array (Array Std.U8
    16#usize) 9#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (offset, auth_path))
  | some h =>
    let (a, index_mut_back) ← Array.index_mut_usize auth_path h
    let (s, to_slice_mut_back) ← lift (Array.to_slice_mut a)
    let i ← offset + params.N
    let s1 ←
      core.array.Array.index (core.ops.index.IndexSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
        { start := offset, «end» := i }
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let a1 := to_slice_mut_back s2
    let a2 := index_mut_back a1
    ok (cont (iter1, i, a2))

/-- [sphincs_c10::hypertree::verify]: loop 6:
    Source: 'sphincs-c10/src/hypertree.rs', lines 463:8-466:9
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop3_loop1
  (iter : core.ops.range.Range Std.Usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize) (auth_path : Array (Array Std.U8 16#usize) 9#usize) :
  Result (Std.Usize × (Array (Array Std.U8 16#usize) 9#usize))
  := do
  loop
    (fun (iter1, offset1, auth_path1) => hypertree.verify_loop3_loop1.body sig
      iter1 offset1 auth_path1)
    (iter, offset, auth_path)

/-- [sphincs_c10::hypertree::verify]: loop body 4:
    Source: 'sphincs-c10/src/hypertree.rs', lines 441:4-488:5
    Visibility: public -/
@[rust_loop_body]
def hypertree.verify_loop3.body
  (sig : Array Std.U8 4008#usize) (seed : Array Std.U8 32#usize)
  (iter : core.ops.range.Range Std.U32) (offset : Std.Usize)
  (current_node : Array Std.U8 16#usize) (idx_tree : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × Std.Usize × (Array
    Std.U8 16#usize) × Std.U32) (Std.Usize × (Array Std.U8 16#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next U32.Insts.CoreIterRangeStep iter
  match o with
  | none => ok (done (offset, current_node))
  | some layer =>
    let i ← params.SUBTREE_H
    let i1 ← 1#u32 <<< i
    let i2 ← i1 - 1#u32
    let idx_leaf ← lift (idx_tree &&& i2)
    let idx_tree1 ← idx_tree >>> i
    let a := Array.repeat 16#usize 0#u8
    let wots_sigma := Array.repeat 43#usize a
    let (offset1, wots_sigma1) ←
      hypertree.verify_loop3_loop0 { start := 0#usize, «end» := params.L }
        sig offset wots_sigma
    let i3 ← Array.index_usize sig offset1
    let i4 ← offset1 + 1#usize
    let i5 ← Array.index_usize sig i4
    let i6 ← offset1 + 2#usize
    let i7 ← Array.index_usize sig i6
    let i8 ← offset1 + 3#usize
    let i9 ← Array.index_usize sig i8
    let count ←
      lift (core.num.U32.from_be_bytes (Array.make 4#usize [ i3, i5, i7, i9 ]))
    let offset2 ← offset1 + 4#usize
    let a1 := Array.repeat 16#usize 0#u8
    let auth_path := Array.repeat 9#usize a1
    let (offset3, auth_path1) ←
      hypertree.verify_loop3_loop1 { start := 0#usize, «end» := i } sig
        offset2 auth_path
    let i10 ← lift (UScalar.cast .U64 idx_tree1)
    let wots_pk ←
      wots.pk_from_sig seed layer i10 idx_leaf current_node wots_sigma1 count
    let i11 ← lift (UScalar.cast .U64 idx_tree1)
    let current_node1 ←
      merkle.verify_auth_path seed layer i11 wots_pk idx_leaf auth_path1
    ok (cont (iter1, offset3, current_node1, idx_tree1))

/-- [sphincs_c10::hypertree::verify]: loop 4:
    Source: 'sphincs-c10/src/hypertree.rs', lines 441:4-488:5
    Visibility: public -/
@[rust_loop]
def hypertree.verify_loop3
  (iter : core.ops.range.Range Std.U32) (sig : Array Std.U8 4008#usize)
  (seed : Array Std.U8 32#usize) (offset : Std.Usize)
  (current_node : Array Std.U8 16#usize) (idx_tree : Std.U32) :
  Result (Std.Usize × (Array Std.U8 16#usize))
  := do
  loop
    (fun (iter1, offset1, current_node1, idx_tree1) =>
      hypertree.verify_loop3.body sig seed iter1 offset1 current_node1
      idx_tree1)
    (iter, offset, current_node, idx_tree)

/-- [sphincs_c10::hypertree::verify]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 369:0-494:1
    Visibility: public -/
def hypertree.verify
  (pk_seed : Array Std.U8 16#usize) (pk_root : Array Std.U8 16#usize)
  (msg_hash : Array Std.U8 32#usize) (sig : Array Std.U8 4008#usize) :
  Result Bool
  := do
  let seed ← hash.pad16 pk_seed
  let root ← hash.pad16 pk_root
  let r := Array.repeat 16#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut r)
  let i ← 0#usize + params.N
  let s1 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
      { start := 0#usize, «end» := i }
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let r1 := to_slice_mut_back s2
  let r_b32 ← hash.pad16 r1
  let digest ← hash.h_msg seed root r_b32 msg_hash
  let fors_indices ← fors.extract_fors_indices digest
  let ht_idx ← fors.extract_ht_index digest
  let i1 ← params.K - 1#usize
  let i2 ← Array.index_usize fors_indices i1
  if i2 != 0#u32
  then ok false
  else
    let a := Array.repeat 16#usize 0#u8
    let fors_secrets := Array.repeat 13#usize a
    let a1 := Array.repeat 16#usize 0#u8
    let fors_roots := Array.repeat 13#usize a1
    let (offset, fors_secrets1) ←
      hypertree.verify_loop0 { start := 0#usize, «end» := params.K } sig i
        fors_secrets
    let a2 := Array.repeat 16#usize 0#u8
    let a3 := Array.repeat 11#usize a2
    let auth_paths := Array.repeat 12#usize a3
    let (offset1, auth_paths1) ←
      hypertree.verify_loop1 { start := 0#usize, «end» := i1 } sig offset
        auth_paths
    let fors_roots1 ←
      hypertree.verify_loop2 { start := 0#usize, «end» := i1 } seed
        fors_indices ht_idx fors_secrets1 fors_roots auth_paths1
    let i3 ← lift (core.convert.num.FromU64U32.from ht_idx)
    let i4 ← lift (UScalar.cast .U32 i1)
    let last_adrs ←
      address.make_adrs 0#u32 i3 params.ADRS_FORS_TREE i4 0#u32 0#u32 0#u32
    let a4 ← Array.index_usize fors_secrets1 i1
    let a5 ← hash.pad16 a4
    let a6 ← hash.th seed last_adrs a5
    let fors_roots2 ← Array.update fors_roots1 i1 a6
    let fors_pk ← fors.compute_fors_pk seed ht_idx fors_roots2
    let i5 ← lift (UScalar.cast .U32 params.D)
    let (offset2, current_node) ←
      hypertree.verify_loop3 { start := 0#u32, «end» := i5 } sig seed offset1
        fors_pk ht_idx
    let right_val ← params.SIGNATURE_LEN
    massert (offset2 = right_val)
    core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 current_node
      pk_root

end sphincs_c10
