//! GENERATED by `tools/ui_px_assets.py` — do not edit.
//!
//! The pixel-UI atlas (`nonsecure/assets/ui-px/atlas.pq1a`: glyph tiers +
//! disc marks) is linked into the NON-SECURE image at a fixed slot offset
//! and is therefore part of what the FSBL measures at boot (invariant #10).
//! The secure world never trusts those bytes on address alone: it re-hashes
//! the window and compares against this pinned root before AND after every
//! pixel dialog (`crate::ui::px::assets`). A stale bake fails
//! `secure/build.rs` (root != sha256 of the committed container).

/// SHA-256 of the whole `atlas.pq1a` container.
pub const ATLAS_ROOT: [u8; 32] = [0xab, 0xbf, 0xc5, 0x29, 0x24, 0xbd, 0x6f, 0x8f, 0x9e, 0xa7, 0x2f, 0x8c, 0x93, 0xdb, 0xe9, 0x08, 0x28, 0xd1, 0x4b, 0x97, 0x50, 0xa3, 0x9a, 0x80, 0xd8, 0x8d, 0x87, 0x92, 0xdc, 0x70, 0x52, 0x1c];
/// Exact container length in bytes.
pub const ATLAS_LEN: usize = 74204;
