//! GENERATED by `tools/ui_px_assets.py` — do not edit.
//!
//! The pixel-UI atlas (`nonsecure/assets/ui-px/atlas.pq1a`: glyph tiers +
//! disc marks) is linked into the NON-SECURE image at a fixed slot offset
//! and is therefore part of what the FSBL measures at boot (invariant #10).
//! The secure world never trusts those bytes on address alone: it re-hashes
//! the window and compares against this pinned root before AND after every
//! pixel dialog (`crate::ui::px::assets`). A stale bake fails
//! `secure/build.rs` (root != sha256 of the committed container).

/// SHA-256 of the whole `atlas.pq1a` container.
pub const ATLAS_ROOT: [u8; 32] = [0x51, 0x40, 0x78, 0x66, 0xfe, 0x67, 0xe5, 0xf0, 0x07, 0x85, 0xe3, 0x73, 0xff, 0x4e, 0x59, 0x26, 0x3f, 0xab, 0x9b, 0x2d, 0x88, 0x3f, 0x61, 0x10, 0x8a, 0x95, 0x8b, 0x71, 0x9c, 0x76, 0x07, 0x45];
/// Exact container length in bytes.
pub const ATLAS_LEN: usize = 75176;
