//! GENERATED by `tools/ui_px_assets.py` — do not edit.
//!
//! The pixel-UI atlas (`nonsecure/assets/ui-px/atlas.pq1a`: glyph tiers +
//! disc marks) is linked into the NON-SECURE image at a fixed slot offset
//! and is therefore part of what the FSBL measures at boot (invariant #10).
//! The secure world never trusts those bytes on address alone: it re-hashes
//! the window and compares against this pinned root before AND after every
//! pixel dialog (`crate::ui::px::assets`). A stale bake fails
//! `secure/build.rs` (root != sha256 of the committed container).

/// SHA-256 of the whole `atlas.pq1a` container.
pub const ATLAS_ROOT: [u8; 32] = [0xe3, 0xbe, 0x84, 0x58, 0x4e, 0x57, 0x4c, 0xb0, 0xc2, 0xac, 0x05, 0xb0, 0x7b, 0xa6, 0xd0, 0xea, 0x8c, 0x63, 0x1b, 0x94, 0x3f, 0xca, 0xbb, 0x69, 0xc7, 0x9a, 0xd7, 0xda, 0xb3, 0x27, 0xda, 0x1f];
/// Exact container length in bytes.
pub const ATLAS_LEN: usize = 74038;
