-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.Hash.Types
import Extracted.Hash.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- Trait implementation: [core::iter::range::{impl core::iter::range::Step for u32}]
    Source: '/rustc/library/core/src/iter/range.rs', lines 266:12-266:43
    Name pattern: [core::iter::range::Step<u32>] -/
@[reducible, rust_trait_impl "core::iter::range::Step<u32>"]
def U32.Insts.CoreIterRangeStep : core.iter.range.Step Std.U32 := {
  cloneInst := core.clone.CloneU32
  partialOrdInst := core.cmp.PartialOrdU32
  steps_between := U32.Insts.CoreIterRangeStep.steps_between
  forward_checked := U32.Insts.CoreIterRangeStep.forward_checked
  backward_checked := U32.Insts.CoreIterRangeStep.backward_checked
}

/-- [sphincs_c10::params::N]
    Source: 'sphincs-c10/src/params.rs', lines 19:0-19:24
    Visibility: public -/
@[global_simps, irreducible] def params.N : Std.Usize := 16#usize

/-- [sphincs_c10::hash::pad16]:
    Source: 'sphincs-c10/src/hash.rs', lines 161:0-165:1
    Visibility: public -/
def hash.pad16
  (val : Array Std.U8 16#usize) : Result (Array Std.U8 32#usize) := do
  let out := Array.repeat 32#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) out
      { «end» := params.N }
  let s1 ← lift (Array.to_slice val)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [sphincs_c10::hash::truncate]:
    Source: 'sphincs-c10/src/hash.rs', lines 169:0-173:1
    Visibility: public -/
def hash.truncate
  (digest : Array Std.U8 32#usize) : Result (Array Std.U8 16#usize) := do
  let out := Array.repeat 16#usize 0#u8
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out)
  let s1 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) digest
      { «end» := params.N }
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (to_slice_mut_back s2)

/-- [sphincs_c10::hash::th]:
    Source: 'sphincs-c10/src/hash.rs', lines 224:0-231:1
    Visibility: public -/
def hash.th
  (seed : Array Std.U8 32#usize) (adrs : Array Std.U8 32#usize)
  (val : Array Std.U8 32#usize) :
  Result (Array Std.U8 16#usize)
  := do
  let buf := Array.repeat 96#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice seed)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice adrs)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 64#usize, «end» := 96#usize }
  let s7 ← lift (Array.to_slice val)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let s9 ← lift (Array.to_slice buf3)
  let a ← hash.sha256_bytes s9
  hash.truncate a

/-- [sphincs_c10::hash::th_pair]:
    Source: 'sphincs-c10/src/hash.rs', lines 238:0-251:1
    Visibility: public -/
def hash.th_pair
  (seed : Array Std.U8 32#usize) (adrs : Array Std.U8 32#usize)
  (left : Array Std.U8 32#usize) (right : Array Std.U8 32#usize) :
  Result (Array Std.U8 16#usize)
  := do
  let buf := Array.repeat 128#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice seed)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice adrs)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 64#usize, «end» := 96#usize }
  let s7 ← lift (Array.to_slice left)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := 96#usize, «end» := 128#usize }
  let s10 ← lift (Array.to_slice right)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let s12 ← lift (Array.to_slice buf4)
  let a ← hash.sha256_bytes s12
  hash.truncate a

/-- [sphincs_c10::hash::TH_MULTI_MAX]
    Source: 'sphincs-c10/src/hash.rs', lines 255:0-255:35
    Visibility: public -/
@[global_simps, irreducible] def hash.TH_MULTI_MAX : Std.Usize := 43#usize

/-- [sphincs_c10::hash::th_multi]: loop body 0:
    Source: 'sphincs-c10/src/hash.rs', lines 276:4-279:5
    Visibility: public -/
@[rust_loop_body]
def hash.th_multi_loop.body
  (vals : Slice (Array Std.U8 16#usize))
  (iter : core.ops.range.Range Std.Usize) (buf : Array Std.U8 1440#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    1440#usize)) (Array Std.U8 1440#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done buf)
  | some i =>
    let i1 ← 32#usize * i
    let off ← 64#usize + i1
    let i2 ← off + params.N
    let (s, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
        { start := off, «end» := i2 }
    let a ← Slice.index_usize vals i
    let s1 ← lift (Array.to_slice a)
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let buf1 := index_mut_back s2
    ok (cont (iter1, buf1))

/-- [sphincs_c10::hash::th_multi]: loop 0:
    Source: 'sphincs-c10/src/hash.rs', lines 276:4-279:5
    Visibility: public -/
@[rust_loop]
def hash.th_multi_loop
  (iter : core.ops.range.Range Std.Usize)
  (vals : Slice (Array Std.U8 16#usize)) (buf : Array Std.U8 1440#usize) :
  Result (Array Std.U8 1440#usize)
  := do
  loop
    (fun (iter1, buf1) => hash.th_multi_loop.body vals iter1 buf1)
    (iter, buf)

/-- [sphincs_c10::hash::th_multi]:
    Source: 'sphincs-c10/src/hash.rs', lines 268:0-281:1
    Visibility: public -/
def hash.th_multi
  (seed : Array Std.U8 32#usize) (adrs : Array Std.U8 32#usize)
  (vals : Slice (Array Std.U8 16#usize)) :
  Result (Array Std.U8 16#usize)
  := do
  let i := Slice.len vals
  massert (i <= hash.TH_MULTI_MAX)
  let buf := Array.repeat 1440#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice seed)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice adrs)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let i1 := Slice.len vals
  let buf2 := index_mut_back1 s5
  let buf3 ← hash.th_multi_loop { start := 0#usize, «end» := i1 } vals buf2
  let i2 := Slice.len vals
  let i3 ← 32#usize * i2
  let i4 ← 64#usize + i3
  let s6 ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) buf3
      { «end» := i4 }
  let a ← hash.sha256_bytes s6
  hash.truncate a

/-- [sphincs_c10::hash::h_msg]:
    Source: 'sphincs-c10/src/hash.rs', lines 299:0-307:1
    Visibility: public -/
def hash.h_msg
  (seed : Array Std.U8 32#usize) (root : Array Std.U8 32#usize)
  (r : Array Std.U8 32#usize) (message : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  let a := Array.repeat 32#usize 255#u8
  let s ← lift (Array.to_slice seed)
  let s1 ← lift (Array.to_slice root)
  let s2 ← lift (Array.to_slice r)
  let s3 ← lift (Array.to_slice message)
  let s4 ← lift (Array.to_slice a)
  let s5 ← lift (Array.to_slice (Array.make 5#usize [ s, s1, s2, s3, s4 ]))
  hash.sha256_parts s5

/-- [sphincs_c10::hash::chain_hash]: loop body 0:
    Source: 'sphincs-c10/src/hash.rs', lines 334:4-339:5
    Visibility: public -/
@[rust_loop_body]
def hash.chain_hash_loop.body
  (seed : Array Std.U8 32#usize) (start_pos : Std.U32)
  (iter : core.ops.range.Range Std.U32) (current : Array Std.U8 32#usize)
  (a : Array Std.U8 32#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × (Array Std.U8
    32#usize) × (Array Std.U8 32#usize)) (Array Std.U8 32#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next U32.Insts.CoreIterRangeStep iter
  match o with
  | none => ok (done current)
  | some step =>
    let pos ← start_pos + step
    let (s, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) a
        { start := 24#usize, «end» := 28#usize }
    let a1 ← lift (core.num.U32.to_be_bytes pos)
    let s1 ← lift (Array.to_slice a1)
    let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
    let a2 := index_mut_back s2
    let a3 ← hash.th seed a2 current
    let current1 ← hash.pad16 a3
    ok (cont (iter1, current1, a2))

/-- [sphincs_c10::hash::chain_hash]: loop 0:
    Source: 'sphincs-c10/src/hash.rs', lines 334:4-339:5
    Visibility: public -/
@[rust_loop]
def hash.chain_hash_loop
  (iter : core.ops.range.Range Std.U32) (seed : Array Std.U8 32#usize)
  (start_pos : Std.U32) (current : Array Std.U8 32#usize)
  (a : Array Std.U8 32#usize) :
  Result (Array Std.U8 32#usize)
  := do
  loop
    (fun (iter1, current1, a1) => hash.chain_hash_loop.body seed start_pos
      iter1 current1 a1)
    (iter, current, a)

/-- [sphincs_c10::hash::chain_hash]:
    Source: 'sphincs-c10/src/hash.rs', lines 324:0-341:1
    Visibility: public -/
def hash.chain_hash
  (seed : Array Std.U8 32#usize) (adrs : Array Std.U8 32#usize)
  (val : Array Std.U8 16#usize) (start_pos : Std.U32) (steps : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let current ← hash.pad16 val
  let current1 ←
    hash.chain_hash_loop { start := 0#u32, «end» := steps } seed start_pos
      current adrs
  hash.truncate current1

/-- [sphincs_c10::hash::wots_digest]:
    Source: 'sphincs-c10/src/hash.rs', lines 352:0-367:1
    Visibility: public -/
def hash.wots_digest
  (seed : Array Std.U8 32#usize) (wots_adrs : Array Std.U8 32#usize)
  (msg_hash : Array Std.U8 32#usize) (count : Std.U32) :
  Result (Array Std.U8 32#usize)
  := do
  let buf := Array.repeat 128#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf
      { start := 0#usize, «end» := 32#usize }
  let s1 ← lift (Array.to_slice seed)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let buf1 := index_mut_back s2
  let (s3, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf1
      { start := 32#usize, «end» := 64#usize }
  let s4 ← lift (Array.to_slice wots_adrs)
  let s5 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s3 s4
  let buf2 := index_mut_back1 s5
  let (s6, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf2
      { start := 64#usize, «end» := 96#usize }
  let s7 ← lift (Array.to_slice msg_hash)
  let s8 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s6 s7
  let buf3 := index_mut_back2 s8
  let (s9, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) buf3
      { start := 124#usize, «end» := 128#usize }
  let a ← lift (core.num.U32.to_be_bytes count)
  let s10 ← lift (Array.to_slice a)
  let s11 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s9 s10
  let buf4 := index_mut_back3 s11
  let s12 ← lift (Array.to_slice buf4)
  hash.sha256_bytes s12

end sphincs_c10
