(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_bered.sh from cdrafts-split/BadEncSplit.ec (A-D)
   or cdrafts-split/BadEncToTColl.ec (E-G, Z) with exactly one site
   mutated so that INFORMATION is deleted (intro arity unchanged).
   THIS FILE IS EXPECTED TO FAIL TO COMPILE.  Graded by cert_gate_split.sh PHASE 3.
   ######################################################################### *)
(* PROMOTED 2026-09-14 into the certified closure from
   experiments/wots-badenc/red/BadEncSplit.ec (proved there 2026-08-14).
   CODE IS IDENTICAL to that copy once comments are stripped -- asserted by
   scratch/promote_tcoll_chain.py, not claimed.  COMMENT EDITS ONLY: the
   experiment-relative paths (../base, ../cd, ../tcoll) point at the live trees;
   every file:line citation was re-checked against them and the moved ones updated;
   expired claims are corrected at the sentence and marked [CORRECTED 2026-09-14].
   The experiment copy is kept unedited as the historical record. *)
(* ==========================================================================
   BadEncSplit.ec  --  STEP 1 of the BadEnc -> +C reduction.

   THE B1/B2 SPLIT, RESTATED AGAINST THE CURRENT TREE AND PROVED HERE.

   ###################  WHY THIS FILE EXISTS AT ALL  ########################
   `experiments/tcollres-leg/Extraction.ec` states this split already, and
   DOES NOT COMPILE against the current tree:

       [critical] Extraction.ec:51 no matching operator, named encode_msgWOTS_C

   The cause is a TYPE SPLIT, not a typo: that file declares the +C messages as
   `m m' : msgWOTS`, but the live `encode_msgWOTS_C` takes a `dgstblock`
   (`cdrafts-split/WOTS_C_Real.ec:404`), because `ThC` takes a `dgstblock` message and
   returns a `msgWOTS` (`:214`).  Everything downstream of that declaration is
   therefore unchecked text.  So this file RESTATES the split at the live types
   and re-proves it; nothing here `require`s Extraction.ec, and nothing here
   consumes a lemma from it.
   ##########################################################################

   THE THREE LEVELS (live types, checked by this file compiling)

     level 1   +C messages       x, x' : dgstblock
     level 2   ThC digests       ThC ps ad x c        : msgWOTS
     level 3   codewords         encode_msgWOTS_C ps ad x c
                                 = encode_msgWOTS (ThC ps ad x c)   [bridge]

   A level-3 (codeword) collision at a COMMON (ps, ad) has two disjoint causes:

     (B1) the ThC digests already collide  -> the existing S-TCR(+C) target
          collision, charged UPSTREAM (see the finding below);
     (B2) the digests DIFFER but their codewords agree -> exactly MM45's
          encoder-injectivity failure, i.e. the win core of T_COLL_RES_ENUM
          (`cdrafts-split/TCollResEnum.ec`).

   ==========================================================================
   FINDING (2026-08-14) -- B1 IS EMPTY *AT THIS BOUNDARY*, AND RE-CHARGING IT
   WOULD BE THE DOUBLE-CHARGE.  READ BOTH SENTENCES.
   ==========================================================================
   The task this file serves asked for a TWO-term bound

       Pr[Game4_WOTSTWES_BadEnc(R_int_WOTSTW(A)) : res /\ badenc]
         <= <S-TCR(+C) term>  +  Pr[T_COLL_RES_ENUM(R_TCOLL(A))]

   on the stated ground that collapsing to one term would "double-charge or
   silently drop a branch".  Checked against the code, the opposite holds at
   THIS boundary:

     * `Game4_WOTSTWES_BadEnc`'s `res` contains `is_fresh <- m' <> m`
       (`base-c10-split/WOTS_TW_ES.ec:3375`), and `m`, `m'` there are `msgWOTS` --
       i.e. LEVEL-2 values.  Under `R_int_WOTSTW` they are literally the ThC
       digests (`cdrafts-split/WOTS_C_Interactive.ec:1813`, forge returns
       `ThC ps (WAddress.val (nth witness wads i)) m' sigc'.`2`).  So `res`
       ALREADY entails `dg <> dg'`: the (B1) branch makes `res` FALSE and
       contributes nothing to the left-hand side.  `split_under_freshness`
       below is that statement, machine-checked, at the value level; the
       game-level version is `BadEncToTColl.ec`'s step-3 lemma, whose
       conclusion `EncNonInjOnThCSurface` CONTAINS the digest inequality.
     * (B1) is charged one layer UP, not here: `cdrafts-split/WOTS_C_Interactive.ec`
       does `rewrite Pr[mu_split (G0_INT.coll)]` and pays the collision half
       into `S_TCR_C_Int` via `interactive_hop1_reduce`.  `G0_INT.coll` records
       exactly `ThC pp tw m j = ThC pp tw m' ctr` -- (B1).

   Consequence, stated in the direction that costs us something: the ONE-term
   bound is STRICTLY STRONGER than the requested two-term bound, and the
   two-term shape follows from it a fortiori since probabilities are >= 0.  A
   summand that is provably unreachable is not conservative, it is noise -- and
   adding it here would be the second charge for a branch already paid for.

   THE OVER-CLAIM THIS FILE DOES **NOT** MAKE.  "B1 is empty at this boundary"
   (because `is_fresh` excludes it) is NOT "B1 is empty" -- that is
   `B2_is_empty`, the deployed-encoder-bridge question, which is WIDE OPEN and
   is the whole reason T_COLL_RES_ENUM exists.  The two sentences are about
   different things: the first says the (B1) *runs* do not reach this event, the
   second would say the (B2) *event* is impossible.  Nothing here bears on the
   second.

   AXIOM / ADMIT LEDGER.  0 admits, 0 axioms, 0 `declare axiom`.  Every lemma is
   a case split or a rewrite; no premise is introduced that the ambient
   MM45/C10-fork theory does not already carry.

   BUILD.  A closure member since 2026-09-14, compiled as a target by
   `cert_gate_split.sh`; pre-promotion receipt
   `experiments/wots-badenc/red/BadEncSplit.out`.

   NEGATIVE CONTROLS -- `scratch/mkctl_bered.sh` (CtlA..D =
   `scratch/bered_ctl{A..D}.ec`), run by the gate from `cert-controls-split.tsv`.
   ========================================================================== *)
require import AllCore List Distr.
require import SPHINCS_PLUS.
require WOTS_C_Real.
require import TCollResEnum.
import FSSLXMTWES.WTWES.
import HA.Adrs.
import WOTS_C_Real.

(* ==========================================================================
   1.  THE LEVEL-3 COLLISION EVENT, AT LIVE TYPES.

   `COLL` is Extraction.ec's op with `m m' : msgWOTS` corrected to
   `x x' : dgstblock` -- the only change needed, and the one that makes the
   file compile.
   ========================================================================== *)
op COLL (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) : bool =
  encode_msgWOTS_C ps ad x' c' = encode_msgWOTS_C ps ad x c.

(* The split at level 3, with NO premise -- it is a case analysis on level 2.
   This is `coll_splits_by_level` restated live. *)
lemma coll_splits_by_level (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     COLL ps ad x x' c c'
  =>    (ThC ps ad x' c' =  ThC ps ad x c)                       (* B1 *)
     \/ (ThC ps ad x' c' <> ThC ps ad x c                        (* B2 *)
         /\ encode_msgWOTS_C ps ad x' c' = encode_msgWOTS_C ps ad x c).
proof.
rewrite /COLL => hcoll.
case: (ThC ps ad x' c' = ThC ps ad x c) => hthc; first by left.
by right.
qed.

(* The good branch: outside COLL the WOTS chain argument gets exactly the
   hypothesis it consumes (codeword inequality), with no side condition. *)
lemma extraction_good_branch (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     ! COLL ps ad x x' c c'
  => encode_msgWOTS_C ps ad x' c' <> encode_msgWOTS_C ps ad x c.
proof. by rewrite /COLL. qed.

(* ==========================================================================
   2.  THE BRIDGE, AS AN EXPLICIT PREMISE.

   [CORRECTED 2026-09-14.]  When this was written `encode_msgWOTS_C` was an
   ABSTRACT op and the development supplied its factorisation as the named
   hypothesis `encb`.  Since 2026-08-26 (commit 48230de) the op is DEFINED as
   `encode_msgWOTS (ThC p a x cc)` (cdrafts-split/WOTS_C_Real.ec:404) and the
   bridge is the theorem `encode_msgWOTS_C_compat` (:418), so `EncBridge` below
   is now PROVABLE rather than assumed.  It is still stated as a PREMISE of
   `coll_is_encoder_collision`, which is therefore weaker than it needs to be --
   harmless, because nothing in the development consumes that lemma (checked
   2026-09-14).  `query_eq_tw` (cdrafts-split/WOTS_C_Interactive.ec:1863) still
   carries `encb` as a premise (:1910).
   ========================================================================== *)
op EncBridge : bool =
  forall (p : pseed) (a : adrs) (x : dgstblock) (cc : cntr),
    encode_msgWOTS_C p a x cc = encode_msgWOTS (ThC p a x cc).

lemma coll_is_encoder_collision (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     EncBridge
  => (   COLL ps ad x x' c c'
     <=> encode_msgWOTS (ThC ps ad x' c') = encode_msgWOTS (ThC ps ad x c)).
proof. by rewrite /EncBridge /COLL => hb; rewrite !hb. qed.

(* ==========================================================================
   3.  THE SPLIT IN THE CURRENCY T_COLL_RES_ENUM ACTUALLY SPEAKS.

   The target game's win core is `dg <> dg' /\ P dg /\ P dg' /\ e = e'`
   (`cdrafts-split/TCollResEnum.ec` section 3).  So the split has to be stated with
   the +C gate `P` carried, not just the codeword equality.  `P dg'` is NOT a
   second hypothesis: it is DERIVED from `P dg` and codeword equality via
   `P_transfers_across_codeword` (proved in TCollResEnum), because `P` reads its
   argument only through the codeword (`base-c10-split/WOTS_TW_ES.ec:654`).

   `P (ThC ps ad x c)` IS a hypothesis, and it is load-bearing: control CtlA (bered_ctlA)
   replaces it by `true` and the file must then fail.
   ========================================================================== *)
lemma badenc_splits_gated (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c')
  => P (ThC ps ad x c)
  =>    false                                                     (* B1 *)
     \/ (   ThC ps ad x c <> ThC ps ad x' c'                       (* B2 *)
         /\ P (ThC ps ad x c) /\ P (ThC ps ad x' c')
         /\ encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c')).
proof.
move=> hcol hP.
case: (ThC ps ad x c = ThC ps ad x' c') => hthc; first by left.
right; do ! split => //.
by apply (P_transfers_across_codeword (ThC ps ad x c) (ThC ps ad x' c') hcol hP).
qed.

(* Exhaustiveness is not "obviously" exhaustive once `P` is in play -- state it.
   The two branches are also DISJOINT, which is what makes "charge B1 there,
   B2 here" a partition rather than an overlap (the double-charge shape). *)
lemma B1_B2_disjoint (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
  ! (   (ThC ps ad x c = ThC ps ad x' c')
     /\ (   ThC ps ad x c <> ThC ps ad x' c'
         /\ P (ThC ps ad x c) /\ P (ThC ps ad x' c')
         /\ encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c'))).
proof. by apply/negP => -[h1 [h2 _]]; move: h2 => /negP h2; exact (h2 h1). qed.

(* ==========================================================================
   4.  THE (B2) BRANCH *IS* T_COLL_RES_ENUM's WIN CORE.

   This is what makes the split a REDUCTION TARGET rather than a taxonomy: the
   (B2) conjunction entails `EncNonInjOnThCSurface`, the exact residual
   `tcoll_win_needs_coll` extracts from a T_COLL_RES_ENUM win.  Both directions
   of the boundary now speak the same op.

   Binder order in `EncNonInjOnThCSurface` is (ps, ad, m, m', ctr, ctr') --
   recorded-entry first, forged second.  Getting it wrong costs a goal read.
   ========================================================================== *)
lemma B2_is_tcoll_win_core (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     ThC ps ad x c <> ThC ps ad x' c'
  => P (ThC ps ad x c)
  => P (ThC ps ad x' c')
  => encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c')
  => EncNonInjOnThCSurface.
proof.
move=> hne hP hP' hcol.
by rewrite /EncNonInjOnThCSurface; exists ps ad x x' c c'.
qed.

(* ==========================================================================
   5.  THE FINDING, MACHINE-CHECKED: FRESHNESS COLLAPSES THE SPLIT TO (B2).

   `Game4_WOTSTWES_BadEnc`'s `is_fresh` is level-2 inequality.  Under it the
   (B1) disjunct is unreachable and the split has ONE live branch.  This is the
   value-level statement; `BadEncToTColl.ec` lifts it to the composed game.

   NOTE THE DIRECTION.  This does NOT say (B1) is impossible -- it says a run
   in (B1) does not satisfy `res`.  (B1) is real, and it is paid for upstream at
   `cdrafts-split/WOTS_C_Interactive.ec`'s `Pr[mu_split (G0_INT.coll)]`.
   ========================================================================== *)
lemma split_under_freshness (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     ThC ps ad x c <> ThC ps ad x' c'                            (* = is_fresh *)
  => encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c')  (* = badenc *)
  => P (ThC ps ad x c)
  =>    ThC ps ad x c <> ThC ps ad x' c'
     /\ P (ThC ps ad x c) /\ P (ThC ps ad x' c')
     /\ encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c').
proof.
move=> hne hcol hP.
have := badenc_splits_gated ps ad x x' c c' hcol hP.
by case=> [hb1 | //]; move: hne; rewrite hb1.
qed.

(* The one-line corollary the composed-game proof consumes: freshness + badenc
   + the +C gate land directly in the target game's residual. *)
lemma freshness_gives_tcoll_core (ps : pseed) (ad : adrs) (x x' : dgstblock) (c c' : cntr) :
     ThC ps ad x c <> ThC ps ad x' c'
  => encode_msgWOTS (ThC ps ad x c) = encode_msgWOTS (ThC ps ad x' c')
  => P (ThC ps ad x c)
  => EncNonInjOnThCSurface.
proof.
move=> hne hcol hP.
have [h1 [h2 [h3 h4]]] := split_under_freshness ps ad x x' c c' hne hcol hP.
by apply (B2_is_tcoll_win_core ps ad x x' c c').
qed.
