#!/bin/sh
# Regenerate the two MUST-FAIL controls for cdrafts-split/GprocWotsNamed.ec.
# A drops the CHARGED WOTS LEG from the composition -- the control that matters:
#   a green compile there would mean the substitution does nothing.
# B drops the deployed statement.  Both MUST fail.
set -eu
cd "$(dirname "$0")/.."
python3 - <<'PY'
s = open('cdrafts-split/GprocWotsNamed.ec').read()
banner = ("(* #########################################################################\n"
          "   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.\n"
          "   Generated by scratch/mkctl_gwn.sh from cdrafts-split/GprocWotsNamed.ec.\n"
          "   ######################################################################### *)\n")
def gen(name, old):
    assert s.count(old) == 1, (name, s.count(old))
    open('scratch/' + name + '.ec', 'w').write(banner + s.replace(old, ''))
gen('gwn_ctlA', "have h2 := wots_leg_charged_at_deployed F &m hgrind Fll.\n")
gen('gwn_ctlB', "have h1 := EUFCMA_SPHINCS_PLUS_C10_CHARGED_QWIRED_TIGHT_AT_DEPLOYED_PARAMS F &m hc hsz.\n")
print("regenerated gwn_ctl{A,B}.ec")
PY
