#!/usr/bin/env bash
# PROMOTED 2026-09-14.  Mutation specs below are copied VERBATIM, by script, from
#   experiments/wots-badenc/tcoll/mkctl.sh
# -- only source/output paths changed.  scratch/check_tcoll_ctls_match.py then
# checks every generated control against the experiment's own control by
# comment-stripped equality, so a porting slip is CAUGHT rather than trusted.
# Regenerate the SIX MUST-FAIL negative controls from TCollResEnum.ec.
#   A--D  delete exactly ONE hypothesis of `tcoll_witness_hoare` +
#         `tcoll_witness_is_one`, replacing it by `true` so the proof scripts'
#         intro arity is unchanged: the control deletes INFORMATION, it does not
#         break the syntax.
#   E     mutates the CONCLUSION (1%r -> 0%r).
#   F     deletes the load-bearing conjunct of the recorded-entry invariant
#         `tcoll_wf`, which is what `tcoll_win_needs_coll` (section 5) consumes.
# All six MUST fail to compile.  A green compile means the corresponding
# hypothesis is not load-bearing and the evidence is worthless -- report that.
set -eu
cd "$(dirname "$0")/.."
banner() {
cat <<'EOF'
(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_tcoll.sh from cdrafts-split/TCollResEnum.ec with exactly one hypothesis
   replaced by `true` (CtlA--CtlD, CtlF) or the conclusion mutated (CtlE).
   THIS FILE IS EXPECTED TO FAIL TO COMPILE.  Graded by cert_gate_split.sh PHASE 3.
   ######################################################################### *)
EOF
}
H='     1 <= p_tgts => W_gated => W_distinct => W_collides'
gen() { # $1 = name, $2 = replacement hypothesis line
  { banner; sed "s|^${H}\$|$2|" cdrafts-split/TCollResEnum.ec; } > "scratch/tcoll_ctl${1#Ctl}.ec"
}
gen CtlA '     1 <= p_tgts => W_gated => W_distinct => true'
gen CtlB '     1 <= p_tgts => W_gated => true => W_collides'
gen CtlC '     1 <= p_tgts => true => W_distinct => W_collides'
gen CtlD '     true => W_gated => W_distinct => W_collides'
{ banner; sed 's|^          : res\] = 1%r\.$|          : res] = 0%r.|' cdrafts-split/TCollResEnum.ec; } > scratch/tcoll_ctlE.ec
{ banner; perl -pe 's/\Qt.`5 = encode_msgWOTS t.`4.\E/true./' cdrafts-split/TCollResEnum.ec; } > scratch/tcoll_ctlF.ec
chmod 666 scratch/tcoll_ctl?.ec 2>/dev/null || true
# ANCHOR GUARD (added on promotion; the experiment generator had none): a sed/perl
# anchor that stops matching emits an UNMUTATED copy, which compiles green for the
# trivial reason.  The banner is 6 lines, so the source starts at line 7.
for x in A B C D E F; do
  if cmp -s <(tail -n +7 "scratch/tcoll_ctl$x.ec") cdrafts-split/TCollResEnum.ec; then
    echo "FATAL: scratch/tcoll_ctl$x.ec is unmutated -- the anchor did not match" >&2; exit 1
  fi
done
echo "regenerated scratch/tcoll_ctl{A..F}.ec; every mutation anchor matched"
