#!/bin/sh
# Regenerate the three MUST-FAIL controls for cdrafts-split/GprocTCollNamed.ec.
# A: drop `badenc_le_tcoll` from the composition -- THE ONE THAT MATTERS: a green
#    compile would mean substituting the T_COLL term for the BadEnc term does nothing.
# B: drop the WOTSNAMED statement from the composition.
# C: drop the ONE new module separation, -O_TCollEnum_Default, from F.
set -eu
cd "$(dirname "$0")/.."
python3 - <<'PY'
s = open('cdrafts-split/GprocTCollNamed.ec').read()
def gen(name, old, new):
    assert s.count(old) == 1, (name, s.count(old))
    banner = ("(* #########################################################################\n"
              "   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.\n"
              "   Generated by scratch/mkctl_gtn.sh from cdrafts-split/GprocTCollNamed.ec.\n"
              "   A green compile here would mean the deleted fact is NOT load-bearing.\n"
              "   ######################################################################### *)\n")
    open('scratch/' + name + '.ec', 'w').write(banner + s.replace(old, new))
gen('gtn_ctlA',
    "have h2 := badenc_le_tcoll (R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F))) &m hc.\n",
    "")
gen('gtn_ctlB',
    "have h1 := EUFCMA_SPHINCS_PLUS_C10_CHARGED_QWIRED_TIGHT_AT_DEPLOYED_PARAMS_WOTSNAMED F &m hgrind Fll hc hsz.\n",
    "")
# C must delete the separation AND the comma before it.  The first version replaced only
# `-O_TCollEnum_Default })` and left `-R_SMDTPREC_Game4WOTSTWES,` dangling: the control
# then failed with `parse error` -- a syntax failure that proves nothing about the
# restriction.  Caught by reading the failure reason before registering the control.
import re
blk = re.search(r"-R_SMDTPREC_Game4WOTSTWES,(\s*\(\*.*?\*\))\s*-O_TCollEnum_Default \}\)", s, re.S)
assert blk is not None and len(re.findall(r"-O_TCollEnum_Default \}\)", s)) == 1
gen('gtn_ctlC', blk.group(0), "-R_SMDTPREC_Game4WOTSTWES" + blk.group(1) + " })")
print("regenerated gtn_ctl{A,B,C}.ec")
PY
