#!/bin/sh
# Regenerate the three MUST-FAIL controls for cdrafts-split/WotsLegCharged.ec.
# A: drop the GRIND-REACHABILITY premise.  B: drop forger losslessness.
# C: drop ONE of the six WOTS-TW separations from F.  All three MUST fail.
set -eu
cd "$(dirname "$0")/.."
python3 - <<'PY'
s = open('cdrafts-split/WotsLegCharged.ec').read()
def gen(name, old, new):
    assert s.count(old) == 1, (name, s.count(old))
    banner = ("(* #########################################################################\n"
              "   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.\n"
              "   Generated by scratch/mkctl_wlc.sh from cdrafts-split/WotsLegCharged.ec.\n"
              "   A green compile here would mean the deleted premise is NOT load-bearing.\n"
              "   ######################################################################### *)\n")
    open('scratch/' + name + '.ec', 'w').write(banner + s.replace(old, new))
gen('wlc_ctlA',
    "     (forall (m : msg), is_lossless (dcond dmkey (good_fors m))) =>",
    "     true =>")
gen('wlc_ctlB',
    "     (forall (O <: SOracle_CMA_C{-F}), islossless O.sign => islossless F(O).forge) =>",
    "     true =>")
gen('wlc_ctlC',
    """             -FC_UD.O_SMDTUD_Default, -FC_TCR.O_SMDTTCR_Default,
             -FC_PRE.O_SMDTPRE_Default, -R_SMDTUDC_Game23WOTSTWES,
             -R_SMDTTCRC_Game34WOTSTWES, -R_SMDTPREC_Game4WOTSTWES }) &m :""",
    """             -FC_UD.O_SMDTUD_Default, -FC_TCR.O_SMDTTCR_Default,
             -FC_PRE.O_SMDTPRE_Default,
             -R_SMDTTCRC_Game34WOTSTWES, -R_SMDTPREC_Game4WOTSTWES }) &m :""")
print("regenerated wlc_ctl{A,B,C}.ec")
PY
