#!/bin/sh
# Regenerate the four MUST-FAIL controls for cdrafts-split/BadEncCountermodel.ec.
# Promoted from experiments/wots-badenc/mkctl.sh 2026-08-31 when the countermodel
# entered the certified closure.  A,B,C each delete exactly ONE hypothesis; D
# mutates the CONCLUSION.  All four MUST fail to compile, each for its own reason
# (cert-controls-split.tsv declares them; the gate checks the reason, not just rc).
set -eu
cd "$(dirname "$0")/.."
SRC=cdrafts-split/BadEncCountermodel.ec
banner() {
cat <<'EOF'
(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_badenc_split.sh from
   cdrafts-split/BadEncCountermodel.ec with exactly one hypothesis of
   `badenc_game_hoare` / `badenc_is_one` replaced by `true` (or, for CtlD, the
   CONCLUSION 1%r replaced by 0%r).
   THIS FILE IS EXPECTED TO FAIL TO COMPILE.  A green compile here would mean
   the corresponding hypothesis is NOT load-bearing, i.e. the real theorem is
   weaker (or more vacuous) than it looks.
   ######################################################################### *)
EOF
}
gen() {
  { banner; sed "s|^     P cm => cm <> cm' => encode_msgWOTS cm = encode_msgWOTS cm'$|$2|" "$SRC"; } > "scratch/$1.ec"
}
gen badenc_ctlA "     P cm => cm <> cm' => true"
gen badenc_ctlB "     P cm => true => encode_msgWOTS cm = encode_msgWOTS cm'"
gen badenc_ctlC "     true => cm <> cm' => encode_msgWOTS cm = encode_msgWOTS cm'"
{ banner; sed "s|: res /\\\\ BadEncFlag.badenc\] = 1%r.|: res /\\\\ BadEncFlag.badenc] = 0%r.|" "$SRC"; } > scratch/badenc_ctlD.ec
