#!/usr/bin/env bash
# PROMOTED 2026-09-14.  Mutation specs below are copied VERBATIM, by script, from
#   experiments/wots-badenc/red/mkctl.sh
# -- only source/output paths changed.  scratch/check_tcoll_ctls_match.py then
# checks every generated control against the experiment's own control by
# comment-stripped equality, so a porting slip is CAUGHT rather than trusted.
# Regenerate the MUST-FAIL negative controls for BadEncSplit.ec (STEP 1).
#
# Each control DELETES INFORMATION at exactly one site and leaves the proof
# script's intro arity unchanged, so the file fails because a hypothesis is
# missing -- not because the syntax broke.
#
#   CtlA  `badenc_splits_gated`: the +C gate `P (ThC ps ad x c)` -> `true`.
#         The (B2) branch can then no longer produce `P dg` (nor `P dg'` via
#         `P_transfers_across_codeword`).
#   CtlB  `badenc_splits_gated`: the (B1) DISJUNCT -> `false`.  THIS IS THE
#         CONTROL THAT GUARDS THE HEADLINE.  If it compiles green then "B1 is
#         empty" is baked into the split itself and the whole finding is
#         worthless -- report that loudly.
#   CtlC  `split_under_freshness`: the freshness hypothesis -> `true`.  Tests
#         that freshness, and nothing else, is what collapses the split to (B2).
#   CtlD  `B2_is_tcoll_win_core`: the digest INEQUALITY -> `true`.  Tests that
#         landing in T_COLL_RES_ENUM's residual really needs `dg <> dg'`.
#
# ALL EIGHT MUST FAIL (A-D above; E-G and Z below).  Graded by cert_gate_split.sh PHASE 3.
set -eu
cd "$(dirname "$0")/.."
banner() {
cat <<'EOF'
(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_bered.sh from cdrafts-split/BadEncSplit.ec (A-D)
   or cdrafts-split/BadEncToTColl.ec (E-G, Z) with exactly one site
   mutated so that INFORMATION is deleted (intro arity unchanged).
   THIS FILE IS EXPECTED TO FAIL TO COMPILE.  Graded by cert_gate_split.sh PHASE 3.
   ######################################################################### *)
EOF
}

# CtlA -- the +C gate premise of badenc_splits_gated (anchored by the B1 line
#         that follows it, so the substitution cannot hit the other three
#         lemmas that carry a textually identical premise).
{ banner; perl -0777 -pe 's/  => P \(ThC ps ad x c\)\n  =>    \(ThC ps ad x c = ThC/  => true\n  =>    (ThC ps ad x c = ThC/s' cdrafts-split/BadEncSplit.ec; } > scratch/bered_ctlA.ec

# CtlB -- the (B1) disjunct itself.
{ banner; perl -0777 -pe 's/  =>    \(ThC ps ad x c = ThC ps ad x. c.\)                          \(\* B1 \*\)/  =>    false                                                     (* B1 *)/s' cdrafts-split/BadEncSplit.ec; } > scratch/bered_ctlB.ec

# CtlC -- the freshness premise of split_under_freshness (anchored by its
#         in-line marker comment, which occurs exactly once).
{ banner; perl -0777 -pe 's/     ThC ps ad x c <> ThC ps ad x. c.                            \(\* = is_fresh \*\)/     true                                                        (* = is_fresh *)/s' cdrafts-split/BadEncSplit.ec; } > scratch/bered_ctlC.ec

# CtlD -- the digest inequality premise of B2_is_tcoll_win_core (anchored by
#         the two `P` premises that follow it).
{ banner; perl -0777 -pe 's/     ThC ps ad x c <> ThC ps ad x. c.\n  => P \(ThC ps ad x c\)\n  => P \(ThC ps ad x. c.\)/     true\n  => P (ThC ps ad x c)\n  => P (ThC ps ad x\x27 c\x27)/s' cdrafts-split/BadEncSplit.ec; } > scratch/bered_ctlD.ec

# ---- STEP 2/3 controls, from BadEncToTColl.ec --------------------------------
#   CtlE  `badenc_target_from_inv`: the `wads_parallel` premise -> `true`.
#         THE load-bearing invariant: without it the two ThC images sit at
#         unrelated tweaks and the conclusion is not EncNonInjOnThCSurface.
#   CtlF  `badenc_target_from_inv`: the `qs_ThC_images` premise -> `true`.
#         Without it the retrieved message is not known to be a ThC image at
#         all, so there is no (ps, ad) to instantiate the residual with.
#   CtlG  `badenc_target`: the `m' <> m` (is_fresh) conjunct -> `true`.
#         This is the control that guards the "B1 is empty at this boundary"
#         claim AT THE GAME LEVEL: delete freshness and the (B2) witness cannot
#         be produced.
#   CtlZ  anti-fail-open: append `lemma NEGCTL : false` proved by `trivial`.
#         If THIS compiles the file is not being checked at all.

# CtlE
{ banner; perl -0777 -pe 's/     wads_parallel wads qs\n  => qs_ThC_images ps qs\n  => badenc_target/     true\n  => qs_ThC_images ps qs\n  => badenc_target/s' cdrafts-split/BadEncToTColl.ec; } > scratch/bered_ctlE.ec
# CtlF
{ banner; perl -0777 -pe 's/  => qs_ThC_images ps qs\n  => badenc_target ps qs i/  => true\n  => badenc_target ps qs i/s' cdrafts-split/BadEncToTColl.ec; } > scratch/bered_ctlF.ec
# CtlG
{ banner; perl -0777 -pe 's/      \/\\ m. <> m                                          \(\* is_fresh \*\)/      \/\\ true                                              (* is_fresh *)/s' cdrafts-split/BadEncToTColl.ec; } > scratch/bered_ctlG.ec
# CtlZ
{ banner; cat cdrafts-split/BadEncToTColl.ec; printf '\nlemma NEGCTL : false.\nproof. trivial. qed.\n'; } > scratch/bered_ctlZ.ec

chmod 666 scratch/bered_ctl?.ec 2>/dev/null || true

# PROMOTION FIX 2026-09-14: the experiment guard used `tail -n +8` against a 6-line
# banner, so the comparison was offset by one line and could never report a match --
# a vacuous guard.  `+7` is correct: banner lines 1-6, source from line 7.
# Fail loudly if a control is byte-identical to the source: that would make the
# control vacuous (it would compile green for the trivial reason).
for f in CtlA CtlB CtlC CtlD; do
  if diff -q <(tail -n +7 "scratch/bered_ctl${f#Ctl}.ec") cdrafts-split/BadEncSplit.ec > /dev/null 2>&1; then
    echo "FATAL: scratch/bered_ctl${f#Ctl}.ec is unmutated -- the anchor did not match" >&2
    exit 1
  fi
done
for f in CtlE CtlF CtlG; do
  if diff -q <(tail -n +7 "scratch/bered_ctl${f#Ctl}.ec") cdrafts-split/BadEncToTColl.ec > /dev/null 2>&1; then
    echo "FATAL: scratch/bered_ctl${f#Ctl}.ec is unmutated -- the anchor did not match" >&2
    exit 1
  fi
done
echo "controls regenerated; every mutation anchor matched"
