(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_tcoll.sh from cdrafts-split/TCollResEnum.ec with exactly one hypothesis
   replaced by `true` (CtlA--CtlD, CtlF) or the conclusion mutated (CtlE).
   THIS FILE IS EXPECTED TO FAIL TO COMPILE.  Graded by cert_gate_split.sh PHASE 3.
   ######################################################################### *)
(* PROMOTED 2026-09-14 into the certified closure from
   experiments/wots-badenc/tcoll/TCollResEnum.ec (proved there 2026-08-13).
   CODE IS IDENTICAL to that copy once comments are stripped -- asserted by
   scratch/promote_tcoll_chain.py, not claimed.  COMMENT EDITS ONLY: the
   experiment-relative paths (../base, ../cd, ../tcoll) point at the live trees;
   every file:line citation was re-checked against them and the moved ones updated;
   expired claims are corrected at the sentence and marked [CORRECTED 2026-09-14].
   The experiment copy is kept unedited as the historical record. *)
(* ==========================================================================
   TCollResEnum.ec  --  T_COLL_RES_ENUM: the +C-layer target-collision game
                        that the WOTS-TW BadEnc charge must MOVE to.

   ###################  READ THIS BEFORE CITING THE FILE  ###################
   THIS FILE IS A DEFINITION PLUS EVIDENCE.  IT IS NOT A PROVED REDUCTION.
   ##########################################################################

   WHAT IS DEFINED HERE
   --------------------
     * `Oracle_TCollEnum` / `O_TCollEnum_Default` -- the target oracle.  On
       (ad, m) it ENUMERATES the counter with the deployed grind
       (`ctr <- grindC ps ad m`), evaluates `dg <- ThC ps ad m ctr`, encodes
       `e <- encode_msgWOTS dg`, records the 5-tuple (ad, m, ctr, dg, e), and
       returns (e, ctr).
     * `Adv_TCollResEnum` -- the adversary: `pick()` with access to BOTH the
       target oracle and the keyed collection oracle, then `find(ps)` with the
       public seed and no oracles.
     * `T_COLL_RES_ENUM` -- the game.  The adversary wins on index `i` with
       (m', ctr') when the i-th recorded digest and `ThC ps ad m' ctr'` are
       DISTINCT, both satisfy the +C gate `P`, and their codewords are EQUAL.

   AND THE EVIDENCE THAT IT IS NOT DEGENERATE (both directions, sections 4-6)
     * `win_core_iff` -- the win core IS "encoder non-injectivity on the
       constant-sum surface", nothing more and nothing less.
     * `tcoll_win_needs_coll` -- NO TRIVIAL WIN: for an ARBITRARY adversary, any
       win entails `EncNonInjOnThCSurface` -- a collision between two `ThC`
       IMAGES AT A COMMON (ps, ad), not merely between two msgWOTS values.  The
       structure is the content: the weaker `EncNonInjOnSurface` is satisfied by
       `cdrafts-split/BadEncCountermodel.ec`'s free `cm`/`cm'` too, so it would not
       discriminate this layer from the one the charge is leaving.  This is the
       direction that matters for a term you intend to PAY: at the WOTS-TW layer
       the analogous event was winnable for free, and this lemma says that route
       is closed here.
     * `tcoll_witness_is_one` -- SATISFIABLE IN PRINCIPLE: an explicit one-query
       adversary wins with probability 1 under an explicitly stated collision
       hypothesis, so the win condition is not identically false.

   WHY IT EXISTS
   -------------
   MM45's WOTS-TW proof admits encoder injectivity, which is FALSE at deployed
   C10 geometry.  The fork replaced that admit with an explicit BadEnc charge,
   and `cdrafts-split/BadEncCountermodel.ec` then PROVED that the charge cannot be
   bounded where it sits: for an explicit replay adversary
   `Pr[Game4_WOTSTWES_BadEnc(A_coll) : res /\ badenc] = 1`.  The reason is that
   the WOTS-TW game lets the adversary choose the message FREELY, so it can
   simply hand over a colliding pair.  At the +C layer it cannot: the WOTS
   message is `ThC ps ad m ctr`, a keyed digest it does not control.  This file
   states the game where the term can plausibly live.

   WHAT IS **NOT** PROVED HERE (and is deliberately absent)
   -------------------------------------------------------
     * THE REDUCTION FROM BadEnc.  There is NO lemma here of the form
       "Pr[Game4_WOTSTWES_BadEnc(A) : res /\ badenc] <= Pr[T_COLL_RES_ENUM(R(A))]"
       and none is sketched in tactics.  [CORRECTED 2026-09-14 -- this said
       "Building `R` is the next unit of work.  Until it exists, this game charges
       nothing".  It was built the next day and is promoted alongside this file:
       `R_TCOLL` is cdrafts-split/BadEncToTColl.ec and the inequality is
       cdrafts-split/BadEncStep4.ec::badenc_le_tcoll.  What stays true: nothing
       in THIS file charges anything, and the BadEnc summand is still UNBOUNDED --
       moving it to this game does not bound it.]
     * THAT THE TERM IS SMALL.  Nothing here bounds `Pr[T_COLL_RES_ENUM(B)]`.
       The non-vacuity evidence below points the OTHER way -- it shows the win
       event is reachable in principle, which is what you want from a game you
       intend to pay for, and says nothing about how much you will pay.
     * THAT AN ENCODER COLLISION EXISTS ON THE CONSTANT-SUM SURFACE AT DEPLOYED
       GEOMETRY.  `ThC` is a defined op over an ABSTRACT `thfc`/`emb_in` here,
       so the colliding pair is carried as an explicit HYPOTHESIS
       (`W_distinct` / `W_collides` / `W_gated` below), exactly as
       `cdrafts-split/BadEncCountermodel.ec` carries `cm`/`cm'`.  The deployed-geometry
       identification would come from `experiments/tcollres-leg/ThCWidth.ec`
       (`predC_sum_inhabited`, via Proj129); its transfer crosses the
       int/emsgWOTS boundary by HAND TRANSCRIPTION, not machine check, and this
       file does not reach for it.

   THE THREE DESIGN CONSTRAINTS, WITH THEIR SOURCES
   ------------------------------------------------
   Each of these cost a review round (GPT-5.6 and Kimi K3, independently), and
   each is a place where the obvious simplification is a SILENT SOUNDNESS GAP.

   (C1) THE COLLECTION ORACLE `OC` IS AVAILABLE DURING `pick`, AND IS
        INITIALISED WITH THE REAL `ps` BEFORE `pick` RUNS.
        Source: the WOTS-TW adversary this game must eventually absorb has
        exactly that access -- `base-c10-split/WOTS_TW_ES.ec:2610-2611`,
        `module type Adv_MEUFGCMA_WOTSTWESNPRF(O, OC) = { proc choose() : unit
        { O.query, OC.query } ... }`.  The init ORDER mirrors `S_TCR_C.main`
        (`cdrafts-split/STCR_C.ec`: `pp <$ dpp; OC.init(pp); O.init(pp); A.pick()`).
        Dropping `OC`, or keying it with anything other than the sampled `ps`,
        models a WEAKER adversary than the real one and would make the eventual
        reduction unsound rather than merely lossy.
        WHICH collection: `FC.Oracle_THFC` (the SPHINCS+ collection over `dgst`,
        `base-c10-split/WOTS_TW_ES.ec:505`), NOT `STCRC_WC.Col.Oracle_THFC` (the +C
        collection over `dgstblock * cntr`).  Reason: a reduction `R(A)` running
        a WOTS-TW/BadEnc adversary must answer that adversary's ARBITRARY `dgst`
        collection queries at the real `ps`; only `FC` can serve them.  `FC` also
        subsumes the +C collection constructively -- `ThC ps tw (m, ctr)` is two
        `FC` queries at tweak `emb_tw tw` on `emb_in0/emb_in1 (m, ctr)`
        (`cdrafts-split/WOTS_C_Real.ec:214`) -- so it is the STRICTLY STRONGER adversary,
        which is the safe direction for an assumption.

   (C2) THE DISCRIMINATOR IS `dg <> dg'`, NOT `m' <> m`.
        Source: `experiments/tcollres-leg/Extraction.ec`, lemma
        `coll_splits_by_level` (:82-90, prose at :70-79).  A level-3 (codeword)
        collision splits into (B1) the ThC digests ALREADY collide -- charged to
        the existing S-TCR(+C) term -- and (B2) the digests DIFFER but their
        codewords agree.  THIS GAME IS (B2).  Keying the win on `m' <> m` would
        overlap (B1) and double-charge, and worse, would admit wins where the
        digests are equal, which is not an encoder failure at all.

   (C3) THE ADVERSARY'S COUNTER IS NOT REQUIRED TO BE THE HONEST ONE:
        there is NO `ctr' = grindC ps ad m'` conjunct.
        Source: `cdrafts-split/WOTS_C_Scheme.ec` -- `verify` takes
        `sigc : sigWOTS * cntr` (:72), reads `counter <- sigc.\`2` (:89), and
        recomputes BOTH the encoding (`em <- encode_msgWOTS_C ps ad m counter`,
        :91) and the +C gate (`okC <- predC (ThC ps ad m counter)`, :101) from
        that SUPPLIED counter.  A forger therefore gets to choose it, and
        requiring the honest grind would model a weaker adversary than the
        scheme actually admits.
        The HONEST side is a different matter and IS enumerated: the target
        oracle uses `grindC` (`cdrafts-split/WOTS_C_Real.ec:423`), because the signer
        does.

   WHY THE NAME SAYS "ENUM", AND WHY IT IS NOT "Def 11"
   ---------------------------------------------------
   Paper Definition 11 SAMPLES the encoder's randomness.  C10 does not: the
   deployed WOTS+C encoder enumerates a counter deterministically.  The repo
   records this itself at `cdrafts-split/IncEnc.ec` (marker (M2), the `drand`
   bullet, :286): "the deployed WOTS+C encoder ENUMERATES a counter
   deterministically rather than sampling, so instantiating this game at C10
   needs a separate coupling argument, not just a choice of `drand`".  That
   coupling is NOT supplied here.  Calling this game "Definition 11" would
   assert the coupling by naming; the "ENUM" suffix refuses to.

   FAITHFULNESS NOTES (deliberate deviations from the S-TCR(+C) template)
   ---------------------------------------------------------------------
     * NO DISJOINTNESS CONJUNCT.  `S_TCR_C` requires
       `Col.disj_lists twsO twsOC`; this game does not, and does not even call
       `OC.get_tweaks()`.  Effect, stated in the honest direction: the win set is
       LARGER, so the term is LARGER, so the ASSUMPTION "this term is small" is
       STRICTLY STRONGER and correspondingly harder to justify later from a THF
       assumption.  It is sound to charge, expensive to believe.  The oracle's
       tweaks are unconstrained in this version.
     * `0 <= nrts` is omitted from the win condition (`S_TCR_C` writes
       `0 <= nrts <= p_stcr`).  `nrts` is a `size`, so the conjunct is a theorem
       and its omission deletes no information.
     * `P dg'` IS REDUNDANT, ON PURPOSE.  `win_core_iff` below PROVES it is
       implied by `P dg` and `e = e'`.  It is kept in the win condition because
       the design as reviewed states it, and because a reader checking the game
       against the (B2) branch expects both gates to appear.  Nothing depends on
       its redundancy, but a control that deleted it would compile green -- so it
       is not used as a control, and this note is here so the redundancy is not
       discovered as a surprise.

   AXIOM / ADMIT LEDGER
   --------------------
   0 admits, 0 axioms, 0 `declare axiom` in this file.  Everything is relative to
   the ambient MM45/C10-fork theory and its declared parameters, which this file
   does not extend: `ge0_ptgts` (`cdrafts-split/WOTS_C_Real.ec:340`),
   `op [lossless] dpseed`, `ge2_len`.  `1 <= p_tgts` is a HYPOTHESIS of the
   witness lemmas, not an axiom -- `ge0_ptgts` alone permits `p_tgts = 0`, under
   which the game is unwinnable because no query fits the budget.

   BUILD.  a closure member since 2026-09-14, compiled as a target by
   `cert_gate_split.sh`; pre-promotion receipt
   `experiments/wots-badenc/tcoll/tcoll.out`.  `experiments/wots-badenc/tcoll/dump.sh <File>`
   prints goal states via `easycrypt cli` -- the two proofs below that needed a
   goal read say so in place, and neither was guessed.

   NEGATIVE CONTROLS -- SIX, ALL MUST FAIL, ALL DO.  Regenerate with
   `scratch/mkctl_tcoll.sh` (CtlA..F = `scratch/tcoll_ctl{A..F}.ec`); the
   gate runs them from `cert-controls-split.tsv` and grades the declared reason.
   A--D each replace exactly ONE hypothesis of `tcoll_witness_hoare` +
   `tcoll_witness_is_one` by `true`, so the proof script's intro arity is
   unchanged and the control deletes INFORMATION rather than breaking syntax.
   Recorded receipts:

     CtlA  no `W_collides`   RC=1  `true` supplied where `W_collides` expected
                                   (final `exact (W_collides_at ps hcol)`)
     CtlB  no `W_distinct`   RC=1  `true` where `W_distinct` expected
     CtlC  no `W_gated`      RC=1  `true` where `W_gated` expected
     CtlD  no `1 <= p_tgts`  RC=1  `nrts <= p_tgts` survives `=> />`, so the
                                   first bullet's term no longer applies
     CtlE  `= 0%r` for `= 1%r`
                             RC=1  `[by]: cannot close goals` at the packaging
                                   step -- it really proves the stated value
     CtlF  `tcoll_wf`'s second conjunct (`t.\`5 = encode_msgWOTS t.\`4`) deleted
                             RC=1  `not an equation to rewrite` at `rewrite -h5`
                                   in `tcoll_win_needs_coll` -- the recorded-entry
                                   invariant is load-bearing for NO-TRIVIAL-WIN,
                                   i.e. that lemma is not bookkeeping

   A control that COMPILED would mean the corresponding hypothesis is not
   load-bearing and this file's evidence is worthless.  None does.

   NOT CONTROLLED, ON PURPOSE: `P dg'` in the win condition.  It is provably
   redundant (see the faithfulness note above), so a control deleting it would
   compile green and would say nothing.
   ========================================================================== *)
require import AllCore List Distr.
require import SPHINCS_PLUS.
require WOTS_C_Real.
import FSSLXMTWES.WTWES.
import HA.Adrs.
import WOTS_C_Real.
import EmsgWOTS.        (* template import; `val` is shadowed here, so every
                           projection below is qualified by type *)

(* ==========================================================================
   1.  THE TARGET ORACLE.

   One recorded entry per query: (ad, m, ctr, dg, e).  `dg` and `e` are STORED
   rather than recomputed by the game, so the win condition speaks about what
   the oracle actually produced (the paper's set Q), not about a re-derivation.
   ========================================================================== *)
type tcoll_entry = adrs * dgstblock * cntr * msgWOTS * EmsgWOTS.emsgWOTS.

module type Oracle_TCollEnum = {
  proc init(ps_init : pseed) : unit
  proc query(ad : adrs, m : dgstblock) : EmsgWOTS.emsgWOTS * cntr
  proc get(i : int) : tcoll_entry
  proc nr_targets() : int
}.

module O_TCollEnum_Default : Oracle_TCollEnum = {
  var ps : pseed
  var ts : tcoll_entry list

  proc init(ps_init : pseed) : unit = {
    ps <- ps_init;
    ts <- [];
  }

  proc query(ad : adrs, m : dgstblock) : EmsgWOTS.emsgWOTS * cntr = {
    var ctr : cntr;
    var dg : msgWOTS;
    var e : EmsgWOTS.emsgWOTS;

    ctr <- grindC ps ad m;          (* C3-honest side: the DEPLOYED enumeration *)
    dg  <- ThC ps ad m ctr;
    e   <- encode_msgWOTS dg;

    ts <- rcons ts (ad, m, ctr, dg, e);

    return (e, ctr);
  }

  proc get(i : int) : tcoll_entry = {
    return nth witness ts i;
  }

  proc nr_targets() : int = {
    return size ts;
  }
}.

(* ==========================================================================
   2.  THE ADVERSARY.

   `pick` gets BOTH oracles and NO seed (C1); `find` gets the seed and NO
   oracles.  The restriction annotations are the enforcement, and they mirror
   `base-c10-split/WOTS_TW_ES.ec:2610-2611` exactly.
   ========================================================================== *)
module type Adv_TCollResEnum(O : Oracle_TCollEnum, OC : FC.Oracle_THFC) = {
  proc pick() : unit                             { O.query, OC.query }
  proc find(ps : pseed) : int * dgstblock * cntr {}
}.

(* ==========================================================================
   3.  THE GAME.
   ========================================================================== *)
module T_COLL_RES_ENUM(B : Adv_TCollResEnum, O : Oracle_TCollEnum, OC : FC.Oracle_THFC) = {
  module B = B(O, OC)

  proc main() : bool = {
    var ps : pseed;
    var ad : adrs;
    var m, m' : dgstblock;
    var ctr, ctr' : cntr;
    var dg, dg' : msgWOTS;
    var e, e' : EmsgWOTS.emsgWOTS;
    var i, nrts : int;

    ps <$ dpseed;

    (* (C1) BOTH oracles are keyed with the REAL ps BEFORE pick runs.  These two
       lines are the constraint; moving either below `pick`, or keying OC with
       anything else, silently weakens the modelled adversary. *)
    OC.init(ps);
    O.init(ps);

    B.pick();                        (* (C1) may call O.query AND OC.query      *)
    (i, m', ctr') <@ B.find(ps);     (* the seed is revealed only here          *)

    (ad, m, ctr, dg, e) <@ O.get(i);
    nrts <@ O.nr_targets();

    (* (C3) the adversary's OWN counter -- no `ctr' = grindC ps ad m'` demand *)
    dg' <- ThC ps ad m' ctr';
    e'  <- encode_msgWOTS dg';

    return    0 <= i < nrts
           /\ nrts <= p_tgts
           /\ dg <> dg'              (* (C2) digests, NOT messages *)
           /\ P dg /\ P dg'
           /\ e = e';
  }
}.

(* ==========================================================================
   4.  WHAT THE WIN EVENT IS, EXACTLY.

   `win_core_iff` is the one lemma that says what this game is worth.  It shows
   the win core is EXACTLY "the encoder is non-injective on the constant-sum
   surface, between two ThC images at a common tweak" -- residual Q2b -- and no
   more.  Three uses:

     (i)   the redundancy of `P dg'` (see the header note) is proved, not
           asserted;
     (ii)  the four-way conjunction is not self-contradictory, so the game is
           not vacuous FOR A SYNTACTIC REASON;
     (iii) in the other direction: nothing wins this game without a genuine
           encoder collision -- no bookkeeping win exists, and the
           `0 <= i < nrts` conjunct blocks an out-of-range `get` returning
           `witness`.
   ========================================================================== *)
lemma win_core_iff (dg dg' : msgWOTS) :
     (dg <> dg' /\ P dg /\ P dg' /\ encode_msgWOTS dg = encode_msgWOTS dg')
 <=> (dg <> dg' /\ encode_msgWOTS dg = encode_msgWOTS dg' /\ P dg).
proof.
split.
+ by move=> [hne [hP [_ hcol]]].
move=> [hne [hcol hP]]; do ! split => //.
by move: hP; rewrite /P hcol.
qed.

(* `P` reads its argument ONLY through the codeword -- the fact behind (i). *)
lemma P_transfers_across_codeword (dg dg' : msgWOTS) :
  encode_msgWOTS dg = encode_msgWOTS dg' => P dg => P dg'.
proof. by move=> hcol; rewrite /P hcol. qed.

(* The residual the game's non-vacuity reduces to, named so it can be cited.
   NOT axiomatised, NOT proved: it is exactly the deployed-geometry question
   `experiments/tcollres-leg/ThCWidth.ec` addresses. *)
op EncNonInjOnSurface : bool =
  exists (dg dg' : msgWOTS),
    dg <> dg' /\ P dg /\ encode_msgWOTS dg = encode_msgWOTS dg'.

(* Winning entails the residual.  Direction (iii), at the level of the win
   expression: no collision, no win. *)
lemma win_needs_surface_coll (dg dg' : msgWOTS) :
     dg <> dg' /\ P dg /\ P dg' /\ encode_msgWOTS dg = encode_msgWOTS dg'
  => EncNonInjOnSurface.
proof. by move=> [hne [hP [_ hcol]]]; exists dg dg'. qed.

(* ==========================================================================
   5.  NO TRIVIAL WIN -- the game-level version of direction (iii), for an
       ARBITRARY adversary.

   THIS IS THE EVIDENCE THAT THE MOVE FROM THE WOTS-TW LAYER IS NOT COSMETIC.
   At the WOTS-TW layer the BadEnc event was winnable with probability 1 by
   handing over a chosen colliding message pair (`cdrafts-split/BadEncCountermodel.ec`).
   Here that route is closed by TYPING: the win expression compares the digest
   the ORACLE produced against `ThC ps ad m' ctr'`, and neither is adversary
   chosen.  The lemma below turns that observation into a theorem -- ANY win, by
   ANY adversary, entails a genuine encoder collision on the constant-sum
   surface between two `ThC` images at a common (ps, ad).

   It is NOT a bound.  It does not say the win is hard, only that it is not
   free.  Bounding it is the S-TCR(+C)-style work that follows the reduction.

   AND THE CONCLUSION IS NOT AN AMBIENT THEOREM, so the lemma is not vacuously
   informative: `encode_msgWOTS` is a FREE op (`base-c10-split/WOTS_TW_ES.ec:624`) and
   `ThC` is built from the abstract `thfc`, so neither `EncNonInjOnThCSurface`
   nor `EncNonInjOnSurface` is derivable in the ambient theory.  The implication
   `ThCsurface_implies_surface` records the relationship between them.

   The recorded-entry invariant is what makes this true rather than vacuous: the
   win reads the STORED codeword `e`, so the proof needs `e = encode dg` for the
   retrieved entry.  That is `tcoll_wf`, preserved by `query`.
   ========================================================================== *)
(* The conclusion, WITH the ThC structure kept.  This is the whole point of the
   lemma and an earlier draft got it wrong: concluding the structure-free
   `EncNonInjOnSurface` would NOT discriminate this layer from the WOTS-TW layer,
   because `cdrafts-split/BadEncCountermodel.ec`'s free `cm`/`cm'` satisfy that one
   too.  What distinguishes the +C layer is that BOTH colliding messages are
   `ThC` images at a COMMON (ps, ad) -- keyed digests the adversary does not
   choose.  So the existential keeps them. *)
op EncNonInjOnThCSurface : bool =
  exists (ps : pseed) (ad : adrs) (m m' : dgstblock) (ctr ctr' : cntr),
       ThC ps ad m ctr <> ThC ps ad m' ctr'
    /\ P (ThC ps ad m ctr)
    /\ encode_msgWOTS (ThC ps ad m ctr) = encode_msgWOTS (ThC ps ad m' ctr').

lemma ThCsurface_implies_surface : EncNonInjOnThCSurface => EncNonInjOnSurface.
proof.
rewrite /EncNonInjOnThCSurface /EncNonInjOnSurface.
by move=> [ps ad m m' ctr ctr' [hne [hP hcol]]]; exists (ThC ps ad m ctr) (ThC ps ad m' ctr').
qed.

op tcoll_wf (ps : pseed) (t : tcoll_entry) : bool =
  t.`4 = ThC ps t.`1 t.`2 t.`3 /\ t.`5 = encode_msgWOTS t.`4.

lemma query_preserves_wf :
  hoare[O_TCollEnum_Default.query :
             all (tcoll_wf O_TCollEnum_Default.ps) O_TCollEnum_Default.ts
         ==> all (tcoll_wf O_TCollEnum_Default.ps) O_TCollEnum_Default.ts].
proof. by proc; auto => /> &hr h; rewrite -cats1 all_cat /tcoll_wf. qed.

section NoTrivialWin.

(* The memory restriction is the usual one and is REQUIRED, not cosmetic: an
   adversary sharing state with `O_TCollEnum_Default` could plant a
   non-well-formed entry directly and win without a collision.  So the lemma
   below reads "for every adversary that does not write the oracle's own
   globals", which is exactly the class any reduction will produce.  No
   losslessness is assumed -- this is a hoare judgement. *)
declare module B <: Adv_TCollResEnum{-O_TCollEnum_Default, -FC.O_THFC_Default}.

lemma tcoll_win_needs_coll :
  hoare[T_COLL_RES_ENUM(B, O_TCollEnum_Default, FC.O_THFC_Default).main :
          true ==> res => EncNonInjOnThCSurface].
proof.
proc.
inline O_TCollEnum_Default.get O_TCollEnum_Default.nr_targets.
wp.
call (: true).
call (: all (tcoll_wf O_TCollEnum_Default.ps) O_TCollEnum_Default.ts).
+ by conseq query_preserves_wf.
+ by proc; auto.
inline O_TCollEnum_Default.init FC.O_THFC_Default.init.
(* Goal state read off `easycrypt cli` (`experiments/wots-badenc/tcoll/dump.sh`), not guessed: after
   `auto => />` the judgement is a single fully-curried pure formula, so there is
   no `&hr` to introduce and `all (tcoll_wf ps) []` is already discharged. *)
auto => /> ps _ ts hall result h0 h1 hpt hne hP hP' heq.
(* The retrieved entry is well-formed.  BOTH conjuncts are load-bearing: `h4`
   says the stored digest really is a `ThC` image at the stored (ad, m, ctr) --
   which is what lets the conclusion keep its structure -- and `h5` says the
   stored codeword really is that digest's encoding, which is what makes the win
   an encoder collision rather than an oracle-bookkeeping accident. *)
have hwf : tcoll_wf ps (nth witness ts result.`1) by smt(allP mem_nth).
move: hwf; rewrite /tcoll_wf => -[h4 h5].
(* binder order is (ps, ad, m, m', ctr, ctr'), NOT the entry's tuple order *)
exists ps (nth witness ts result.`1).`1 (nth witness ts result.`1).`2
       result.`2 (nth witness ts result.`1).`3 result.`3.
rewrite -h4.
do ! split => //.
by rewrite -h5 heq.
qed.

end section NoTrivialWin.

(* ==========================================================================
   6.  NON-VACUITY: AN EXPLICIT WITNESS ADVERSARY, Pr = 1 UNDER AN EXPLICIT
       COLLISION HYPOTHESIS.

   Style is copied from `cdrafts-split/BadEncCountermodel.ec`: the witness data are
   FREE ops and the collision facts are HYPOTHESES, so the file exhibits no
   collision and asserts none.

   THE HYPOTHESES ARE `forall ps`.  That is the faithful analogue of the
   countermodel's free `cm`/`cm'` (there `encode_msgWOTS` is ps-free; here `ThC`
   is ps-KEYED and `ps` is sampled inside `main`, so a witness that survives the
   sampling must work at every seed).  It is STRICTLY STRONGER than "a collision
   exists at the sampled ps", and neither is established here.
   ========================================================================== *)
op wad   : adrs.
op wm    : dgstblock.
op wm'   : dgstblock.
op wctr' : cntr.

(* the honest (enumerated) digest, and the adversary's *)
op wdg  (ps : pseed) : msgWOTS = ThC ps wad wm (grindC ps wad wm).
op wdg' (ps : pseed) : msgWOTS = ThC ps wad wm' wctr'.

op W_distinct : bool = forall (ps : pseed), wdg ps <> wdg' ps.
op W_collides : bool = forall (ps : pseed), encode_msgWOTS (wdg ps) = encode_msgWOTS (wdg' ps).
op W_gated    : bool = forall (ps : pseed), P (wdg ps).

(* Point instances, unfolded once here so that the game proof consumes each
   hypothesis by `exact` on a PROOF TERM.  This is deliberate control hygiene:
   had the proof instead done `rewrite /W_distinct in hne`, a control replacing
   `W_distinct` by `true` would fail at the REWRITE -- a syntactic failure that
   only shows the script mentions the name.  Failing at `exact` instead shows the
   hypothesis is what CLOSES the goal. *)
lemma W_distinct_at (ps : pseed) :
  W_distinct => ThC ps wad wm (grindC ps wad wm) <> ThC ps wad wm' wctr'.
proof. by rewrite /W_distinct /wdg /wdg' => h; exact (h ps). qed.

lemma W_collides_at (ps : pseed) :
     W_collides
  =>   encode_msgWOTS (ThC ps wad wm (grindC ps wad wm))
     = encode_msgWOTS (ThC ps wad wm' wctr').
proof. by rewrite /W_collides /wdg /wdg' => h; exact (h ps). qed.

lemma W_gated_at (ps : pseed) :
  W_gated => P (ThC ps wad wm (grindC ps wad wm)).
proof. by rewrite /W_gated /wdg => h; exact (h ps). qed.

(* One target query, then point at it.  `OC` is never used -- which is exactly
   why this witness says nothing about (C1): (C1) is about what the adversary
   MAY do, and the game must permit it whether or not this witness needs it. *)
module (B_wit : Adv_TCollResEnum) (O : Oracle_TCollEnum, OC : FC.Oracle_THFC) = {
  proc pick() : unit = {
    var r : EmsgWOTS.emsgWOTS * cntr;
    r <@ O.query(wad, wm);
  }

  proc find(ps : pseed) : int * dgstblock * cntr = {
    return (0, wm', wctr');
  }
}.

(* -- losslessness (every procedure is straight-line; `grindC` is an op) -- *)
lemma o_tcoll_init_ll : islossless O_TCollEnum_Default.init.
proof. by proc; auto. qed.

lemma o_tcoll_query_ll : islossless O_TCollEnum_Default.query.
proof. by proc; auto. qed.

lemma o_tcoll_get_ll : islossless O_TCollEnum_Default.get.
proof. by proc; auto. qed.

lemma o_tcoll_nrt_ll : islossless O_TCollEnum_Default.nr_targets.
proof. by proc; auto. qed.

lemma oc_init_ll : islossless FC.O_THFC_Default.init.
proof. by proc; auto. qed.

lemma bwit_pick_ll : islossless B_wit(O_TCollEnum_Default, FC.O_THFC_Default).pick.
proof. by proc; call o_tcoll_query_ll; auto. qed.

lemma bwit_find_ll : islossless B_wit(O_TCollEnum_Default, FC.O_THFC_Default).find.
proof. by proc; auto. qed.

lemma tcoll_game_ll :
  islossless T_COLL_RES_ENUM(B_wit, O_TCollEnum_Default, FC.O_THFC_Default).main.
proof.
proc.
wp; call o_tcoll_nrt_ll; call o_tcoll_get_ll.
call bwit_find_ll; call bwit_pick_ll.
call o_tcoll_init_ll; call oc_init_ll.
by auto; smt(dpseed_ll).
qed.

(* -- the win holds with certainty under the collision hypothesis -- *)
lemma tcoll_witness_hoare :
     1 <= p_tgts => true => W_distinct => W_collides
  => hoare[T_COLL_RES_ENUM(B_wit, O_TCollEnum_Default, FC.O_THFC_Default).main :
             true ==> res].
proof.
move=> hpt hP hne hcol.
(* `=> />` already consumes `hpt` on the `nrts <= p_tgts` conjunct (the witness
   makes `nrts = 1`), so only the four collision conjuncts remain.  Goal state
   read off `easycrypt cli` (`experiments/wots-badenc/tcoll/dump.sh`), not guessed. *)
proc; inline *; auto => /> ps _.
do ! split.
+ exact (W_distinct_at ps hne).
+ exact (W_gated_at ps hP).
+ by apply (P_transfers_across_codeword (ThC ps wad wm (grindC ps wad wm))
                                        (ThC ps wad wm' wctr')
                                        (W_collides_at ps hcol) (W_gated_at ps hP)).
exact (W_collides_at ps hcol).
qed.

(* -- the packaging step -- *)
lemma tcoll_witness_is_one &m :
     1 <= p_tgts => true => W_distinct => W_collides
  => Pr[T_COLL_RES_ENUM(B_wit, O_TCollEnum_Default, FC.O_THFC_Default).main() @ &m
          : res] = 1%r.
proof.
move=> hpt hP hne hcol.
byphoare => //.
by conseq tcoll_game_ll (tcoll_witness_hoare hpt hP hne hcol).
qed.

(* ==========================================================================
   7.  HOW TO READ SECTION 6, PRECISELY.

   `tcoll_witness_is_one` (section 6) says: IF a ThC-image pair exists that is distinct,
   gated, and codeword-colliding at every seed, THEN the game is winnable with
   probability 1 by a one-query adversary.  So the game is NOT vacuous for a
   structural reason -- its win condition is satisfiable in principle, and the
   only thing standing between it and a real win is the encoder collision
   itself.

   It says NOTHING about whether such a pair exists.  It is not an attack, and
   it is not a bound.  The deployed wallet is unaffected for the same reason
   recorded in `cdrafts-split/BadEncCountermodel.ec`'s header: C10's WOTS layer
   encodes key-determined internal nodes, never an adversary-chosen value.

   The gap that remained when this was written: the reduction
   BadEnc -> T_COLL_RES_ENUM did not exist.  [CORRECTED 2026-09-14: it does now --
   cdrafts-split/BadEncStep4.ec::badenc_le_tcoll.  It MOVES the charge to this
   game; it bounds nothing, and this file on its own still changes no bound.]
   ========================================================================== *)
