(* #########################################################################
   MUST-FAIL NEGATIVE CONTROL -- NOT A RESULT.  DO NOT PROMOTE OR VENDOR.
   Generated by scratch/mkctl_wlc.sh from cdrafts-split/WotsLegCharged.ec.
   A green compile here would mean the deleted premise is NOT load-bearing.
   ######################################################################### *)
(* ==========================================================================
   WotsLegCharged.ec -- THE DEPLOYED WOTS LEG, CHARGED.  Landed 2026-09-01.

   WHAT THIS IS.  `GprocQWired.ec` carries the WOTS-TW game as an OPAQUE SUMMAND
   of its statement.  `wots_leg_charged_at_deployed` (below) replaces that
   summand with the four NAMED terms of `MEUFGCMA_WOTSTWESNPRF_Charged` --
   UD / TCR / PRE / encoding-collision -- AT THE DEPLOYED ADVERSARY
   `R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))`.  Composing it with the
   deployed capstone is then transitivity.

   WHY IT COULD NOT BE WRITTEN BEFORE.  This is step 5 of
   scratch/scope_fextractop_VERDICT.md, which disqualified it in 2026-08 for one
   reason: "wiring `_Unfolded` PROMOTES B INTO THE HEADLINE -- it would make a
   live admit load-bearing.  A regression."  Admit B (`nhchwcoll_hchwpre_msg`) was
   REMOVED on 2026-08-30 and left the taint closure the same day.  The stated
   regression has no addressee, and the verdict's own recommendation stands.

   IT BOUNDS NOTHING.  Four named terms in place of one opaque game is
   ASSUMPTION-SURFACE progress, not a number.  In particular
   `BadEncCountermodel.ec::badenc_is_one` does NOT apply here: that theorem is
   about `A_coll`, and the term below sits at a DIFFERENT composed adversary whose
   value is OPEN.  That is exactly the +C-layer question the tree records as
   unresolved.  Do not read this file as making the deployed bound smaller, and do
   not read it as making its vacuity visible either -- neither is established.

   THE PRICE, STATED RATHER THAN BURIED.  Three things the deployed capstone does
   not carry:
     1. SIX extra module separations on F -- the WOTS-TW internals the charged
        bound needs (`FC_UD`/`FC_TCR`/`FC_PRE` defaults and the three
        Game23/34/4 reductions).  Formally a NARROWING: the theorem applies to
        fewer adversaries.  `GprocQWired.ec` already takes this exact trade twice
        and prices it in its own words -- "the price of replacing an unreduced Q
        with three named hardness advantages".  Same trade, one leg over.
     2. GRIND REACHABILITY: `forall m, is_lossless (dcond dmkey (good_fors m))`.
        `R_top_C`'s CMA oracle draws `mk <$ dcond dmkey (good_fors m)`, and a
        CONDITIONAL distribution is lossless only if its condition is reachable.
        NOTHING in the closure supplies that.  This is the "+C" grind assumption
        made VISIBLE; it is carried as a HYPOTHESIS and deliberately NOT
        axiomatised.  It was always implicitly required by the deployed
        instantiation -- it simply had nowhere to appear, because the deployed
        capstone carries no losslessness premises at all.
     3. Ordinary forger losslessness, which the deployed capstone also lacks.

   STRUCTURE, and why `composed_*_ll` keep A_ht ABSTRACT.  The two obligation
   proofs are XmssmtCC_All.ec:8915-8979's, VERBATIM.  Those scripts open with
   `proc; inline *`, which with an ABSTRACT adversary leaves the `A_ht` call
   standing for a `call` step.  Instantiated at the CONCRETE `R_top_C(F)`,
   `inline *` inlines the adversary too and the expected call is not there.  So
   the obligations are proved generically and instantiated afterwards; that keeps
   the borrowed proofs byte-identical rather than re-derived.

   `rtopc_choose_ll` NEEDS NO ADVERSARY PREMISE.  `R_top_C.choose` never calls the
   forger -- it is a four-deep loop nest over `ddgstblock` and `OC.query`.  Only
   `forge` reaches the adversary, and only there does the grind premise bite.

   CONTROLS: scratch/wlc_ctl{A,B,C}.ec, registered in cert-controls-split.tsv.
   A drops the grind premise, B drops forger losslessness, C drops ONE of the six
   separations from F.  All three MUST fail, and each fails for its own reason.
   ========================================================================== *)
require import AllCore List Distr StdBigop StdOrder IntDiv.
require import SPHINCS_PLUS XmssmtCC_All RtopCSoundness FxChain GprocFORSC10 GprocVI.
require WOTS_C_Real WOTS_C_Scheme XMSSMT_C_Scheme WOTS_C_Interactive.
require FORS_C10 FORS_C10_Multi DigitalSignatures.
require import BitEncoding. import BS2Int BitChunking.
require import SphincsC10CapstoneWired.
require import GprocT1Opre GprocT2Trh GprocT3Trco GprocQBound.
require import C10DeployedInstance C10DeployedCapstone.
(* Same import surface the capstone itself opens (SphincsC10CapstoneWired.ec
   :381-387): the lemma statement below is that file's, so it needs that file's
   unqualified names (R_int_STCRC, FSSLXMTWES.*, EmsgWOTS, ...). *)
import FSSLXMTWES.
import FSSLXMTWES.WTWES.
import WOTS_C_Real.
import WOTS_C_Scheme.
import EmsgWOTS.
import XMSSMT_C_Scheme.
import WOTS_C_Interactive.

lemma rtopc_choose_ll (F <: Adv_EUFCMA_C) (OC <: FSSLXMTWES.TRHC.Oracle_THFC{-R_top_C}) :
  islossless OC.query => islossless R_top_C(F, OC).choose.
proof.
move=> OCll.
proc.
while (true) (nr_trees 0 - size R_top_C.skFORSnt).
+ move=> z.
  wp.
  while (true) (l' - size skFORSlp).
  - move=> z'.
    wp; call OCll; wp.
    while (true) (k - size skFORScube).
    * move=> z''.
      wp.
      while (true) (a - size nodes).
      + move=> z'''.
        wp.
        while (true) (nr_nodesf (size nodes + 1) - size nodescl).
        - move=> z''''.
          by wp; call OCll; wp; skip => />; smt(size_rcons).
        by wp; skip => />; smt(size_rcons).
      wp.
      while (true) (t - size skFORSet).
      + move=> z'''.
        by wp; call OCll; wp; rnd; skip => />; smt(size_rcons ddgstblock_ll).
      by wp; skip => />; smt(size_rcons).
    by wp; skip => />; smt(size_rcons).
  by wp; skip => />; smt(size_rcons).
by wp; skip => /> /#.
qed.

(* helper: the FORS signing procedure is lossless *)
lemma gen_leaves_ll : islossless FTWES.FL_FORS_ES_NPRF.gen_leaves_single_tree.
proof.
islossless.
while (true) (t - size leaves).
+ by move=> z; auto => />; smt(size_rcons).
by auto => /#.
qed.

lemma fors_sign_ll : islossless FTWES.FL_FORS_ES_NPRF.sign.
proof.
islossless.
while (true) (k - size sig).
+ by move=> z; wp; call gen_leaves_ll; auto => />; smt(size_rcons).
by auto => /#.
qed.

(* Obligation 2.  `forge` calls A(O_CMA).forge, so it needs BOTH the adversary's
   losslessness AND the CMA oracle's -- and the oracle draws
   `mk <$ dcond dmkey (good_fors m)`, a CONDITIONAL distribution.  That is a
   GRIND-REACHABILITY side condition; it is carried as an explicit premise
   because nothing in the closure supplies it. *)
lemma rtopc_forge_ll
  (F <: Adv_EUFCMA_C{-R_top_C}) (OC <: FSSLXMTWES.TRHC.Oracle_THFC{-R_top_C, -F}) :
     (forall (m : msg), is_lossless (dcond dmkey (good_fors m)))
  => (forall (O <: SOracle_CMA_C{-F}), islossless O.sign => islossless F(O).forge)
  => islossless R_top_C(F, OC).forge.
proof.
move=> hgrind Fll.
proc.
call pkfromsig_ll.
wp.
have OCMAll : islossless R_top_C(F, OC).O_CMA.sign.
+ proc; wp; call fors_sign_ll; wp; rnd; skip.
  move=> &hr _; split => [|v _ //].
  by have := hgrind m{hr}; rewrite /is_lossless => <-; apply/mu_eq.
call (Fll (<: R_top_C(F, OC).O_CMA) OCMAll).
by auto.
qed.


(* ==========================================================================
   The two losslessness obligations of MEUFGCMA_WOTSTWESNPRF_Charged, proved
   GENERICALLY in A_ht so the proofs are XmssmtCC_All.ec's VERBATIM (with the
   adversary abstract, `inline *` leaves the A_ht call standing, which is what
   those scripts expect).  Instantiating at the concrete R_top_C(F) afterwards
   is then a one-liner.
   ========================================================================== *)
lemma composed_choose_ll
  (A_ht <: Adv_EUFNAGCMA_FLSLXMSSMTTWCESNPRF{ -R_int_STCRC, -R_int_WOTSTW,
             -O_MEUFGCMA_WOTSC_Default, -O_MEUFGCMA_WOTSTWESNPRF,
             -STCRC_WC.O_STCRC_Default, -FC.O_THFC_Default, -O_THFC_MA, -G0_INT,
             -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -EUF_NAGCMA_FLSLXMSSMTTWCESNPRF_C,
             -O_MEUFGCMA_WOTSC_V,
             -R_SMDTTCRCPKCO_C, -R_SMDTTCRCTRH_C,
             -FSSLXMTWES.PKCOC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.PKCOC.O_THFC_Default,
             -FSSLXMTWES.TRHC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.TRHC.O_THFC_Default,
             (* --- ADDED for the unfold: the six WOTS-TW-internal modules that
                    MM45's `MEUFGCMA_WOTSTWESNPRF` requires its adversary to be
                    disjoint from.  A superset restriction is a STRONGER
                    hypothesis on A_ht, so it still discharges everything the
                    component theorem needed. --- *)
             -FC_UD.O_SMDTUD_Default, -FC_TCR.O_SMDTTCR_Default,
             -FC_PRE.O_SMDTPRE_Default, -R_SMDTUDC_Game23WOTSTWES,
             -R_SMDTTCRC_Game34WOTSTWES, -R_SMDTPREC_Game4WOTSTWES }) :
     (forall (OC <: FSSLXMTWES.TRHC.Oracle_THFC{-A_ht}), islossless OC.query => islossless A_ht(OC).choose)
  => forall (O <: Oracle_MEUFGCMA_WOTSTWESNPRF{-A_ht, -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -R_int_WOTSTW}) (OC <: FC.Oracle_THFC{-A_ht, -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -R_int_WOTSTW}),
       islossless O.query => islossless OC.query =>
       islossless R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(A_ht), O, OC).choose.
proof.
move=> A_ht_choose_ll.
move=> O OC Oll OCll.
proc; inline *.
(* `d` (hypertree depth) is SHADOWED inside the inlined `O_wrap.query` by its
   local `d : dgstblock`, so it cannot be named in a while-variant.  Lift it
   into the LOGICAL context first, where no program variable shadows it. *)
pose dd := d.
wp.
while (true) (dd - size R_MEUFGCMAWOTSC_EUFNAGCMA_C.pkWOTStd).
- move=> z.
  wp.
  while (true)
        (nr_trees (size R_MEUFGCMAWOTSC_EUFNAGCMA_C.pkWOTStd) - size pkWOTSnt).
  * move=> z'.
    wp => /=.
    while (true) (h' - size nodes).
    + move=> z''.
      wp => /=.
      while (true) (nr_nodesx (size nodes + 1) - size nodescl).
      - move=> z'''.
        by wp; call OCll; wp; skip => />; smt(size_rcons).
      by wp; skip => />; smt(size_rcons).
    wp => /=.
    while (true) (l' - size pkWOTSlp).
    + move=> z''.
      wp => /=.
      call OCll.
      wp.
      call Oll.
      wp.
      call OCll.
      call OCll.
      while (true) (size cs).
      - move=> z'''.
        by wp; call OCll; call OCll; wp; skip => />; smt(size_behead size_ge0).
      by wp; skip => />; smt(size_rcons size_ge0 size_eq0).
    by wp; skip => />; smt(size_rcons).
  by wp; skip => />; smt(size_rcons).
wp; call (A_ht_choose_ll OC OCll).
by wp; skip => /> /#.
qed.

lemma composed_forge_ll
  (A_ht <: Adv_EUFNAGCMA_FLSLXMSSMTTWCESNPRF{ -R_int_STCRC, -R_int_WOTSTW,
             -O_MEUFGCMA_WOTSC_Default, -O_MEUFGCMA_WOTSTWESNPRF,
             -STCRC_WC.O_STCRC_Default, -FC.O_THFC_Default, -O_THFC_MA, -G0_INT,
             -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -EUF_NAGCMA_FLSLXMSSMTTWCESNPRF_C,
             -O_MEUFGCMA_WOTSC_V,
             -R_SMDTTCRCPKCO_C, -R_SMDTTCRCTRH_C,
             -FSSLXMTWES.PKCOC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.PKCOC.O_THFC_Default,
             -FSSLXMTWES.TRHC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.TRHC.O_THFC_Default,
             (* --- ADDED for the unfold: the six WOTS-TW-internal modules that
                    MM45's `MEUFGCMA_WOTSTWESNPRF` requires its adversary to be
                    disjoint from.  A superset restriction is a STRONGER
                    hypothesis on A_ht, so it still discharges everything the
                    component theorem needed. --- *)
             -FC_UD.O_SMDTUD_Default, -FC_TCR.O_SMDTTCR_Default,
             -FC_PRE.O_SMDTPRE_Default, -R_SMDTUDC_Game23WOTSTWES,
             -R_SMDTTCRC_Game34WOTSTWES, -R_SMDTPREC_Game4WOTSTWES }) :
     (forall (OC <: FSSLXMTWES.TRHC.Oracle_THFC{-A_ht}), islossless A_ht(OC).forge)
  => forall (O <: Oracle_MEUFGCMA_WOTSTWESNPRF{-A_ht, -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -R_int_WOTSTW}) (OC <: FC.Oracle_THFC{-A_ht, -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -R_int_WOTSTW}),
       islossless R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(A_ht), O, OC).forge.
proof.
move=> A_ht_forge_ll.
move=> O OC.
proc; inline *.
pose dd := d.
wp => /=.
while (true) (dd - size pkWOTSs').
+ move=> z.
  wp.
  while (true) (len - size pkWOTS_l).
  - move=> z'.
    by wp; skip => />; smt(size_rcons).
  by wp; skip => />; smt(size_rcons).
wp.
call (A_ht_forge_ll OC).
wp => /=.
while (true) (l - size sigl).
+ move=> z.
  wp.
  while (true) (dd - size sapl).
  - move=> z'.
    by wp; skip => />; smt(size_rcons).
  by wp; skip => />; smt(size_rcons).
by wp; skip => /> /#.
qed.

lemma wots_leg_charged_at_deployed
  (F <: Adv_EUFCMA_C{ -R_int_STCRC, -R_int_WOTSTW,
             -O_MEUFGCMA_WOTSC_Default, -O_MEUFGCMA_WOTSTWESNPRF,
             -STCRC_WC.O_STCRC_Default, -FC.O_THFC_Default, -O_THFC_MA, -G0_INT,
             -R_MEUFGCMAWOTSC_EUFNAGCMA_C, -EUF_NAGCMA_FLSLXMSSMTTWCESNPRF_C,
             -O_MEUFGCMA_WOTSC_V, -R_SMDTTCRCPKCO_C, -R_SMDTTCRCTRH_C,
             -FSSLXMTWES.PKCOC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.PKCOC.O_THFC_Default,
             -FSSLXMTWES.TRHC_TCR.O_SMDTTCR_Default, -FSSLXMTWES.TRHC.O_THFC_Default,
             -R_top, -R_top_C,
             -FC_UD.O_SMDTUD_Default, -FC_TCR.O_SMDTTCR_Default,
             -FC_PRE.O_SMDTPRE_Default,
             -R_SMDTTCRC_Game34WOTSTWES, -R_SMDTPREC_Game4WOTSTWES }) &m :
     (forall (m : msg), is_lossless (dcond dmkey (good_fors m))) =>
     (forall (O <: SOracle_CMA_C{-F}), islossless O.sign => islossless F(O).forge) =>
    Pr[M_EUF_GCMA_WOTSTWESNPRF(R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F))),
                               O_MEUFGCMA_WOTSTWESNPRF, FC.O_THFC_Default).main() @ &m : res]
 <=   (w - 2)%r
      * `|Pr[FC_UD.SM_DT_UD_C(R_SMDTUDC_Game23WOTSTWES(
             R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))),
             FC_UD.O_SMDTUD_Default, FC.O_THFC_Default).main(false) @ &m : res]
          - Pr[FC_UD.SM_DT_UD_C(R_SMDTUDC_Game23WOTSTWES(
             R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))),
             FC_UD.O_SMDTUD_Default, FC.O_THFC_Default).main(true) @ &m : res]|
    + Pr[FC_TCR.SM_DT_TCR_C(R_SMDTTCRC_Game34WOTSTWES(
             R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))),
             FC_TCR.O_SMDTTCR_Default, FC.O_THFC_Default).main() @ &m : res]
    + ( Pr[FC_PRE.SM_DT_PRE_C(R_SMDTPREC_Game4WOTSTWES(
             R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))),
             FC_PRE.O_SMDTPRE_Default, FC.O_THFC_Default).main() @ &m : res]
      + Pr[Game4_WOTSTWES_BadEnc(
             R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))).main() @ &m
             : res /\ BadEncFlag.badenc] ).
proof.
move=> hgrind Fll.
apply (MEUFGCMA_WOTSTWESNPRF_Charged
         (R_int_WOTSTW(R_MEUFGCMAWOTSC_EUFNAGCMA_C(R_top_C(F)))) _ _ &m).
+ by apply (composed_choose_ll (R_top_C(F)) _) => OC' OCpll;
     apply (rtopc_choose_ll F OC' OCpll).
+ by apply (composed_forge_ll (R_top_C(F)) _) => OC';
     apply (rtopc_forge_ll F OC' hgrind Fll).
qed.
