-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.WotsKeygen.Types
import Extracted.WotsKeygen.FunsExternal
import Extracted.PkFromSig.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::wots::keygen_pk]: loop body 0:
    Source: 'sphincs-c10/src/wots.rs', lines 110:4-114:5
    Visibility: public -/
@[rust_loop_body]
def wots.keygen_pk_loop.body
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (kp : Std.U32)
  (base_adrs : Array Std.U8 32#usize) (iter : core.ops.range.Range Std.Usize)
  (pk_elements : Array (Array Std.U8 16#usize) 43#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 43#usize)) (Array (Array Std.U8 16#usize) 43#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done pk_elements)
  | some i =>
    let i1 ← lift (UScalar.cast .U32 i)
    let sk_i ← hash.wots_secret sk_seed layer tree kp i1
    let i2 ← lift (UScalar.cast .U32 i)
    let chain_adrs ← address.set_chain_index base_adrs i2
    let i3 ← params.W - 1#usize
    let i4 ← lift (UScalar.cast .U32 i3)
    let a ← hash.chain_hash seed chain_adrs sk_i 0#u32 i4
    let a1 ← Array.update pk_elements i a
    ok (cont (iter1, a1))

/-- [sphincs_c10::wots::keygen_pk]: loop 0:
    Source: 'sphincs-c10/src/wots.rs', lines 110:4-114:5
    Visibility: public -/
@[rust_loop]
def wots.keygen_pk_loop
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (sk_seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (kp : Std.U32) (base_adrs : Array Std.U8 32#usize)
  (pk_elements : Array (Array Std.U8 16#usize) 43#usize) :
  Result (Array (Array Std.U8 16#usize) 43#usize)
  := do
  loop
    (fun (iter1, pk_elements1) => wots.keygen_pk_loop.body seed sk_seed layer
      tree kp base_adrs iter1 pk_elements1)
    (iter, pk_elements)

/-- [sphincs_c10::wots::keygen_pk]:
    Source: 'sphincs-c10/src/wots.rs', lines 101:0-117:1
    Visibility: public -/
def wots.keygen_pk
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (kp : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let base_adrs ←
    address.make_adrs layer tree params.ADRS_WOTS kp 0#u32 0#u32 0#u32
  let a := Array.repeat 16#usize 0#u8
  let pk_elements := Array.repeat 43#usize a
  let pk_elements1 ←
    wots.keygen_pk_loop { start := 0#usize, «end» := params.L } seed sk_seed
      layer tree kp base_adrs pk_elements
  let pk_adrs ←
    address.make_adrs layer tree params.ADRS_WOTS_PK kp 0#u32 0#u32 0#u32
  let s ← lift (Array.to_slice pk_elements1)
  hash.th_multi seed pk_adrs s

end sphincs_c10
