-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.FindCount.Types
import Extracted.FindCount.FunsExternal
import Extracted.PkFromSig.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::hypertree::report]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 127:0-136:1 -/
def hypertree.report
  (progress : hypertree.ProgressSink) (pct : Std.U8) : Result Unit := do
  ok ()

/-- [sphincs_c10::wots::GRIND_REPORT_EVERY]
    Source: 'sphincs-c10/src/wots.rs', lines 51:0-51:48 -/
@[global_simps, irreducible] def wots.GRIND_REPORT_EVERY : Std.U32 := 4096#u32

/-- [sphincs_c10::wots::find_count]: loop body 1:
    Source: 'sphincs-c10/src/wots.rs', lines 79:8-81:9 -/
@[rust_loop_body]
def wots.find_count_loop0_loop0.body
  (digits : Array Std.U8 43#usize) (iter : core.ops.range.Range Std.Usize)
  (sum : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize)
    Std.Usize)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done sum)
  | some i =>
    let i1 ← Array.index_usize digits i
    let i2 ← lift (UScalar.cast .Usize i1)
    let sum1 ← sum + i2
    ok (cont (iter1, sum1))

/-- [sphincs_c10::wots::find_count]: loop 1:
    Source: 'sphincs-c10/src/wots.rs', lines 79:8-81:9 -/
@[rust_loop]
def wots.find_count_loop0_loop0
  (iter : core.ops.range.Range Std.Usize) (digits : Array Std.U8 43#usize)
  (sum : Std.Usize) :
  Result Std.Usize
  := do
  loop
    (fun (iter1, sum1) => wots.find_count_loop0_loop0.body digits iter1 sum1)
    (iter, sum)

/-- [sphincs_c10::wots::find_count]: loop body 0:
    Source: 'sphincs-c10/src/wots.rs', lines 74:4-94:1 -/
@[rust_loop_body]
def wots.find_count_loop0.body
  (seed : Array Std.U8 32#usize) (msg_hash : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (pct : Std.U8)
  (wots_adrs : Array Std.U8 32#usize) (count : Std.U32) :
  Result (ControlFlow Std.U32 (Std.U32 × (Array Std.U8 32#usize) × (Array
    Std.U8 43#usize)))
  := do
  massert (count < 10000000#u32)
  let d ← hash.wots_digest seed wots_adrs msg_hash count
  let digits ← wots.extract_digits d
  let sum ←
    wots.find_count_loop0_loop0 { start := 0#usize, «end» := params.L }
      digits 0#usize
  if sum = params.TARGET_SUM
  then ok (done (count, d, digits))
  else
    let i ← count % wots.GRIND_REPORT_EVERY
    let i1 ← wots.GRIND_REPORT_EVERY - 1#u32
    if i = i1
    then hypertree.report progress pct
    else ok ()
    let count1 ← count + 1#u32
    ok (cont count1)

/-- [sphincs_c10::wots::find_count]: loop 0:
    Source: 'sphincs-c10/src/wots.rs', lines 74:4-94:1 -/
@[rust_loop]
def wots.find_count_loop0
  (seed : Array Std.U8 32#usize) (msg_hash : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (pct : Std.U8)
  (wots_adrs : Array Std.U8 32#usize) (count : Std.U32) :
  Result (Std.U32 × (Array Std.U8 32#usize) × (Array Std.U8 43#usize))
  := do
  loop
    (fun count1 => wots.find_count_loop0.body seed msg_hash progress pct
      wots_adrs count1)
    count

/-- [sphincs_c10::wots::find_count]:
    Source: 'sphincs-c10/src/wots.rs', lines 63:0-94:1 -/
def wots.find_count
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (kp : Std.U32) (msg_hash : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (pct : Std.U8) :
  Result (Std.U32 × (Array Std.U8 32#usize) × (Array Std.U8 43#usize))
  := do
  let wots_adrs ←
    address.make_adrs layer tree params.ADRS_WOTS kp 0#u32 0#u32 0#u32
  wots.find_count_loop0 seed msg_hash progress pct wots_adrs 0#u32

end sphincs_c10
