-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.SignForest.Types
import Extracted.SignForest.FunsExternal
import Extracted.Verify.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- Trait implementation: [core::array::equality::{impl core::cmp::PartialEq<[U; N]> for [T; N]}]
    Source: '/rustc/library/core/src/array/equality.rs', lines 5:0-7:28
    Name pattern: [core::cmp::PartialEq<[@T; @N], [@U; @N]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T; @N], [@U; @N]>"]
def Array.Insts.CoreCmpPartialEqArray {T : Type} {U : Type} (N : Std.Usize)
  (cmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (Array T N)
  (Array U N) := {
  eq := core.array.equality.PartialEqArray.eq cmpPartialEqInst
}

/-- [sphincs_c10::hypertree::write16]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 145:0-147:1 -/
def hypertree.write16
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (block : Array Std.U8 16#usize) :
  Result (Array Std.U8 4008#usize)
  := do
  let i ← offset + params.N
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
      { start := offset, «end» := i }
  let s1 ← lift (Array.to_slice block)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [sphincs_c10::hypertree::set_row]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 157:0-159:1 -/
def hypertree.set_row
  (rows : Array (Array Std.U8 16#usize) 13#usize) (i : Std.Usize)
  (v : Array Std.U8 16#usize) :
  Result (Array (Array Std.U8 16#usize) 13#usize)
  := do
  Array.update rows i v

/-- [sphincs_c10::hypertree::sign_inner]: loop body 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 216:4-234:5 -/
@[rust_loop_body]
def hypertree.sign_inner_loop0.body
  (sk_seed : Array Std.U8 32#usize) (progress : hypertree.ProgressSink)
  (seed : Array Std.U8 32#usize) (fors_indices : Array Std.U32 13#usize)
  (ht_idx : Std.U32) (fors_order : Array Std.U8 64#usize)
  (iter : core.ops.range.Range Std.Usize)
  (fors_roots : Array (Array Std.U8 16#usize) 13#usize)
  (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 13#usize) × (Array (Array Std.U8 16#usize) 13#usize) × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)) ((Array (Array Std.U8
    16#usize) 13#usize) × (Array (Array Std.U8 16#usize) 13#usize) × (Array
    (Array (Array Std.U8 16#usize) 11#usize) 12#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (fors_roots, fors_secrets, fors_auth_paths))
  | some step =>
    let i ← Array.index_usize fors_order step
    let t ← lift (UScalar.cast .Usize i)
    let i1 ← lift (UScalar.cast .U32 t)
    let i2 ← Array.index_usize fors_indices t
    let (secret, auth_path) ← fors.sign_fors_tree seed sk_seed ht_idx i1 i2
    let a ← Array.update fors_secrets t secret
    let a1 ← Array.update fors_auth_paths t auth_path
    let i3 ← lift (UScalar.cast .U32 t)
    let a2 ←
      hypertree.reconstruct_fors_root seed ht_idx i3 i2 secret auth_path
    let a3 ← Array.update fors_roots t a2
    let i4 ← lift (UScalar.cast .U32 step)
    let i5 ← i4 + 1#u32
    let i6 ← i5 * 25#u32
    let i7 ← lift (UScalar.cast .U32 params.K)
    let i8 ← i7 - 1#u32
    let i9 ← i6 / i8
    let i10 ← 5#u32 + i9
    let i11 ← lift (UScalar.cast .U8 i10)
    hypertree.report progress i11
    ok (cont (iter1, a3, a, a1))

/-- [sphincs_c10::hypertree::sign_inner]: loop 0:
    Source: 'sphincs-c10/src/hypertree.rs', lines 216:4-234:5 -/
@[rust_loop]
def hypertree.sign_inner_loop0
  (iter : core.ops.range.Range Std.Usize) (sk_seed : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (seed : Array Std.U8 32#usize)
  (fors_indices : Array Std.U32 13#usize) (ht_idx : Std.U32)
  (fors_roots : Array (Array Std.U8 16#usize) 13#usize)
  (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (fors_order : Array Std.U8 64#usize) :
  Result ((Array (Array Std.U8 16#usize) 13#usize) × (Array (Array Std.U8
    16#usize) 13#usize) × (Array (Array (Array Std.U8 16#usize) 11#usize)
    12#usize))
  := do
  loop
    (fun (iter1, fors_roots1, fors_secrets1, fors_auth_paths1) =>
      hypertree.sign_inner_loop0.body sk_seed progress seed fors_indices ht_idx
      fors_order iter1 fors_roots1 fors_secrets1 fors_auth_paths1)
    (iter, fors_roots, fors_secrets, fors_auth_paths)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 1:
    Source: 'sphincs-c10/src/hypertree.rs', lines 249:4-254:5 -/
@[rust_loop_body]
def hypertree.sign_inner_loop1.body
  (fors_secrets : Array (Array Std.U8 16#usize) 13#usize)
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize) (t : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 4008#usize) × Std.Usize × Std.Usize)
    ((Array Std.U8 4008#usize) × Std.Usize))
  := do
  if t < params.K
  then
    let row ← Array.index_usize fors_secrets t
    let sig1 ← hypertree.write16 sig offset row
    let offset1 ← offset + params.N
    let t1 ← t + 1#usize
    ok (cont (sig1, offset1, t1))
  else ok (done (sig, offset))

/-- [sphincs_c10::hypertree::sign_inner]: loop 1:
    Source: 'sphincs-c10/src/hypertree.rs', lines 249:4-254:5 -/
@[rust_loop]
def hypertree.sign_inner_loop1
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (fors_secrets : Array (Array Std.U8 16#usize) 13#usize) (t : Std.Usize) :
  Result ((Array Std.U8 4008#usize) × Std.Usize)
  := do
  loop
    (fun (sig1, offset1, t1) => hypertree.sign_inner_loop1.body fors_secrets
      sig1 offset1 t1)
    (sig, offset, t)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 3:
    Source: 'sphincs-c10/src/hypertree.rs', lines 263:8-268:9 -/
@[rust_loop_body]
def hypertree.sign_inner_loop2_loop0.body
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (t : Std.Usize) (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (h : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 4008#usize) × Std.Usize × Std.Usize)
    ((Array Std.U8 4008#usize) × Std.Usize))
  := do
  if h < params.A
  then
    let a ← Array.index_usize fors_auth_paths t
    let row ← Array.index_usize a h
    let sig1 ← hypertree.write16 sig offset row
    let offset1 ← offset + params.N
    let h1 ← h + 1#usize
    ok (cont (sig1, offset1, h1))
  else ok (done (sig, offset))

/-- [sphincs_c10::hypertree::sign_inner]: loop 3:
    Source: 'sphincs-c10/src/hypertree.rs', lines 263:8-268:9 -/
@[rust_loop]
def hypertree.sign_inner_loop2_loop0
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (t : Std.Usize) (h : Std.Usize) :
  Result ((Array Std.U8 4008#usize) × Std.Usize)
  := do
  loop
    (fun (sig1, offset1, h1) => hypertree.sign_inner_loop2_loop0.body
      fors_auth_paths t sig1 offset1 h1)
    (sig, offset, h)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 2:
    Source: 'sphincs-c10/src/hypertree.rs', lines 261:4-270:5 -/
@[rust_loop_body]
def hypertree.sign_inner_loop2.body
  (i : Std.Usize)
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize) (t : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 4008#usize) × Std.Usize × Std.Usize)
    ((Array Std.U8 4008#usize) × Std.Usize))
  := do
  if t < i
  then
    let (sig1, offset1) ←
      hypertree.sign_inner_loop2_loop0 sig offset fors_auth_paths t 0#usize
    let t1 ← t + 1#usize
    ok (cont (sig1, offset1, t1))
  else ok (done (sig, offset))

/-- [sphincs_c10::hypertree::sign_inner]: loop 2:
    Source: 'sphincs-c10/src/hypertree.rs', lines 261:4-270:5 -/
@[rust_loop]
def hypertree.sign_inner_loop2
  (i : Std.Usize) (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (fors_auth_paths : Array (Array (Array Std.U8 16#usize) 11#usize) 12#usize)
  (t : Std.Usize) :
  Result ((Array Std.U8 4008#usize) × Std.Usize)
  := do
  loop
    (fun (sig1, offset1, t1) => hypertree.sign_inner_loop2.body i
      fors_auth_paths sig1 offset1 t1)
    (sig, offset, t)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 5:
    Source: 'sphincs-c10/src/hypertree.rs', lines 316:8-321:9 -/
@[rust_loop_body]
def hypertree.sign_inner_loop3_loop0.body
  (wots_sigma : Array (Array Std.U8 16#usize) 43#usize)
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 4008#usize) × Std.Usize × Std.Usize)
    ((Array Std.U8 4008#usize) × Std.Usize))
  := do
  if i < params.L
  then
    let row ← Array.index_usize wots_sigma i
    let sig1 ← hypertree.write16 sig offset row
    let offset1 ← offset + params.N
    let i1 ← i + 1#usize
    ok (cont (sig1, offset1, i1))
  else ok (done (sig, offset))

/-- [sphincs_c10::hypertree::sign_inner]: loop 5:
    Source: 'sphincs-c10/src/hypertree.rs', lines 316:8-321:9 -/
@[rust_loop]
def hypertree.sign_inner_loop3_loop0
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (wots_sigma : Array (Array Std.U8 16#usize) 43#usize) (i : Std.Usize) :
  Result ((Array Std.U8 4008#usize) × Std.Usize)
  := do
  loop
    (fun (sig1, offset1, i1) => hypertree.sign_inner_loop3_loop0.body
      wots_sigma sig1 offset1 i1)
    (sig, offset, i)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 6:
    Source: 'sphincs-c10/src/hypertree.rs', lines 329:8-334:9 -/
@[rust_loop_body]
def hypertree.sign_inner_loop3_loop1.body
  (i : Std.Usize) (auth_path : Array (Array Std.U8 16#usize) 9#usize)
  (sig : Array Std.U8 4008#usize) (offset : Std.Usize) (h : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 4008#usize) × Std.Usize × Std.Usize)
    ((Array Std.U8 4008#usize) × Std.Usize))
  := do
  if h < i
  then
    let row ← Array.index_usize auth_path h
    let sig1 ← hypertree.write16 sig offset row
    let offset1 ← offset + params.N
    let h1 ← h + 1#usize
    ok (cont (sig1, offset1, h1))
  else ok (done (sig, offset))

/-- [sphincs_c10::hypertree::sign_inner]: loop 6:
    Source: 'sphincs-c10/src/hypertree.rs', lines 329:8-334:9 -/
@[rust_loop]
def hypertree.sign_inner_loop3_loop1
  (i : Std.Usize) (sig : Array Std.U8 4008#usize) (offset : Std.Usize)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize) (h : Std.Usize) :
  Result ((Array Std.U8 4008#usize) × Std.Usize)
  := do
  loop
    (fun (sig1, offset1, h1) => hypertree.sign_inner_loop3_loop1.body i
      auth_path sig1 offset1 h1)
    (sig, offset, h)

/-- [sphincs_c10::hypertree::sign_inner]: loop body 4:
    Source: 'sphincs-c10/src/hypertree.rs', lines 281:4-354:5 -/
@[rust_loop_body]
def hypertree.sign_inner_loop3.body
  (sk_seed : Array Std.U8 32#usize) (progress : hypertree.ProgressSink)
  (shuffle : shuffle.ShuffleSeed) (seed : Array Std.U8 32#usize)
  (iter : core.ops.range.Range Std.U32) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize) (current_node : Array Std.U8 16#usize)
  (idx_tree : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × (Array Std.U8
    4008#usize) × Std.Usize × (Array Std.U8 16#usize) × Std.U32) ((Array
    Std.U8 4008#usize) × Std.Usize × (Array Std.U8 16#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next U32.Insts.CoreIterRangeStep iter
  match o with
  | none => ok (done (sig, offset, current_node))
  | some layer =>
    let i ← params.SUBTREE_H
    let i1 ← 1#u32 <<< i
    let i2 ← i1 - 1#u32
    let idx_leaf ← lift (idx_tree &&& i2)
    let idx_tree1 ← idx_tree >>> i
    let i3 ← layer * 33#u32
    let i4 ← 32#u32 + i3
    let pct_lo ← lift (UScalar.cast .U8 i4)
    let i5 ← layer + 1#u32
    let i6 ← i5 * 33#u32
    let i7 ← 32#u32 + i6
    let pct_hi ← lift (UScalar.cast .U8 i7)
    let i8 ← lift (UScalar.cast .U64 idx_tree1)
    let (auth_path, _) ←
      merkle.build_subtree_with_auth seed sk_seed layer i8 idx_leaf progress
        pct_lo pct_hi
    hypertree.report progress pct_hi
    let wots_label ←
      match layer with
      | 0#uscalar =>
        ok
          (Array.make 7#usize [
             119#u8, 111#u8, 116#u8, 115#u8, 45#u8, 48#u8, 0#u8
             ] : Array Std.U8 7#usize)
      | _ =>
        ok
          (Array.make 7#usize [
             119#u8, 111#u8, 116#u8, 115#u8, 45#u8, 49#u8, 0#u8
             ] : Array Std.U8 7#usize)
    let s ← lift (Array.to_slice wots_label)
    let wots_shuffle_seed ← sphincs_c10.shuffle.ShuffleSeed.derive shuffle s
    let i9 ← lift (UScalar.cast .U64 idx_tree1)
    let (wots_sigma, count) ←
      wots.sign_with_shuffle seed sk_seed layer i9 idx_leaf current_node
        wots_shuffle_seed progress pct_hi
    let (sig1, offset1) ←
      hypertree.sign_inner_loop3_loop0 sig offset wots_sigma 0#usize
    let i10 ← offset1 + 4#usize
    let (s1, index_mut_back) ←
      core.array.Array.index_mut (core.ops.index.IndexMutSlice
        (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig1
        { start := offset1, «end» := i10 }
    let a ← lift (core.num.U32.to_be_bytes count)
    let s2 ← lift (Array.to_slice a)
    let s3 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s1 s2
    let sig2 := index_mut_back s3
    let (sig3, offset2) ←
      hypertree.sign_inner_loop3_loop1 i sig2 i10 auth_path 0#usize
    let i11 ← lift (UScalar.cast .U64 idx_tree1)
    let wots_pk ←
      wots.pk_from_sig seed layer i11 idx_leaf current_node wots_sigma count
    let i12 ← lift (UScalar.cast .U64 idx_tree1)
    let current_node1 ←
      merkle.verify_auth_path seed layer i12 wots_pk idx_leaf auth_path
    ok (cont (iter1, sig3, offset2, current_node1, idx_tree1))

/-- [sphincs_c10::hypertree::sign_inner]: loop 4:
    Source: 'sphincs-c10/src/hypertree.rs', lines 281:4-354:5 -/
@[rust_loop]
def hypertree.sign_inner_loop3
  (iter : core.ops.range.Range Std.U32) (sk_seed : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (shuffle : shuffle.ShuffleSeed)
  (seed : Array Std.U8 32#usize) (sig : Array Std.U8 4008#usize)
  (offset : Std.Usize) (current_node : Array Std.U8 16#usize)
  (idx_tree : Std.U32) :
  Result ((Array Std.U8 4008#usize) × Std.Usize × (Array Std.U8 16#usize))
  := do
  loop
    (fun (iter1, sig1, offset1, current_node1, idx_tree1) =>
      hypertree.sign_inner_loop3.body sk_seed progress shuffle seed iter1 sig1
      offset1 current_node1 idx_tree1)
    (iter, sig, offset, current_node, idx_tree)

/-- [sphincs_c10::hypertree::sign_inner]:
    Source: 'sphincs-c10/src/hypertree.rs', lines 161:0-366:1 -/
def hypertree.sign_inner
  (sk_seed : Array Std.U8 32#usize) (pk_seed : Array Std.U8 16#usize)
  (pk_root : Array Std.U8 16#usize) (msg_hash : Array Std.U8 32#usize)
  (opt_rand : Option (Array Std.U8 16#usize))
  (progress : hypertree.ProgressSink) (shuffle : shuffle.ShuffleSeed) :
  Result (Array Std.U8 4008#usize)
  := do
  let seed ← hash.pad16 pk_seed
  let sig := Array.repeat 4008#usize 0#u8
  hypertree.report progress 0#u8
  let (r, digest) ← fors.grind_r sk_seed pk_seed pk_root msg_hash opt_rand
  let i ← 0#usize + params.N
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) sig
      { start := 0#usize, «end» := i }
  let s1 ← lift (Array.to_slice r)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let fors_indices ← fors.extract_fors_indices digest
  let ht_idx ← fors.extract_ht_index digest
  let i1 ← params.K - 1#usize
  let left_val ← Array.index_usize fors_indices i1
  if left_val = 0#u32
  then
    hypertree.report progress 5#u8
    let a := Array.repeat 16#usize 0#u8
    let fors_roots := Array.repeat 13#usize a
    let a1 := Array.repeat 16#usize 0#u8
    let fors_secrets := Array.repeat 13#usize a1
    let a2 := Array.repeat 16#usize 0#u8
    let a3 := Array.repeat 11#usize a2
    let fors_auth_paths := Array.repeat 12#usize a3
    let s3 ←
      lift (Array.to_slice
        (Array.make 4#usize [ 102#u8, 111#u8, 114#u8, 115#u8 ]))
    let fors_shuffle_seed ← sphincs_c10.shuffle.ShuffleSeed.derive shuffle s3
    let fors_order ← sphincs_c10.shuffle.fisher_yates fors_shuffle_seed i1
    let sig1 := index_mut_back s2
    let (fors_roots1, fors_secrets1, fors_auth_paths1) ←
      hypertree.sign_inner_loop0 { start := 0#usize, «end» := i1 } sk_seed
        progress seed fors_indices ht_idx fors_roots fors_secrets
        fors_auth_paths fors_order
    let i2 ← lift (UScalar.cast .U32 i1)
    let last_root ← fors.compute_fors_root seed sk_seed ht_idx i2
    let fors_secrets2 ← hypertree.set_row fors_secrets1 i1 last_root
    let i3 ← lift (core.convert.num.FromU64U32.from ht_idx)
    let i4 ← lift (UScalar.cast .U32 i1)
    let last_leaf_adrs ←
      address.make_adrs 0#u32 i3 params.ADRS_FORS_TREE i4 0#u32 0#u32 0#u32
    let a4 ← hash.pad16 last_root
    let a5 ← hash.th seed last_leaf_adrs a4
    let fors_roots2 ← hypertree.set_row fors_roots1 i1 a5
    hypertree.report progress 32#u8
    let (sig2, offset) ←
      hypertree.sign_inner_loop1 sig1 i fors_secrets2 0#usize
    let (sig3, offset1) ←
      hypertree.sign_inner_loop2 i1 sig2 offset fors_auth_paths1 0#usize
    let right_val ← params.SIG_FORS_TOTAL
    massert (offset1 = right_val)
    let fors_pk ← fors.compute_fors_pk seed ht_idx fors_roots2
    let i5 ← lift (UScalar.cast .U32 params.D)
    let (sig4, offset2, current_node) ←
      hypertree.sign_inner_loop3 { start := 0#u32, «end» := i5 } sk_seed
        progress shuffle seed sig3 offset1 fors_pk ht_idx
    hypertree.report progress 100#u8
    let right_val1 ← params.SIGNATURE_LEN
    massert (offset2 = right_val1)
    let b ←
      core.array.equality.PartialEqArray.eq core.cmp.PartialEqU8 current_node
        pk_root
    if b
    then ok sig4
    else
      let _ ←
        core.fmt.Arguments.from_str (toStr
          "Signing self-verification failed: root mismatch" (by (conv_lhs => rw [← String.ofList_toList (s := "Signing self-verification failed: root mismatch"), String.toByteArray_ofList]); simp only [List.utf8Encode, List.size_toByteArray]; simp [String.utf8EncodeChar]; scalar_tac))
      fail panic
  else
    let _ ←
      core.fmt.Arguments.from_str (toStr
        "Last FORS index must be 0 after R-grinding" (by (conv_lhs => rw [← String.ofList_toList (s := "Last FORS index must be 0 after R-grinding"), String.toByteArray_ofList]); simp only [List.utf8Encode, List.size_toByteArray]; simp [String.utf8EncodeChar]; scalar_tac))
    fail panic

end sphincs_c10
