-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: type definitions
import Aeneas
import Extracted.FindCount.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sphincs_c10

/-- [sphincs_c10::shuffle::ShuffleSeed]
    Source: 'sphincs-c10/src/shuffle.rs', lines 42:0-42:37
    Visibility: public -/
@[reducible]
def shuffle.ShuffleSeed := Array Std.U8 32#usize

end sphincs_c10
