-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.WotsSecret.Types
import Extracted.WotsSecret.FunsExternal
import Extracted.Hash.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::hash::u64_to_b32]:
    Source: 'sphincs-c10/src/hash.rs', lines 178:0-182:1 -/
def hash.u64_to_b32 (v : Std.U64) : Result (Array Std.U8 32#usize) := do
  let out := Array.repeat 32#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) out
      { start := 24#usize, «end» := 32#usize }
  let a ← lift (core.num.U64.to_be_bytes v)
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [sphincs_c10::hash::wots_secret]:
    Source: 'sphincs-c10/src/hash.rs', lines 378:0-395:1
    Visibility: public -/
def hash.wots_secret
  (sk_seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (kp : Std.U32) (chain_idx : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let tree_b32 ← hash.u64_to_b32 tree
  let s ← lift (Array.to_slice sk_seed)
  let s1 ←
    lift (Array.to_slice
      (Array.make 4#usize [ 119#u8, 111#u8, 116#u8, 115#u8 ]))
  let a ← lift (core.num.U32.to_be_bytes layer)
  let s2 ← lift (Array.to_slice a)
  let s3 ← lift (Array.to_slice tree_b32)
  let a1 ← lift (core.num.U32.to_be_bytes kp)
  let s4 ← lift (Array.to_slice a1)
  let a2 ← lift (core.num.U32.to_be_bytes chain_idx)
  let s5 ← lift (Array.to_slice a2)
  let s6 ←
    lift (Array.to_slice (Array.make 6#usize [ s, s1, s2, s3, s4, s5 ]))
  let a3 ← hash.sha256_parts s6
  hash.truncate a3

end sphincs_c10
