-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.GrindR.Types
import Extracted.GrindR.FunsExternal
import Extracted.Fors.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::fors::grind_r]: loop body 0:
    Source: 'sphincs-c10/src/fors.rs', lines 110:4-131:1
    Visibility: public -/
@[rust_loop_body]
def fors.grind_r_loop.body
  (sk_seed : Array Std.U8 32#usize) (message : Array Std.U8 32#usize)
  (opt_rand : Option (Array Std.U8 16#usize))
  (seed_b32 : Array Std.U8 32#usize) (root_b32 : Array Std.U8 32#usize)
  (last_shift : Std.Usize) (nonce : Std.U32) :
  Result (ControlFlow Std.U32 ((Array Std.U8 16#usize) × (Array Std.U8
    32#usize)))
  := do
  massert (nonce < 10000000#u32)
  let nonce_b32 := Array.repeat 32#usize 0#u8
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) nonce_b32
      { start := 28#usize, «end» := 32#usize }
  let a ← lift (core.num.U32.to_be_bytes nonce)
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  let r_full ←
    match opt_rand with
    | none =>
      do
      let s3 ← lift (Array.to_slice sk_seed)
      let s4 ←
        lift (Array.to_slice
          (Array.make 7#usize [
            82#u8, 95#u8, 103#u8, 114#u8, 105#u8, 110#u8, 100#u8
            ]))
      let s5 ← lift (Array.to_slice message)
      let nonce_b321 := index_mut_back s2
      let s6 ← lift (Array.to_slice nonce_b321)
      let s7 ← lift (Array.to_slice (Array.make 4#usize [ s3, s4, s5, s6 ]))
      hash.sha256_parts s7
    | some rand =>
      do
      let s3 ← lift (Array.to_slice sk_seed)
      let s4 ←
        lift (Array.to_slice
          (Array.make 7#usize [
            82#u8, 95#u8, 103#u8, 114#u8, 105#u8, 110#u8, 100#u8
            ]))
      let s5 ← lift (Array.to_slice rand)
      let s6 ← lift (Array.to_slice message)
      let nonce_b321 := index_mut_back s2
      let s7 ← lift (Array.to_slice nonce_b321)
      let s8 ←
        lift (Array.to_slice (Array.make 5#usize [ s3, s4, s5, s6, s7 ]))
      hash.sha256_parts s8
  let r ← hash.truncate r_full
  let r_b32 ← hash.pad16 r
  let digest ← hash.h_msg seed_b32 root_b32 r_b32 message
  let i ← fors.read_bits_le digest last_shift params.A
  if i = 0#u64
  then ok (done (r, digest))
  else let nonce1 ← nonce + 1#u32
       ok (cont nonce1)

/-- [sphincs_c10::fors::grind_r]: loop 0:
    Source: 'sphincs-c10/src/fors.rs', lines 110:4-131:1
    Visibility: public -/
@[rust_loop]
def fors.grind_r_loop
  (sk_seed : Array Std.U8 32#usize) (message : Array Std.U8 32#usize)
  (opt_rand : Option (Array Std.U8 16#usize))
  (seed_b32 : Array Std.U8 32#usize) (root_b32 : Array Std.U8 32#usize)
  (last_shift : Std.Usize) (nonce : Std.U32) :
  Result ((Array Std.U8 16#usize) × (Array Std.U8 32#usize))
  := do
  loop
    (fun nonce1 => fors.grind_r_loop.body sk_seed message opt_rand seed_b32
      root_b32 last_shift nonce1)
    nonce

/-- [sphincs_c10::fors::grind_r]:
    Source: 'sphincs-c10/src/fors.rs', lines 98:0-131:1
    Visibility: public -/
def fors.grind_r
  (sk_seed : Array Std.U8 32#usize) (pk_seed : Array Std.U8 16#usize)
  (pk_root : Array Std.U8 16#usize) (message : Array Std.U8 32#usize)
  (opt_rand : Option (Array Std.U8 16#usize)) :
  Result ((Array Std.U8 16#usize) × (Array Std.U8 32#usize))
  := do
  let seed_b32 ← hash.pad16 pk_seed
  let root_b32 ← hash.pad16 pk_root
  let i ← params.K - 1#usize
  let last_shift ← i * params.A
  fors.grind_r_loop sk_seed message opt_rand seed_b32 root_b32 last_shift 0#u32

end sphincs_c10
