//! Build script for the first-stage bootloader.
//!
//! Does two things:
//!
//! 1. Places `memory-stm32u585.x` where cortex-m-rt's `link.x` can find
//!    it (copies to OUT_DIR and adds OUT_DIR to the linker search path).
//!    The FSBL only ever builds for `thumbv8m.main-none-eabi`; there is
//!    no host-side smoke test for it because the full bring-up sequence
//!    only makes sense on real hardware.
//!
//! 2. Embeds the vendor SPHINCS+C10 public key from the path in the
//!    `FSBL_VENDOR_PUBKEY` environment variable into a generated
//!    `vendor_pubkey_bytes.rs` source file. Release builds MUST set
//!    this env var; if it's unset we fall back to a committed
//!    development pubkey at `fixtures/dev_pubkey.bin` (non-secret; the
//!    matching vendor SK is the one used by integration tests). The
//!    FSBL at boot time rejects a release signed by a different key
//!    than its compiled-in pubkey, so dev FSBLs cannot run
//!    production-signed firmware and vice versa — which is the
//!    intended safety property.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let target = env::var("TARGET").unwrap_or_default();
    if !target.contains("thumbv") {
        // Host build (cargo check only) — skip linker-script setup.
        return;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- Linker script -------------------------------------------------------
    fs::copy("memory-stm32u585.x", out_dir.join("memory.x"))
        .expect("copying memory-stm32u585.x");
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rerun-if-changed=memory-stm32u585.x");
    println!("cargo:rerun-if-changed=build.rs");

    // --- Vendor pubkey embedding --------------------------------------------
    //
    // Production: FSBL_VENDOR_PUBKEY points at a 32-byte file produced by
    // `fwsign pubkey`. This is the file that will be burned into every
    // production FSBL image; changing it changes the set of releases the
    // device will accept.
    //
    // Dev: if FSBL_VENDOR_PUBKEY is unset, we regenerate a fixed-seed
    // development pubkey on the fly using sphincs-c10. The seed below is
    // the same one used by fwsign's integration tests (sign_verify_roundtrip),
    // so dev FSBLs and dev-signed .pqfw bundles verify against each other.
    println!("cargo:rerun-if-env-changed=FSBL_VENDOR_PUBKEY");

    let (pk_seed, pk_root, source_desc): ([u8; 16], [u8; 16], String) =
        if let Ok(path) = env::var("FSBL_VENDOR_PUBKEY") {
            println!("cargo:rerun-if-changed={path}");
            let bytes = fs::read(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
            if bytes.len() != 32 {
                panic!(
                    "{path}: expected 32 bytes (pk_seed[16] || pk_root[16]), got {}",
                    bytes.len()
                );
            }
            let mut s = [0u8; 16];
            let mut r = [0u8; 16];
            s.copy_from_slice(&bytes[..16]);
            r.copy_from_slice(&bytes[16..]);
            (s, r, format!("FSBL_VENDOR_PUBKEY={path}"))
        } else {
            println!("cargo:warning=FSBL_VENDOR_PUBKEY unset — using built-in dev fixture key. DO NOT USE FOR PRODUCTION.");
            let dev_sk: [u8; 32] = [
                0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee,
                0xff, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c,
                0x0d, 0x0e, 0x0f, 0x10,
            ];
            let dev_ps: [u8; 16] = [
                0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad,
                0xae, 0xaf,
            ];
            let sk = sphincs_c10::SigningKey::keygen(dev_sk, dev_ps);
            (*sk.pk_seed(), *sk.pk_root(), "built-in dev fixture".to_string())
        };

    let mut bytes = [0u8; 32];
    bytes[..16].copy_from_slice(&pk_seed);
    bytes[16..].copy_from_slice(&pk_root);

    // Emit a source file with the pubkey as a literal byte array plus
    // its SHA-256 fingerprint. The fingerprint is pre-computed at build
    // time so the FSBL's vendor-fpr check is a plain memcmp at runtime.
    use sha2::{Digest, Sha256};
    let fpr: [u8; 32] = Sha256::digest(&bytes).into();

    let mut src = String::new();
    src.push_str("// AUTO-GENERATED by fsbl/build.rs — do not edit by hand.\n");
    src.push_str(&format!(
        "//\n// Source: {source_desc}\n// SHA-256(pubkey): {}\n\n",
        fpr.iter().map(|b| format!("{b:02x}")).collect::<String>()
    ));
    src.push_str("/// Vendor pk_seed (first 16 bytes of the 32-byte pubkey).\n");
    src.push_str(&format!("pub const VENDOR_PK_SEED: [u8; 16] = {:?};\n", &bytes[..16]));
    src.push_str("/// Vendor pk_root (last 16 bytes of the 32-byte pubkey).\n");
    src.push_str(&format!("pub const VENDOR_PK_ROOT: [u8; 16] = {:?};\n", &bytes[16..]));
    src.push_str(
        "/// SHA-256(pk_seed || pk_root). Pre-computed at build time so\n\
        /// the runtime vendor-fpr check is a memcmp.\n",
    );
    src.push_str(&format!("pub const VENDOR_PK_FPR: [u8; 32] = {:?};\n", fpr));

    fs::write(out_dir.join("vendor_pubkey_bytes.rs"), src)
        .expect("writing vendor_pubkey_bytes.rs");
}
