"""The render gallery: every flow x every ending, every library screen x preset, at the
panel's 14 fps, with the Python file that makes each one — `python3 -m tools.handoff --renders`.

    renders/handoff/GALLERY.md                          the index (also copied into handoff/)
    renders/handoff/renders/flows/<flow>/<success|cancel>/<leaf>_<full|early>_<end>.gif
    renders/handoff/renders/screens/<cat>/<name>[--<preset>].gif

`--renders-zip` packs that folder as pq1-handoff-renders.zip; unzipped beside the handoff
the GALLERY.md links resolve (both put `renders/` at the same root).
"""
import os
import sys
import zipfile
from concurrent.futures import ProcessPoolExecutor

from . import introspect as I
import flows
import screens

FPS = 14
OUT = os.path.join(I.REPO, "renders", "handoff")
ZIP_NAME = "pq1-handoff-renders.zip"
SKIP_FILES = (".DS_Store",)


def src(mod):
    """the module file as the handoff ships it (handoff/source/…)"""
    return "source/" + I.rel(mod.__file__)


# ------------------------------------------------------------------- the jobs --
def flow_jobs():
    """[(flow, end, early, sample, relpath)] — the same matrix and names as `python3 -m flows X --end all`"""
    jobs = []
    for n in flows.names():
        mod = flows.get(n)
        leaf = n.rsplit("/", 1)[-1]
        ends = sorted(getattr(mod, "ENDS", {}))
        smp = flows.sample_names(n)
        if not ends:
            jobs.append((n, None, False, smp[0] if smp else None, f"flows/{n}/{leaf}.gif"))
            continue
        long_ = any(s.get("kind") == "confirm" for s in flows.screens(n))
        for early in ([False, True] if long_ else [False]):
            for e in ends:
                picked = smp[flows.sample_slot(n, e, early)] if smp else None
                oc = "success" if mod.ENDS[e].get("state", "done") == "done" else "cancel"
                jobs.append((n, e, early, picked,
                             f"flows/{n}/{oc}/{leaf}_{'early' if early else 'full'}_{e}.gif"))
    return jobs


def screen_jobs():
    """[(qual, preset or None, relpath)] — every library screen, default + each distinct preset"""
    jobs = []
    for qual, mod in sorted(screens.modules().items()):
        seen = []
        for p in [None] + sorted(getattr(mod, "PRESETS", {})):
            sp = screens.spec(qual, preset=p) if p else screens.spec(qual)
            if sp in seen:                  # a preset equal to the default renders once
                continue
            seen.append(sp)
            jobs.append((qual, p, f"screens/{qual}{'--' + p if p else ''}.gif"))
    return jobs


def _render_flow(job, root):
    from pq1 import flow as pqflow
    n, end, early, sample, rel_ = job
    scr = flows.screens(n, end, early=early, sample=sample)
    pqflow.save_gif(pqflow.render_flow(scr, fps=FPS), os.path.join(root, "renders", rel_), FPS, None)
    return rel_


def _render_screen(job, root):
    from screens.__main__ import main
    qual, preset, rel_ = job
    out = os.path.join(root, "renders", rel_)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    main([preset or qual, "-o", out, "--fps", str(FPS)])
    return rel_


# ------------------------------------------------------------------ the index --
def _cmd_flow(n, end, early):
    return (f"python3 -m flows {n}" + (f" --end {end}" if end else "")
            + (" --early" if early else "") + f" --fps {FPS}")


def gallery_md(fjobs, sjobs):
    L = ["<!-- GENERATED by `python3 -m tools.handoff --renders` (tools/handoff/gallery.py) -->",
         "# Render gallery",
         "",
         f"Every flow × every ending and every library screen × preset, rendered from the code at the "
         f"panel's {FPS} fps. The GIFs are in **`pq1-handoff-renders.zip`**: unzip it into the handoff folder "
         f"(`unzip -o pq1-handoff-renders.zip`, which carries this same GALLERY.md) and the links below "
         f"open. Opened on its own, that zip's GALLERY.md works too. Each row names **the "
         f"Python that makes it** (under `source/`) and the command that re-renders it from `source/`.",
         "",
         f"{len(flows.names())} flows · {len(fjobs)} flow renders · {len(screens.modules())} library "
         f"screens · {len(sjobs)} screen renders. Illustrations: never measure timing off a GIF — "
         f"the numbers are in `spec/`.",
         ""]

    # library screens: verdicts first, they are the ones a port gets wrong
    cats = sorted({q.split("/")[0] for q, _, _ in sjobs}, key=lambda c: (c != "verdict", c))
    L += ["## Library screens", "",
          "Ready-made status screens a flow splices in (`screens.spec(name)`). One catalog page each "
          "in `catalog/library/`.", ""]
    for cat in cats:
        L += [f"### {cat}", "", "| screen | preset | GIF | made by | re-render |", "|---|---|---|---|---|"]
        for qual, p, rel_ in sjobs:
            if qual.split("/")[0] != cat:
                continue
            mod, _ = screens.get(qual)
            L.append(f"| `{qual}` | {p or '—'} | [{os.path.basename(rel_)}](renders/{rel_}) "
                     f"| `{src(mod)}` | `python3 -m screens {p or qual} --fps {FPS}` |")
        L.append("")

    # flows, grouped by family
    L += ["## Flows", "",
          "Each flow is one module of plain screen dicts; `pq1/` decides the structure. `full` walks "
          "every screen, `early` takes the mid-flow Confirm? exit (long flows only). `success/` = the "
          "ending resolves done, `cancel/` = declined or failed. Every flow is also listed screen by "
          "screen in `spec/flows.json` and `source/flows/MANIFEST.md`.", ""]
    fams = {}
    for j in fjobs:
        fams.setdefault(j[0].split("/")[0] if "/" in j[0] else "(single flows)", []).append(j)
    for fam in sorted(fams, key=lambda f: (f == "(single flows)", f)):
        L += [f"### {fam}", "", "| flow | path | ending | GIF | made by | re-render |", "|---|---|---|---|---|---|"]
        for n, end, early, _s, rel_ in fams[fam]:
            L.append(f"| `{n}` | {'early' if early else 'full'} | {end or '—'} "
                     f"| [{os.path.basename(rel_)}](renders/{rel_}) | `{src(flows.get(n))}` "
                     f"| `{_cmd_flow(n, end, early)}` |")
        L.append("")
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------ entry points --
def render(out=OUT, workers=None):
    fjobs, sjobs = flow_jobs(), screen_jobs()
    print(f"rendering {len(fjobs)} flow + {len(sjobs)} screen GIFs at {FPS} fps -> {I.rel(out)}/ …", flush=True)
    bad = []
    with ProcessPoolExecutor(max_workers=workers or os.cpu_count()) as ex:
        futs = {ex.submit(_render_flow, j, out): j[-1] for j in fjobs}
        futs.update({ex.submit(_render_screen, j, out): j[-1] for j in sjobs})
        for i, (f, rel_) in enumerate(futs.items(), 1):
            try:
                f.result()
            except Exception as e:           # noqa: BLE001 — report every failure, not the first
                bad.append(f"{rel_}: {e}")
            if i % 20 == 0:
                print(f"  {i}/{len(futs)}", flush=True)
    for f in [os.path.join(out, "renders", j[-1]) for j in fjobs + sjobs]:
        if not os.path.exists(f):
            bad.append(f"missing {I.rel(f)}")
    open(os.path.join(out, "GALLERY.md"), "w").write(gallery_md(fjobs, sjobs))
    if bad:
        print(f"GALLERY FAILED — {len(bad)} problems:", file=sys.stderr)
        for b in bad:
            print("  - " + b, file=sys.stderr)
        return 1
    mb = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(out) for f in fs) / 1e6
    print(f"gallery -> {I.rel(out)}/ ({len(fjobs) + len(sjobs)} GIFs, {mb:.0f} MB)")
    return 0


def make_zip(out=OUT):
    if not os.path.exists(os.path.join(out, "GALLERY.md")):
        print("no gallery yet — run `python3 -m tools.handoff --renders`", file=sys.stderr)
        return 1
    path = os.path.join(I.REPO, ZIP_NAME)
    with zipfile.ZipFile(path, "w") as z:
        for root, dirs, files in os.walk(out):
            dirs.sort()
            for f in sorted(files):
                if f in SKIP_FILES:
                    continue
                p = os.path.join(root, f)
                zi = zipfile.ZipInfo(os.path.relpath(p, out), date_time=(2026, 1, 1, 0, 0, 0))
                zi.compress_type = zipfile.ZIP_DEFLATED if f.endswith(".md") else zipfile.ZIP_STORED
                zi.external_attr = 0o644 << 16
                z.writestr(zi, open(p, "rb").read())
    print(f"zipped -> {ZIP_NAME} ({os.path.getsize(path) // 1024 // 1024} MB)")
    return 0
