"""The catalog's table of contents — every screen type, component, action and
transition the handoff documents. ADD A ROW HERE to add a page; its prose goes
in pages/<section>/<slug>.md (library screens get a page automatically, one
per module in screens/, from the module's own docstring).

  port     PORT        the device must implement it
           DEMO-ONLY   exists for the GIF / demo loop — do not port
           BENCH-ONLY  exists for the laptop bench player — do not port
           SPEC-ONLY   specified in DESIGN.md, not rendered by the Python yet
  match    (screen, flow_screens, i) -> bool : which live flow screens ARE this
           type — drives {{example}}, {{used-in}} and the flows x types matrix
  preview  a previews.record() recipe, or ("window", flow or None) = the first
           matching live screen with its neighbours, walked by the demo Sim
  gestures a truth-table context (substring) for {{gestures}}
"""
from pq1 import status

R, L = "right", "left"


def E(section, slug, title, summary, port="PORT", owners=(), match=None, preview=None, gestures=None):
    return dict(section=section, slug=slug, title=title, summary=summary, port=port,
                owners=list(owners), match=match, preview=preview, gestures=gestures)


def _anim(s):
    return s.get("anim") or status.default_anim(s)


def _is_status(s, anim=None, lead=None):
    if s.get("kind") != "status":
        return False
    if lead is not None and bool(s.get("lead")) != lead:
        return False
    return anim is None or _anim(s) == anim


SCREEN_TYPES = [
    E("screen-types", "hero-ask", "Hero — the ask",
      "The question the flow exists to ask (SEND 12,500 TOSHI?). The hub: taps enter the details, hold-right signs.",
      owners=["pq1/layout.py", "pq1/flow.py", "pq1/components.py", "pq1/driver.py"],
      match=lambda s, a, i: s["kind"] == "hero" and s.get("commit") and not s.get("pager"),
      preview=("window", "send_token"), gestures="hero — the ask"),
    E("screen-types", "hero-intro", "Hero — an intro (band chevron)",
      "A hero that introduces instead of asking: the caption carries the chevron, corners hide, nothing to sign here.",
      owners=["pq1/layout.py", "pq1/components.py", "flows/erc7730/__init__.py", "flows/firmware/__init__.py"],
      match=lambda s, a, i: s["kind"] == "hero" and s.get("band_chev") and not s.get("pager"),
      preview=("window", "erc7730/swap"), gestures="hero — an intro"),
    E("screen-types", "hero-pager", "Hero — batch position (n/m pager)",
      "A batch's per-transaction hero: the pager says which transaction of how many; it never turns.",
      owners=["pq1/layout.py", "pq1/components.py", "flows/batch/__init__.py"],
      match=lambda s, a, i: s["kind"] == "hero" and bool(s.get("pager")),
      preview=("window", "batch/transfers")),
    E("screen-types", "detail", "Detail",
      "One fact of the transaction: circle + label on one side, 1–3 value lines on the other. Sides alternate.",
      owners=["pq1/layout.py", "pq1/components.py", "pq1/flow.py"],
      match=lambda s, a, i: (s["kind"] == "detail" and not s.get("pages")
                             and "chain" not in s),
      preview=("window", "send_token"), gestures="detail — middle"),
    E("screen-types", "chain", "Chain badge",
      "Which network is being signed for: one chain id becomes the mark, the disc colour, the trail and the caption.",
      owners=["pq1/chains.py", "pq1/colors.py", "pq1/layout.py",
              "pq1/procedural/chains.py"],
      match=lambda s, a, i: "chain" in s,
      preview=("window", "send"), gestures="detail — middle"),
    E("screen-types", "detail-paged", "Detail — paged (n/m)",
      "A value too long for three lines: pages of 1–3 lines, a pager, and taps that turn the page before the screen.",
      owners=["pq1/layout.py", "pq1/flow.py", "pq1/motion.py", "pq1/components.py"],
      match=lambda s, a, i: s["kind"] == "detail" and bool(s.get("pages")),
      preview=("window", "eip1271/personal_counterfactual_hash"), gestures="detail — paged"),
    E("screen-types", "value", "Value — full-width text",
      "A value shown alone and centred across the panel; the token disc parks off-canvas.",
      owners=["pq1/layout.py", "pq1/flow.py"],
      match=lambda s, a, i: s["kind"] == "value" and not s.get("words") and not s.get("pages"),
      preview=("window", None), gestures="value — full-width"),
    E("screen-types", "value-paged", "Value — paged",
      "A full-width value over two or more pages (a full hash), with the n/m pager.",
      owners=["pq1/layout.py", "pq1/flow.py", "flows/fingerprint/__init__.py"],
      match=lambda s, a, i: s["kind"] == "value" and bool(s.get("pages")),
      preview=("synthetic", "value-paged")),
    E("screen-types", "value-words", "Value — numbered words grid",
      "Up to eight numbered words in two columns (the firmware fingerprint words).",
      owners=["pq1/layout.py", "flows/firmware/__init__.py"],
      match=lambda s, a, i: s["kind"] == "value" and bool(s.get("words")),
      preview=("window", "firmware/update")),
    E("screen-types", "confirm", "Confirm? — the mid-flow early exit",
      "Inserted automatically as the 6th screen of a long flow: sign now, or keep reading.",
      owners=["pq1/layout.py", "pq1/motion.py", "pq1/components.py", "flows/__init__.py"],
      match=lambda s, a, i: s["kind"] == "confirm",
      preview=("window", "blind/unknown_call"), gestures="confirm —"),
    E("screen-types", "batch-segment", "Batch — a run of segments",
      "A batch is several transactions in one flow: each segment has its own hub hero and its own ending.",
      owners=["flows/batch/__init__.py", "pq1/layout.py", "pq1/driver.py"],
      match=lambda s, a, i: s["kind"] == "hero" and bool(s.get("pager")) and s.get("commit")),
    E("screen-types", "status-qubit", "Status — the qubit film (an ending after work)",
      "The device did work: the token splits into two qubits, orbits — on the device for as long as the work takes — spirals back, flashes, and the result lands: the check, or the X when the host reports a failure.",
      owners=["pq1/loading.py", "pq1/status.py"],
      match=lambda s, a, i: _is_status(s, "qubit", lead=False), preview=("anim", "core/qubit")),
    E("screen-types", "status-resolve", "Status — the resolve (a cancel ending)",
      "A cancel does no work, so there is no film: the token resolves in place to the failed look.",
      owners=["pq1/status.py"],
      match=lambda s, a, i: _is_status(s, "resolve", lead=False), preview=("anim", "core/resolve")),
    E("screen-types", "status-arrive", "Status — arrive (an ending after a lead film)",
      "The resting look arrives on an empty canvas under the verdict entrance law.",
      owners=["pq1/status.py", "pq1/motion.py"],
      match=lambda s, a, i: _is_status(s, "arrive"), preview=("anim", "core/arrive")),
    E("screen-types", "status-led", "Status — led by a film (lead + gap + main)",
      "One screen made of two animations: a film that ends on an empty canvas, a gap of black, then the main.",
      owners=["pq1/status.py", "screens/fx/explosion.py", "flows/firmware/__init__.py"],
      match=lambda s, a, i: s.get("kind") == "status" and bool(s.get("lead")),
      preview=("end", "firmware/update", "updated")),
    E("screen-types", "resting-look", "The resting look — branded vs unbranded endings",
      "What an ending rests on: unbranded flows stroke the disc in the state colour; branded families fill it.",
      owners=["pq1/status.py", "pq1/colors.py", "flows/safe/__init__.py", "flows/cowswap/__init__.py"],
      match=lambda s, a, i: s.get("kind") == "status" and "resting" in s,
      preview=("end", "safe/clear_sign", "signed")),
]

COMPONENTS = [
    E("components", "token-disc", "Token disc",
      "The 60 px circle every navigable screen carries: solid, unknown (address-hashed ramp), logo art or monogram.",
      owners=["pq1/components.py", "pq1/colors.py", "pq1/gradients.py"]),
    E("components", "glyph-morph", "Glyph + chevron morph",
      "Between two screens the glyph inside the disc and the corner chevrons crossfade on the mix spring.",
      owners=["pq1/flow.py", "pq1/components.py"]),
    E("components", "chevrons", "Corner chevrons and the hint bob",
      "The two corner marks say what the buttons do: lr = taps navigate, up = a hold is armed. They bob to hint.",
      owners=["pq1/components.py", "pq1/motion.py", "pq1/layout.py", "pq1/flow.py"]),
    E("components", "band-chevron", "Band chevron",
      "An intro's caption carries one chevron beside the text; the corner chevrons hide.",
      owners=["pq1/components.py", "pq1/layout.py"]),
    E("components", "pager", "Pager (n/m)",
      "The small n/m mark: on a paged value it follows the page; on a batch hero it names the transaction.",
      owners=["pq1/components.py", "pq1/flow.py"]),
    E("components", "confirm-band", "Confirm band",
      "The Confirm? screen's bottom band alternates two instructions on a slow beat.",
      owners=["pq1/motion.py", "pq1/components.py", "pq1/flow.py"]),
    E("components", "caption", "Caption (the bottom band)",
      "The question / status text on the y-128 baseline, and how it fades between screens.",
      owners=["pq1/components.py", "pq1/layout.py", "pq1/typography.py", "pq1/flow.py"]),
    E("components", "busy-caption", "Busy caption",
      "The caption during a loading film breathes; it starts only once the qubits are on the orbit.",
      owners=["pq1/status.py", "pq1/motion.py"]),
    E("components", "detail-text", "Detail text: label, tiers, name lines, transition rows",
      "The value block: size tiers, the SemiBold name line, the old-to-new transition row, line stacking.",
      owners=["pq1/layout.py", "pq1/typography.py", "pq1/components.py"]),
    E("components", "words-grid", "Words grid",
      "Two columns of four numbered words, numbers right-aligned in grey.",
      owners=["pq1/layout.py"]),
    E("components", "trail", "Trail (follower chain)",
      "Five discs trail the token as it travels and as it sweeps; each chases the one ahead.",
      owners=["pq1/motion.py", "pq1/components.py", "pq1/flow.py"]),
    E("components", "idle-sweep", "Idle sweep",
      "On a hero the token drifts side to side after a short rest, inside fixed x bounds.",
      owners=["pq1/motion.py", "pq1/flow.py", "pq1/layout.py"]),
    E("components", "pulse-rings", "Pulse rings",
      "Expanding rings around the disc that mark a screen needing extra attention (blind signing).",
      owners=["pq1/components.py", "pq1/flow.py"]),
    E("components", "flash-ring", "Flash ring + result glyphs",
      "How a result lands on the disc: the flash ring, the check / X glyph and the caption.",
      owners=["pq1/loading.py", "pq1/status.py", "pq1/components.py", "pq1/procedural/marks.py"]),
    E("components", "hold-flood", "Hold flood (the progress fill)",
      "A hold fills the disc from the bottom up; three dresses depending on the body under it.",
      owners=["pq1/components.py", "pq1/motion.py", "pq1/flow.py"], preview=("driver", "send_token", [("hold", R, 1200), ("wait", 300), ("hold", R)])),
    E("components", "pin-row", "PIN row: slots, dials, marks and labels",
      "Eight rings; the active one dials a digit; − / + marks and pulsing instruction labels.",
      owners=["screens/pin/pin_entering.py", "pq1/procedural/pin_slots.py", "pq1/procedural/marks.py"]),
    E("components", "press-feedback", "Press feedback (chevron nudge)",
      "The pressed side's chevron nudges for an instant. Specified, not yet rendered by the Python.",
      port="SPEC-ONLY", owners=["pq1/motion.py", "pq1/driver.py", "pq1/DESIGN.md"]),
]

ACTIONS = [
    E("actions", "tap-hub", "Tap on the ask — enter the details",
      "Either tap on a hero enters the detail section at its first screen; an intro leads on to the ask.",
      owners=["pq1/driver.py"], gestures="hero —",
      preview=("driver", "erc7730/swap", [("tap", R), ("tap", R), ("tap", L)])),
    E("actions", "tap-navigate", "Tap left / right — back and forward",
      "Inside the details left regresses, right progresses; a paged screen turns its page first.",
      owners=["pq1/driver.py", "pq1/flow.py"], gestures="detail —",
      preview=("driver", "send_token", [("tap", R), ("tap", R), ("tap", R), ("tap", L), ("tap", L)])),
    E("actions", "tap-page", "Tap on a paged screen — the page turns first",
      "Right: next page until the last, then the next screen. Left: previous page, then the previous screen on its LAST page.",
      owners=["pq1/driver.py", "pq1/flow.py", "pq1/motion.py"], gestures="detail — paged",
      preview=("driver", "fingerprint/erc8213_call_data_digest", [("tap", R), ("tap", R), ("tap", R), ("tap", L), ("tap", L)])),
    E("actions", "hold-right-sign", "Hold right — sign",
      "Armed only where the screen commits (the ask, Confirm?). The disc fills; the action fires when it is full.",
      owners=["pq1/driver.py", "pq1/motion.py", "pq1/components.py", "pq1/flow.py"], gestures="hero — the ask",
      preview=("driver", "send_token", [("hold", R)])),
    E("actions", "hold-left-decline", "Hold left — decline",
      "Armed on every navigable screen of a flow that has a failing ending.",
      owners=["pq1/driver.py", "pq1/motion.py"], gestures="detail — first",
      preview=("driver", "send_token", [("tap", R), ("hold", L)])),
    E("actions", "hold-release-early", "Release a hold early — snap back",
      "Letting go before the fill completes drains it and does nothing.",
      owners=["pq1/motion.py", "pq1/flow.py", "pq1/driver.py"],
      preview=("driver", "send_token", [("hold", R, 1300), ("wait", 500)])),
    E("actions", "unbound-gestures", "Unbound gestures — what is NOT bound",
      "Right hold where nothing commits, both buttons and double presses outside an entry, any input during an ending.",
      owners=["pq1/driver.py"], gestures=""),
    E("actions", "entry-dial", "PIN entry — tap to dial the digit",
      "On an entry a tap is −1 / +1 on the active dial.",
      owners=["pq1/driver.py", "screens/pin/pin_entering.py"], gestures="entry — PIN row, empty",
      preview=("driver", "pin/unlock", [("tap", R), ("tap", R), ("tap", R), ("tap", L)])),
    E("actions", "entry-enter", "PIN entry — both buttons ENTER; the 8th checks the PIN",
      "The chord enters the digit and moves on; the chord that completes the row submits it at once.",
      owners=["pq1/driver.py", "screens/pin/pin_entering.py", "pq1/motion.py"], gestures="entry — PIN row",
      preview=("driver", "pin/unlock", [("tap", R), ("chord",), ("tap", R), ("tap", R), ("chord",), ("chord",)])),
    E("actions", "entry-move", "PIN entry — double press: BACK / NEXT over entered digits",
      "A second press on one side inside the double-tap window moves the cursor; a dial is never taken away.",
      owners=["pq1/driver.py", "screens/pin/pin_entering.py", "pq1/motion.py"], gestures="entry — PIN row, 3 digits",
      preview=("driver", "pin/unlock", [("chord",), ("chord",), ("chord",), ("double", L), ("double", L), ("double", R)])),
    E("actions", "entry-cancel", "PIN entry — hold left cancels the row",
      "Only the left hold is bound on an entry: the rings fill white and the row is cancelled.",
      owners=["pq1/driver.py", "screens/pin/pin_entering.py"], gestures="entry — PIN row",
      preview=("driver", "pin/unlock", [("tap", R), ("chord",), ("hold", L)])),
    E("actions", "entry-outcome", "PIN entry — after the row: miss, match, cancel",
      "A miss plays its verdict and opens the next attempt; a match continues; a cancel returns.",
      owners=["pq1/driver.py", "flows/pin/__init__.py", "screens/pin/pin_entering.py"]),
    E("actions", "demo-auto-advance", "Demo auto-advance and the demo-performed hold",
      "The GIF / kiosk loop advances on dwell timers and performs the hold itself. On hardware nothing moves without a press.",
      port="DEMO-ONLY", owners=["pq1/flow.py", "pq1/motion.py"]),
    E("actions", "bench-keys", "Bench player keys",
      "The laptop bench player maps keyboard keys onto the two buttons to drive the panel.",
      port="BENCH-ONLY", owners=["tools/panel/play_flow.py"]),
]

TRANSITIONS = [
    E("transitions", "spring-morph", "Spring morph — screen to screen",
      "Every screen change is one critically-damped spring set: circle x / y / r, the glyph mix and each screen's text alpha.",
      owners=["pq1/flow.py", "pq1/motion.py"],
      preview=("driver", "send_token", [("tap", R), ("tap", R), ("tap", R), ("tap", L)])),
    E("transitions", "reversal", "Mid-flight reversal and retargeting",
      "A press during a transit is never dropped: the springs retarget from the live pose, velocity carried.",
      owners=["pq1/flow.py", "pq1/driver.py", "pq1/motion.py"],
      preview=("driver", "send_token", [("tap", R), ("fast", R), ("fast", L), ("fast", L)])),
    E("transitions", "text-in-delay", "Text-in delay — the circle leads",
      "Outgoing text fades at once; incoming text is released a beat later, so the disc visibly leads the words.",
      owners=["pq1/flow.py", "pq1/motion.py"]),
    E("transitions", "page-flip", "Page flip",
      "A page change is sequential: the old page fades out, then the new one fades in. The pager follows.",
      owners=["pq1/motion.py", "pq1/flow.py"]),
    E("transitions", "handoff", "Handoff crossfade — token to verdict",
      "Entering a screen that owns its canvas, the flow's resting token fades out under the screen's hold phase.",
      owners=["pq1/status.py", "pq1/verdict.py", "pq1/flow.py"]),
    E("transitions", "tokenless-fade", "Token-less transit — fade to black",
      "Leaving a verdict or a PIN row nothing morphs: the screen fades to black and the next handoff is dropped.",
      owners=["pq1/flow.py", "pq1/status.py", "pq1/canvas.py"]),
    E("transitions", "lead-film", "Lead film, tail and gap",
      "A film that ends on an empty canvas may lead a screen: its tail keeps drawing under the main's hold. A looping lead carries the led screen's start with it.",
      owners=["pq1/status.py", "screens/fx/explosion.py", "pq1/procedural/burst.py"]),
    E("transitions", "film-entrance", "Entering a film — the beat, then the seed",
      "The one sequential transit: the screen fades out with its circle parked, then the film morphs that circle into its first qubit. No spring leg.",
      owners=["pq1/flow.py", "pq1/loading.py", "pq1/status.py", "pq1/motion.py"],
      preview=("driver", "send", [("hold", R)])),
    E("transitions", "loading-loop", "The loading loop and the outcome latch",
      "A film starts when the work is dispatched, repeats the steady orbit in whole turns while the answer is outstanding, and latches its outcome at the spiral — the tail and the rest are fixed.",
      owners=["pq1/loading.py", "pq1/status.py", "pq1/driver.py", "screens/fx/explosion.py"],
      preview=("anim", "core/qubit", dict(busy="SIGNING…", ready=7000))),
    E("transitions", "side-entrance", "Side entrance of a film",
      "The explosion's token can enter from off-panel (left / right / both sides) before the film starts.",
      owners=["pq1/procedural/burst.py", "pq1/motion.py", "screens/fx/explosion.py"],
      preview=("anim", "fx/explosion", dict(enter="left"))),
    E("transitions", "hold-commit-fade", "Hold commit — the fill fades with the leg",
      "When a hold fires, the full fill does not pop: it fades out riding the transit's own spring.",
      owners=["pq1/flow.py", "pq1/components.py"]),
    E("transitions", "verdict-law", "The verdict law — hold, arrive, beat, caption, rest",
      "The phase law every verdict and arriving status obeys, and the entrance law inside it.",
      owners=["pq1/verdict.py", "pq1/motion.py", "pq1/status.py"], preview=("anim", "verdict/firmware_verified")),
    E("transitions", "result-hold", "Result hold and leaving an ending",
      "Every ending rests for the same time after it resolves, then the flow returns.",
      owners=["pq1/status.py", "pq1/flow.py"]),
]

CORE = SCREEN_TYPES + COMPONENTS + ACTIONS + TRANSITIONS
SECTIONS = [
    ("screen-types", "Screen types", "Every kind of screen a flow can contain."),
    ("library", "Library screens", "Ready-made status screens (verdicts, films, PIN, idle) a flow splices in — one page per module in screens/."),
    ("components", "Components", "The parts screens are made of."),
    ("actions", "Actions", "What the two buttons do, in every context."),
    ("transitions", "Transitions", "How the UI moves between and inside screens."),
]
