-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.ForsPk.Types
import Extracted.ForsPk.FunsExternal
import Extracted.Adrs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::ADRS_FORS_ROOTS]
    Source: 'sphincs-c10/src/params.rs', lines 101:0-101:35
    Visibility: public -/
@[global_simps, irreducible] def params.ADRS_FORS_ROOTS : Std.U32 := 4#u32

/-- [sphincs_c10::fors::compute_fors_pk]:
    Source: 'sphincs-c10/src/fors.rs', lines 265:0-268:1
    Visibility: public -/
def fors.compute_fors_pk
  (seed : Array Std.U8 32#usize) (ht_idx : Std.U32)
  (roots : Array (Array Std.U8 16#usize) 13#usize) :
  Result (Array Std.U8 16#usize)
  := do
  let i ← lift (core.convert.num.FromU64U32.from ht_idx)
  let roots_adrs ←
    address.make_adrs 0#u32 i params.ADRS_FORS_ROOTS 0#u32 0#u32 0#u32 0#u32
  let s ← lift (Array.to_slice roots)
  hash.th_multi seed roots_adrs s

end sphincs_c10
