#!/usr/bin/env node
//
// vk_bin_to_rust.js
//
// Convert a committed 960-byte Groth16 VK (`secure/data/vks/foo.vk.bin`)
// into a Rust source file that exposes `VK_BYTES: [u8; 960]` and
// `VK_HASH: [u8; 32]` (the SHA-256 of the blob). The Rust file is
// consumed by `zk-test` and, historically, by an older firmware path
// before VKs moved to NS rodata. It exists today purely so
// `cargo run -p zk-test` has a known-good static VK to exercise the
// host-side verifier against.
//
// This script replaces the VK-writing portion of
// `tools/export_zk_constants.js`, which used to read from an external
// `ZKlarity` directory. Our in-tree Circom pipeline produces the same
// VK bytes now (see circuits/README.md and circuits/UPSTREAM.md), so
// the input is a straightforward 960-byte file.
//
// Usage:
//   node circuits/scripts/vk_bin_to_rust.js \
//        --in  <secure/data/vks/foo.vk.bin> \
//        --out <secure/src/zk/vk_data.rs>
//

"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

function parseArgs(argv) {
  const opts = { in: null, out: null };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--in")  opts.in  = argv[++i];
    else if (a === "--out") opts.out = argv[++i];
    else if (a === "-h" || a === "--help") { printUsage(); process.exit(0); }
    else throw new Error("Unknown argument: " + a);
  }
  if (!opts.in || !opts.out) { printUsage(); throw new Error("Missing --in / --out"); }
  return opts;
}

function printUsage() {
  process.stderr.write([
    "Usage: node circuits/scripts/vk_bin_to_rust.js \\",
    "         --in  <secure/data/vks/foo.vk.bin> \\",
    "         --out <secure/src/zk/vk_data.rs>",
    "",
  ].join("\n"));
}

function formatByteArray(bytes, indent) {
  const lines = [];
  const bytesPerRow = 16;
  for (let i = 0; i < bytes.length; i += bytesPerRow) {
    const row = [];
    for (let j = i; j < Math.min(i + bytesPerRow, bytes.length); j++) {
      row.push("0x" + bytes[j].toString(16).padStart(2, "0"));
    }
    lines.push(indent + row.join(", ") + ",");
  }
  return lines.join("\n");
}

function main() {
  const opts = parseArgs(process.argv);

  const vkBytes = fs.readFileSync(opts.in);
  if (vkBytes.length !== 960) {
    throw new Error(`${opts.in}: expected 960 bytes, got ${vkBytes.length}`);
  }

  const vkHash = crypto.createHash("sha256").update(vkBytes).digest();

  const srcRel = path.relative(path.dirname(opts.out), opts.in);

  const rust = `//! Aave V3 Pool clear-signing VK for host-side ZK verifier tests.
//! Generated by circuits/scripts/vk_bin_to_rust.js — DO NOT EDIT.
//!
//! Source: ${srcRel}
//!
//! The firmware does NOT use this file in production — at sign time the
//! VK is supplied in the NS → S bundle and Merkle-verified against
//! \`secure/src/db_roots::VK_DB_ROOT\`. This static copy exists solely
//! so \`cargo run -p zk-test\` has a known-good 960-byte blob to
//! exercise the Groth16 verifier on the host CPU.

pub static VK_BYTES: [u8; 960] = [
${formatByteArray(vkBytes, "    ")}
];

pub static VK_HASH: [u8; 32] = [
${formatByteArray(vkHash, "    ")}
];
`;

  fs.mkdirSync(path.dirname(opts.out), { recursive: true });
  fs.writeFileSync(opts.out, rust);
  process.stdout.write(`wrote ${opts.out} (${rust.length} B)\n`);
}

try {
  main();
} catch (e) {
  process.stderr.write("vk_bin_to_rust: " + e.message + "\n");
  process.exit(1);
}
