-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [fw_manifest]: function definitions
import Aeneas
import Extracted.FwManifest.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace fw_manifest

/-- [fw_manifest::DOMAIN_TAG]
    Source: 'fw-manifest/src/lib.rs', lines 200:0-200:44
    Visibility: public -/
@[global_simps, irreducible]
def DOMAIN_TAG : Array Std.U8 7#usize :=
  Array.make 7#usize [ 80#u8, 81#u8, 70#u8, 87#u8, 95#u8, 86#u8, 49#u8 ]

/-- [fw_manifest::signed_preimage]:
    Source: 'fw-manifest/src/lib.rs', lines 276:0-290:1
    Visibility: public -/
def signed_preimage
  (fw_version : Std.U32) (secure_hash : Array Std.U8 32#usize)
  (nonsecure_hash : Array Std.U8 32#usize) :
  Result (Array Std.U8 75#usize)
  := do
  let out := Array.repeat 75#usize 0#u8
  let s ← lift (Array.to_slice DOMAIN_TAG)
  let ver_off := Slice.len s
  let sec_off ← ver_off + 4#usize
  let ns_off ← sec_off + 32#usize
  let (s1, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8)) out
      { «end» := ver_off }
  let s2 ← lift (Array.to_slice DOMAIN_TAG)
  let s3 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s1 s2
  let out1 := index_mut_back s3
  let (s4, index_mut_back1) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) out1
      { start := ver_off, «end» := sec_off }
  let a ← lift (core.num.U32.to_be_bytes fw_version)
  let s5 ← lift (Array.to_slice a)
  let s6 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s4 s5
  let out2 := index_mut_back1 s6
  let (s7, index_mut_back2) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) out2
      { start := sec_off, «end» := ns_off }
  let s8 ← lift (Array.to_slice secure_hash)
  let s9 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s7 s8
  let out3 := index_mut_back2 s9
  let i ← ns_off + 32#usize
  let (s10, index_mut_back3) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) out3
      { start := ns_off, «end» := i }
  let s11 ← lift (Array.to_slice nonsecure_hash)
  let s12 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s10 s11
  ok (index_mut_back3 s12)

end fw_manifest
