#!/usr/bin/env python3
"""verify-kani-census — a source-generated Kani harness census (F11, 2026-07-16).

THE GAP (FV review finding F11). The published Kani numbers ("148 harnesses /
25 files", "140 in 19 mutation-enrolled files, 8 in 6 outside") were a
hand-maintained prose count (docs + a stale `gate_enforcement.json` note said
"93 harnesses across 17 files"). `kani_mutations.json` is a MUTATION manifest —
it deliberately lists only the load-bearing harnesses that carry an anti-vacuity
mutation, so it can never encode the full 148/25 census. Nothing regenerated the
census from source, so it silently drifted and could not tell you when a new
security-bearing harness landed with no mutation coverage.

THIS GATE regenerates the census from the git-tracked sources (counting only
active, line-leading, standalone `#[kani::proof]` attributes — robust to
`#[kani::unwind(N)]`/comment lines between the attribute and `fn`), derives the
mutation-enrolled vs outside split from `kani_mutations.json`, cross-checks the
manifest for rot (file + harness still exist and each non-noop find string
occurs exactly once), and diffs exact file/function identities against a
committed lockfile
(`scripts/kani_census.lock.json`). Pure Python — NO `cargo kani` — so it runs on
every PR as the fast standing census, while the slow `verify-kani-mutation`
(which actually runs Kani) stays nightly.

Usage:
  kani_census.py --check     regenerate + diff vs the lock; FAIL on drift (CI default)
  kani_census.py --write     regenerate + write the lock (after a conscious change)
  kani_census.py --list      print the human census tables
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
MANIFEST = SCRIPT_DIR / "kani_mutations.json"
LOCK = SCRIPT_DIR / "kani_census.lock.json"

PROOF_ATTR = re.compile(r"^[ \t]*#\[kani::proof\][ \t]*$")
FN_DECL = re.compile(
    r"^[ \t]*(?:(?:pub(?:\([^)]*\))?)[ \t]+)?"
    r"(?:unsafe[ \t]+)?(?:async[ \t]+)?fn[ \t]+([A-Za-z_][A-Za-z0-9_]*)"
)


def git_tracked_rs() -> list[str]:
    out = subprocess.run(["git", "ls-files", "*.rs"], cwd=str(REPO_ROOT),
                         capture_output=True, text=True, check=True).stdout
    return sorted(l for l in out.splitlines() if l.strip())


def harnesses_in(text: str) -> list[str]:
    """Return exact harness names bound to active proof attributes.

    A proof attribute must occupy its own source line (apart from indentation
    and trailing whitespace). This deliberately rejects prose such as
    ``// Kani `#[kani::proof]` harnesses ...``. Once active, the attribute binds
    to the next active function declaration while allowing other attributes,
    comments, and blank lines in between.
    """
    names: list[str] = []
    pending = False
    for line in text.splitlines():
        if PROOF_ATTR.fullmatch(line):
            pending = True
            continue
        if pending:
            m = FN_DECL.match(line)
            if m:
                names.append(m.group(1))
                pending = False
    return names


def generate() -> dict:
    files: dict[str, int] = {}
    file_harnesses: dict[str, list[str]] = {}
    for rel in git_tracked_rs():
        p = REPO_ROOT / rel
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        harnesses = harnesses_in(text)
        if harnesses:
            files[rel] = len(harnesses)
            file_harnesses[rel] = harnesses

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    muts = manifest.get("mutations", [])
    enrolled_files = sorted({m["file"] for m in muts})
    enrolled_harnesses = sorted({f'{m["crate"]}::{m["harness"]}' for m in muts})
    tiers: dict[str, int] = {}
    for m in muts:
        tiers[m.get("tier", "?")] = tiers.get(m.get("tier", "?"), 0) + 1

    total_harnesses = sum(files.values())
    harnesses_in_enrolled = sum(c for f, c in files.items() if f in set(enrolled_files))
    outside_files = sorted(f for f in files if f not in set(enrolled_files))
    harnesses_outside = sum(files[f] for f in outside_files)

    return {
        "schema": "fv-kani-census/v1",
        "note": "F11 source-generated census (introduced 2026-07-16; refreshed 2026-07-23 "
                "at the FV Phase-D closure boundary). Generated by scripts/kani_census.py --write "
                "from git-tracked sources (active standalone #[kani::proof] attributes bound to "
                "their exact function identities). kani_mutations.json is the MUTATION manifest "
                "(load-bearing harnesses only); this lock is the FULL census + the enrolled/outside "
                "split. Run `make verify-kani-census` (--check) on every PR; regenerate with --write.",
        "files": files,
        "harnesses": file_harnesses,
        "totals": {
            "total_files": len(files),
            "total_harnesses": total_harnesses,
            "mutation_enrolled_files": len(enrolled_files),
            "harnesses_in_enrolled_files": harnesses_in_enrolled,
            "files_outside_mutation": len(outside_files),
            "harnesses_outside_mutation": harnesses_outside,
            "mutation_groups_total": len(muts),
            "mutation_groups_by_tier": tiers,
            "distinct_enrolled_harnesses": len(enrolled_harnesses),
        },
        "files_outside_mutation": outside_files,
        "_file_harnesses": file_harnesses,
    }


_FEATURE_REF = re.compile(r'\bfeature\s*=\s*"([^"]+)"')


def _harness_cfg_features(source: str, harness: str) -> list[str]:
    """``feature = "..."`` names from ``#[cfg(...)]`` attributes attached to
    ``fn <harness>`` (walking up over the contiguous attribute/comment/blank
    block above each same-named fn, unioned).

    A cfg-gated harness (e.g. ``#[cfg(feature = "kani-heavy")]``) is compiled
    OUT unless ``cargo kani`` gets a matching ``--features`` flag — without it
    kani produces no VERIFICATION verdict and the mutation lane dies with a
    HarnessError (issue #662). Only per-harness ``cfg`` attributes are seen;
    a gate on an enclosing ``mod`` is not (none exist today).
    """
    fn_decl = re.compile(
        r"^[ \t]*(?:(?:pub(?:\([^)]*\))?)[ \t]+)?"
        r"(?:unsafe[ \t]+)?(?:async[ \t]+)?fn[ \t]+" + re.escape(harness) + r"\b"
    )
    # Normalize complete attributes first, so layout never hides a cfg gate.
    source = re.sub(r"#\[[^\]]*\]", lambda m: " ".join(m.group().split()), source)
    lines = source.splitlines()
    features: list[str] = []
    for i, line in enumerate(lines):
        if not fn_decl.match(line):
            continue
        j = i - 1
        while j >= 0:
            s = lines[j].strip()
            if not s or s.startswith("//"):
                j -= 1
                continue
            if s.startswith("#["):
                if re.match(r"#\[cfg(?:_attr)?\b", s) and _FEATURE_REF.search(s):
                    if not re.fullmatch(r'#\[cfg\(\s*feature\s*=\s*"[^"]+"\s*\)\]', s):
                        raise ValueError(f"unsupported feature cfg on {harness}: {s}")
                    features.extend(_FEATURE_REF.findall(s))
                j -= 1
                continue
            break
    return sorted(set(features))


def _z_flag_features(entry: dict) -> list[str]:
    """Feature names an entry's ``z_flags`` passes via ``--features`` (both the
    ``["--features", "a,b"]`` and ``["--features=a,b"]`` forms)."""
    z_flags = entry.get("z_flags", [])
    feats: list[str] = []
    if not isinstance(z_flags, list):
        return feats
    for k, flag in enumerate(z_flags):
        if flag == "--features" and k + 1 < len(z_flags):
            feats.extend(x.strip() for x in str(z_flags[k + 1]).split(","))
        elif isinstance(flag, str) and flag.startswith("--features="):
            feats.extend(x.strip() for x in flag.split("=", 1)[1].split(","))
    return [f for f in feats if f]


def manifest_rot(
    census: dict,
    *,
    manifest: dict | None = None,
    repo_root: Path = REPO_ROOT,
) -> list[str]:
    """Static mirror of ``check_kani_mutations.py``'s materiality guard.

    The fast census must reject a mutation entry *before* the slow Kani lane if
    its file/harness disappeared, its find string is empty/absent/ambiguous, or
    its replacement is a no-op. Otherwise a dead mutation can remain enrolled
    in the published anti-vacuity count while never changing production code.

    The harness may live in a DIFFERENT file than the mutation target (a shared
    pure helper mutated where it is defined, pinned by a caller's harness —
    e.g. ``native_amount_exactness_helper_gate_dropped``); it is only required
    to exist in SOME git-tracked source. When the harness is cfg-gated
    (``#[cfg(feature = "...")]``), the entry's ``z_flags`` must enable every
    gating feature, else the slow lane compiles the harness out and dies with
    a HarnessError instead of a verdict (issue #662).

    ``manifest`` and ``repo_root`` are injectable only for the offline unit
    tests; normal callers read the committed manifest under :data:`REPO_ROOT`.
    """
    fails: list[str] = []
    fh = census["_file_harnesses"]
    if manifest is None:
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))

    for m in manifest.get("mutations", []):
        mutation_id = m.get("id", "<missing-id>")
        f = m.get("file")
        h = m.get("harness")
        if not isinstance(f, str) or not f:
            fails.append(f"manifest `{mutation_id}`: missing non-empty file path.")
            continue
        if not isinstance(h, str) or not h:
            fails.append(f"manifest `{mutation_id}`: missing non-empty harness name.")
            continue

        path = repo_root / f
        if not path.exists():
            fails.append(f"manifest `{mutation_id}`: file {f} does not exist (deleted/renamed).")
            continue
        harness_file = f if h in fh.get(f, []) else next(
            (hf for hf, hs in fh.items() if h in hs), None
        )
        if harness_file is None:
            fails.append(
                f"manifest `{mutation_id}`: no `#[kani::proof] fn {h}` in {f} or any "
                "other git-tracked source (renamed/deleted harness — the mutation "
                "would misfire before Kani runs)."
            )

        find = m.get("find")
        replace = m.get("replace")
        if not isinstance(find, str) or not find:
            fails.append(f"manifest `{mutation_id}`: find string is missing or empty.")
            continue
        if not isinstance(replace, str):
            fails.append(f"manifest `{mutation_id}`: replacement must be a string.")
            continue
        if replace == find:
            fails.append(f"manifest `{mutation_id}`: replace == find (no-op mutation).")

        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            fails.append(f"manifest `{mutation_id}`: cannot read {f}: {exc}.")
            continue
        occurrences = source.count(find)
        if occurrences != 1:
            fails.append(
                f"manifest `{mutation_id}`: find string occurs {occurrences}x in {f}; "
                "expected exactly once."
            )

        # cfg-gate feature check (issue #662 class): a harness compiled out for
        # lack of a `--features` flag yields no VERIFICATION verdict, so the
        # slow lane dies with a HarnessError. Catch it statically here.
        if harness_file is not None:
            hsource = source
            if harness_file != f:
                try:
                    hsource = (repo_root / harness_file).read_text(
                        encoding="utf-8", errors="replace"
                    )
                except OSError:
                    hsource = ""
            try:
                required = _harness_cfg_features(hsource, h)
            except ValueError as exc:
                fails.append(f"manifest `{mutation_id}`: {exc}")
                continue
            missing = [feat for feat in required if feat not in _z_flag_features(m)]
            if missing:
                fails.append(
                    f"manifest `{mutation_id}`: harness {h} is cfg-gated on "
                    f"feature(s) {required} in {harness_file} but the entry's z_flags "
                    f"do not enable {missing} — `cargo kani` would compile the harness "
                    f"OUT (no VERIFICATION verdict, the #662 nightly-lane death). Add "
                    f'e.g. ["--features", "{missing[0]}"] to the entry\'s z_flags.'
                )
    return fails


def _canonical(c: dict) -> dict:
    """The comparable subset (drop only the duplicate helper index)."""
    return {k: v for k, v in c.items() if k != "_file_harnesses"}


def do_check() -> int:
    census = generate()
    rot = manifest_rot(census)
    if rot:
        print(f"FAIL: kani_mutations.json has {len(rot)} stale/non-material entry issue(s):", file=sys.stderr)
        for r in rot:
            print(f"  - {r}", file=sys.stderr)
        return 2
    if not LOCK.exists():
        print(f"FAIL: {LOCK} missing — run `kani_census.py --write` to create the census lock.", file=sys.stderr)
        return 1
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    live = _canonical(census)
    if _canonical(lock) != live:
        print("FAIL: Kani census DRIFTED from the committed lock:", file=sys.stderr)
        lf, cf = lock.get("files", {}), live["files"]
        for f in sorted(set(lf) | set(cf)):
            if lf.get(f) != cf.get(f):
                print(f"  - {f}: lock={lf.get(f)} live={cf.get(f)}", file=sys.stderr)
        if lock.get("totals") != live["totals"]:
            print(f"  - totals: lock={lock.get('totals')}\n           live={live['totals']}", file=sys.stderr)
        print("\nA harness was added/removed/renamed, or the mutation-enrolled split changed. "
              "If intentional, run `kani_census.py --write` and update the census prose in docs/STATUS.md "
              "+ FV_SURFACE_MAP.md.", file=sys.stderr)
        return 1
    t = live["totals"]
    print(f"OK: Kani census matches the lock — {t['total_harnesses']} harnesses / {t['total_files']} files; "
          f"{t['harnesses_in_enrolled_files']} in {t['mutation_enrolled_files']} mutation-enrolled files, "
          f"{t['harnesses_outside_mutation']} in {t['files_outside_mutation']} outside; "
          f"{t['mutation_groups_total']} mutation groups {t['mutation_groups_by_tier']}. Manifest consistent.")
    return 0


def do_write() -> int:
    census = generate()
    rot = manifest_rot(census)
    if rot:
        print(f"REFUSING to write lock — manifest rot ({len(rot)}):", file=sys.stderr)
        for r in rot:
            print(f"  - {r}", file=sys.stderr)
        return 2
    LOCK.write_text(json.dumps(_canonical(census), indent=2) + "\n", encoding="utf-8")
    t = census["totals"]
    print(f"wrote {LOCK}: {t['total_harnesses']} harnesses / {t['total_files']} files "
          f"({t['harnesses_outside_mutation']} in {t['files_outside_mutation']} files outside mutation).")
    return 0


def do_list() -> int:
    census = generate()
    enrolled = {m["file"] for m in json.loads(MANIFEST.read_text(encoding="utf-8"))["mutations"]}
    print("=== Kani harness census (from git-tracked sources) ===")
    for f, c in sorted(census["files"].items()):
        mark = "" if f in enrolled else "  (no mutation coverage)"
        print(f"  {c:3d}  {f}{mark}")
    t = census["totals"]
    print(f"\n  TOTAL: {t['total_files']} files, {t['total_harnesses']} harnesses")
    print(f"  mutation-enrolled: {t['harnesses_in_enrolled_files']} harnesses in {t['mutation_enrolled_files']} files")
    print(f"  outside mutation:  {t['harnesses_outside_mutation']} harnesses in {t['files_outside_mutation']} files")
    print(f"  outside files: {census['files_outside_mutation']}")
    return 0


def main() -> int:
    args = sys.argv[1:]
    if "--write" in args or "--update" in args:
        return do_write()
    if "--list" in args:
        return do_list()
    return do_check()


if __name__ == "__main__":
    sys.exit(main())
