-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.XmssAuth.Types
import Extracted.XmssAuth.FunsExternal
import Extracted.XmssRoot.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- Trait implementation: [core::fmt::num::imp::{impl core::fmt::Display for usize}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 134:8-134:39
    Name pattern: [core::fmt::Display<usize>] -/
@[reducible, rust_trait_impl "core::fmt::Display<usize>"]
def Usize.Insts.CoreFmtDisplay : core.fmt.Display Std.Usize := {
  fmt := core.fmt.num.imp.DisplayUsize.fmt
}

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop body 1:
    Source: 'sphincs-c10/src/merkle.rs', lines 114:8-142:9 -/
@[rust_loop_body]
def merkle.build_subtree_with_auth_loop0_loop0.body
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (target_leaf : Std.U32) (stack : Array (Array Std.U8 16#usize) 10#usize)
  (stack_heights : Array Std.U32 10#usize) (kp : Std.Usize) (sp : Std.Usize)
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) (node : Array Std.U8 16#usize)
  (node_h : Std.U32) :
  Result (ControlFlow (Std.Usize × (Array (Array Std.U8 16#usize) 9#usize) ×
    (Array Bool 9#usize) × (Array Std.U8 16#usize) × Std.U32) (Std.Usize ×
    (Array (Array Std.U8 16#usize) 9#usize) × (Array Bool 9#usize) × (Array
    Std.U8 16#usize) × Std.U32))
  := do
  if sp > 0#usize
  then
    let i ← sp - 1#usize
    let i1 ← Array.index_usize stack_heights i
    if i1 = node_h
    then
      let left ← Array.index_usize stack i
      let h ← lift (UScalar.cast .Usize node_h)
      let b ← Array.index_usize keep_set h
      let (keep1, keep_set1) ←
        if b
        then ok (keep, keep_set)
        else
          do
          let target_at_h ← target_leaf >>> node_h
          let sibling_at_h ← lift (target_at_h ^^^ 1#u32)
          let i2 ← node_h + 1#u32
          let i3 ← kp >>> i2
          let pair_start ← i3 <<< i2
          let i4 ← pair_start >>> node_h
          let left_idx ← lift (UScalar.cast .U32 i4)
          let right_idx ← left_idx + 1#u32
          if left_idx = sibling_at_h
          then
            let a ← Array.update keep h left
            let a1 ← Array.update keep_set h true
            ok (a, a1)
          else
            if right_idx = sibling_at_h
            then
              let a ← Array.update keep h node
              let a1 ← Array.update keep_set h true
              ok (a, a1)
            else ok (keep, keep_set)
      let i2 ← node_h + 1#u32
      let i3 ← kp >>> i2
      let parent_idx ← lift (UScalar.cast .U32 i3)
      let adrs ←
        address.make_adrs layer tree params.ADRS_TREE 0#u32 0#u32 i2 parent_idx
      let a ← hash.pad16 left
      let a1 ← hash.pad16 node
      let node1 ← hash.th_pair seed adrs a a1
      ok (cont (i, keep1, keep_set1, node1, i2))
    else ok (done (sp, keep, keep_set, node, node_h))
  else ok (done (sp, keep, keep_set, node, node_h))

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop 1:
    Source: 'sphincs-c10/src/merkle.rs', lines 114:8-142:9 -/
@[rust_loop]
def merkle.build_subtree_with_auth_loop0_loop0
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (target_leaf : Std.U32) (stack : Array (Array Std.U8 16#usize) 10#usize)
  (stack_heights : Array Std.U32 10#usize) (sp : Std.Usize)
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) (kp : Std.Usize)
  (node : Array Std.U8 16#usize) (node_h : Std.U32) :
  Result (Std.Usize × (Array (Array Std.U8 16#usize) 9#usize) × (Array Bool
    9#usize) × (Array Std.U8 16#usize) × Std.U32)
  := do
  loop
    (fun (sp1, keep1, keep_set1, node1, node_h1) =>
      merkle.build_subtree_with_auth_loop0_loop0.body seed layer tree
      target_leaf stack stack_heights kp sp1 keep1 keep_set1 node1 node_h1)
    (sp, keep, keep_set, node, node_h)

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop body 0:
    Source: 'sphincs-c10/src/merkle.rs', lines 110:4-153:5 -/
@[rust_loop_body]
def merkle.build_subtree_with_auth_loop0.body
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (target_leaf : Std.U32)
  (progress : hypertree.ProgressSink) (pct_lo : Std.U8) (pct_hi : Std.U8)
  (n_leaves : Std.Usize) (iter : core.ops.range.Range Std.Usize)
  (stack : Array (Array Std.U8 16#usize) 10#usize)
  (stack_heights : Array Std.U32 10#usize) (sp : Std.Usize)
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 10#usize) × (Array Std.U32 10#usize) × Std.Usize × (Array
    (Array Std.U8 16#usize) 9#usize) × (Array Bool 9#usize)) ((Array (Array
    Std.U8 16#usize) 10#usize) × Std.Usize × (Array (Array Std.U8 16#usize)
    9#usize) × (Array Bool 9#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (stack, sp, keep, keep_set))
  | some kp =>
    let i ← lift (UScalar.cast .U32 kp)
    let node ← wots.keygen_pk seed sk_seed layer tree i
    let (sp1, keep1, keep_set1, node1, node_h) ←
      merkle.build_subtree_with_auth_loop0_loop0 seed layer tree target_leaf
        stack stack_heights sp keep keep_set kp node 0#u32
    let (_, index_mut_back) ← Array.index_mut_usize stack sp1
    let (_, index_mut_back1) ← Array.index_mut_usize stack_heights sp1
    let sp2 ← sp1 + 1#usize
    let i1 ← kp + 1#usize
    let i2 ← i1 % merkle.REPORT_EVERY
    if i2 = 0#usize
    then
      let i3 ← lift (core.num.U8.saturating_sub pct_hi pct_lo)
      let span ← lift (core.convert.num.FromU32U8.from i3)
      let i4 ← lift (core.convert.num.FromU32U8.from pct_lo)
      let i5 ← lift (UScalar.cast .U32 kp)
      let i6 ← i5 + 1#u32
      let i7 ← i6 * span
      let i8 ← lift (UScalar.cast .U32 n_leaves)
      let i9 ← i7 / i8
      let pct ← i4 + i9
      let i10 ← lift (UScalar.cast .U8 pct)
      hypertree.report progress i10
      let a := index_mut_back1 node_h
      let a1 := index_mut_back node1
      ok (cont (iter1, a1, a, sp2, keep1, keep_set1))
    else
      let a := index_mut_back1 node_h
      let a1 := index_mut_back node1
      ok (cont (iter1, a1, a, sp2, keep1, keep_set1))

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop 0:
    Source: 'sphincs-c10/src/merkle.rs', lines 110:4-153:5 -/
@[rust_loop]
def merkle.build_subtree_with_auth_loop0
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (sk_seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (target_leaf : Std.U32) (progress : hypertree.ProgressSink) (pct_lo : Std.U8)
  (pct_hi : Std.U8) (n_leaves : Std.Usize)
  (stack : Array (Array Std.U8 16#usize) 10#usize)
  (stack_heights : Array Std.U32 10#usize) (sp : Std.Usize)
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) :
  Result ((Array (Array Std.U8 16#usize) 10#usize) × Std.Usize × (Array
    (Array Std.U8 16#usize) 9#usize) × (Array Bool 9#usize))
  := do
  loop
    (fun (iter1, stack1, stack_heights1, sp1, keep1, keep_set1) =>
      merkle.build_subtree_with_auth_loop0.body seed sk_seed layer tree
      target_leaf progress pct_lo pct_hi n_leaves iter1 stack1 stack_heights1
      sp1 keep1 keep_set1)
    (iter, stack, stack_heights, sp, keep, keep_set)

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop body 2:
    Source: 'sphincs-c10/src/merkle.rs', lines 159:8-159:25 -/
@[rust_loop_body]
def merkle.build_subtree_with_auth_loop1.body
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) (iter : core.ops.range.Range Std.Usize)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 9#usize)) (Array (Array Std.U8 16#usize) 9#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done auth_path)
  | some h =>
    let b ← Array.index_usize keep_set h
    if b
    then
      let a ← Array.index_usize keep h
      let a1 ← Array.update auth_path h a
      ok (cont (iter1, a1))
    else
      let a ← core.fmt.rt.Argument.new_display Usize.Insts.CoreFmtDisplay h
      let _ ←
        core.fmt.Arguments.new
          (Array.make 39#usize [
            25#u8, 65#u8, 117#u8, 116#u8, 104#u8, 32#u8, 112#u8, 97#u8, 116#u8,
            104#u8, 32#u8, 110#u8, 111#u8, 100#u8, 101#u8, 32#u8, 97#u8,
            116#u8, 32#u8, 104#u8, 101#u8, 105#u8, 103#u8, 104#u8, 116#u8,
            32#u8, 192#u8, 10#u8, 32#u8, 110#u8, 111#u8, 116#u8, 32#u8, 102#u8,
            111#u8, 117#u8, 110#u8, 100#u8, 0#u8
            ]) (Array.make 1#usize [ a ])
      fail panic

/-- [sphincs_c10::merkle::build_subtree_with_auth]: loop 2:
    Source: 'sphincs-c10/src/merkle.rs', lines 159:8-159:25 -/
@[rust_loop]
def merkle.build_subtree_with_auth_loop1
  (iter : core.ops.range.Range Std.Usize)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize)
  (keep : Array (Array Std.U8 16#usize) 9#usize)
  (keep_set : Array Bool 9#usize) :
  Result (Array (Array Std.U8 16#usize) 9#usize)
  := do
  loop
    (fun (iter1, auth_path1) => merkle.build_subtree_with_auth_loop1.body keep
      keep_set iter1 auth_path1)
    (iter, auth_path)

/-- [sphincs_c10::merkle::build_subtree_with_auth]:
    Source: 'sphincs-c10/src/merkle.rs', lines 85:0-165:1 -/
def merkle.build_subtree_with_auth
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (target_leaf : Std.U32)
  (progress : hypertree.ProgressSink) (pct_lo : Std.U8) (pct_hi : Std.U8) :
  Result ((Array (Array Std.U8 16#usize) 9#usize) × (Array Std.U8 16#usize))
  := do
  let n_leaves ← params.SUBTREE_LEAVES
  let a := Array.repeat 16#usize 0#u8
  let auth_path := Array.repeat 9#usize a
  let a1 := Array.repeat 16#usize 0#u8
  let stack := Array.repeat 10#usize a1
  let stack_heights := Array.repeat 10#usize 0#u32
  let a2 := Array.repeat 16#usize 0#u8
  let keep := Array.repeat 9#usize a2
  let keep_set := Array.repeat 9#usize false
  let (stack1, sp, keep1, keep_set1) ←
    merkle.build_subtree_with_auth_loop0
      { start := 0#usize, «end» := n_leaves } seed sk_seed layer tree
      target_leaf progress pct_lo pct_hi n_leaves stack stack_heights 0#usize
      keep keep_set
  massert (sp = 1#usize)
  let root ← Array.index_usize stack1 0#usize
  let i ← params.SUBTREE_H
  let auth_path1 ←
    merkle.build_subtree_with_auth_loop1 { start := 0#usize, «end» := i }
      auth_path keep1 keep_set1
  ok (auth_path1, root)

end sphincs_c10
