//! 5×8 ASCII glyph table for the FSBL fingerprint renderer (NV3007 LCD).
//!
//! Vendored from the same `secure/assets/font_5x8.raw` the secure-world
//! uses so the FSBL row and `measured_boot::run`'s row are visually
//! identical. ~480 bytes of rodata.
//!
//! Column-byte format: bit `r` of byte `c` = pixel at column `c`, row `r`
//! (0 = top). The layout is column-major because it was chosen when the
//! bench display was an SSD1306, whose page format it matched directly; the
//! NV3007 renderer expands these same bytes to RGB565. Kept as-is so the FSBL
//! and secure-world rows stay byte-identical.
//!
//! Generated by `fsbl/build.rs::generate_font_flat`.

// `FONT_GLYPH_H` is part of the generated table but the FSBL renderer
// only needs `FONT_GLYPH_W` + the column-byte format directly.
#[allow(dead_code)]
mod table {
    include!(concat!(env!("OUT_DIR"), "/glyphs_5x8.rs"));
}
pub use table::{FONT_FIRST_CHAR, FONT_FLAT_5X8, FONT_GLYPH_W, FONT_LAST_CHAR};

/// Look up one column-byte of an ASCII glyph. Returns 0 (blank column)
/// for non-printable input.
#[inline]
pub fn glyph_col(ch: u8, col: usize) -> u8 {
    if ch < FONT_FIRST_CHAR || ch > FONT_LAST_CHAR || col >= FONT_GLYPH_W {
        return 0;
    }
    FONT_FLAT_5X8[(ch - FONT_FIRST_CHAR) as usize][col]
}
