-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.ForsRoot.Types
import Extracted.ForsRoot.FunsExternal
import Extracted.ForsRecovery.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::FORS_LEAVES]
    Source: 'sphincs-c10/src/params.rs', lines 40:0-40:38
    Visibility: public -/
@[global_simps, irreducible]
def params.FORS_LEAVES : Result Std.Usize := 1#usize <<< params.A

/-- [sphincs_c10::fors::compute_fors_root]: loop body 1:
    Source: 'sphincs-c10/src/fors.rs', lines 156:8-172:9
    Visibility: public -/
@[rust_loop_body]
def fors.compute_fors_root_loop0_loop0.body
  (seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (stack : Array (Array Std.U8 16#usize) 12#usize)
  (stack_heights : Array Std.U32 12#usize) (j : Std.Usize) (sp : Std.Usize)
  (node : Array Std.U8 16#usize) (node_h : Std.U32) :
  Result (ControlFlow (Std.Usize × (Array Std.U8 16#usize) × Std.U32)
    (Std.Usize × (Array Std.U8 16#usize) × Std.U32))
  := do
  if sp > 0#usize
  then
    let i ← sp - 1#usize
    let i1 ← Array.index_usize stack_heights i
    if i1 = node_h
    then
      let sibling ← Array.index_usize stack i
      let i2 ← node_h + 1#u32
      let i3 ← j >>> i2
      let parent_idx ← lift (UScalar.cast .U32 i3)
      let i4 ← lift (core.convert.num.FromU64U32.from ht_idx)
      let adrs ←
        address.make_adrs 0#u32 i4 params.ADRS_FORS_TREE tree_idx 0#u32 i2
          parent_idx
      let a ← hash.pad16 sibling
      let a1 ← hash.pad16 node
      let node1 ← hash.th_pair seed adrs a a1
      ok (cont (i, node1, i2))
    else ok (done (sp, node, node_h))
  else ok (done (sp, node, node_h))

/-- [sphincs_c10::fors::compute_fors_root]: loop 1:
    Source: 'sphincs-c10/src/fors.rs', lines 156:8-172:9
    Visibility: public -/
@[rust_loop]
def fors.compute_fors_root_loop0_loop0
  (seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (stack : Array (Array Std.U8 16#usize) 12#usize)
  (stack_heights : Array Std.U32 12#usize) (sp : Std.Usize) (j : Std.Usize)
  (node : Array Std.U8 16#usize) (node_h : Std.U32) :
  Result (Std.Usize × (Array Std.U8 16#usize) × Std.U32)
  := do
  loop
    (fun (sp1, node1, node_h1) => fors.compute_fors_root_loop0_loop0.body seed
      ht_idx tree_idx stack stack_heights j sp1 node1 node_h1)
    (sp, node, node_h)

/-- [sphincs_c10::fors::compute_fors_root]: loop body 0:
    Source: 'sphincs-c10/src/fors.rs', lines 148:4-177:5
    Visibility: public -/
@[rust_loop_body]
def fors.compute_fors_root_loop0.body
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (ht_idx : Std.U32) (tree_idx : Std.U32)
  (iter : core.ops.range.Range Std.Usize)
  (stack : Array (Array Std.U8 16#usize) 12#usize)
  (stack_heights : Array Std.U32 12#usize) (sp : Std.Usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 12#usize) × (Array Std.U32 12#usize) × Std.Usize) ((Array
    (Array Std.U8 16#usize) 12#usize) × (Array Std.U32 12#usize) ×
    Std.Usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (stack, stack_heights, sp))
  | some j =>
    let i ← lift (UScalar.cast .U32 j)
    let secret ← hash.fors_secret sk_seed ht_idx tree_idx i
    let i1 ← lift (core.convert.num.FromU64U32.from ht_idx)
    let i2 ← lift (UScalar.cast .U32 j)
    let leaf_adrs ←
      address.make_adrs 0#u32 i1 params.ADRS_FORS_TREE tree_idx 0#u32 0#u32 i2
    let a ← hash.pad16 secret
    let node ← hash.th seed leaf_adrs a
    let (sp1, node1, node_h) ←
      fors.compute_fors_root_loop0_loop0 seed ht_idx tree_idx stack
        stack_heights sp j node 0#u32
    let a1 ← Array.update stack sp1 node1
    let a2 ← Array.update stack_heights sp1 node_h
    let sp2 ← sp1 + 1#usize
    ok (cont (iter1, a1, a2, sp2))

/-- [sphincs_c10::fors::compute_fors_root]: loop 0:
    Source: 'sphincs-c10/src/fors.rs', lines 148:4-177:5
    Visibility: public -/
@[rust_loop]
def fors.compute_fors_root_loop0
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (sk_seed : Array Std.U8 32#usize) (ht_idx : Std.U32) (tree_idx : Std.U32)
  (stack : Array (Array Std.U8 16#usize) 12#usize)
  (stack_heights : Array Std.U32 12#usize) (sp : Std.Usize) :
  Result ((Array (Array Std.U8 16#usize) 12#usize) × (Array Std.U32 12#usize)
    × Std.Usize)
  := do
  loop
    (fun (iter1, stack1, stack_heights1, sp1) =>
      fors.compute_fors_root_loop0.body seed sk_seed ht_idx tree_idx iter1
      stack1 stack_heights1 sp1)
    (iter, stack, stack_heights, sp)

/-- [sphincs_c10::fors::compute_fors_root]:
    Source: 'sphincs-c10/src/fors.rs', lines 136:0-182:1
    Visibility: public -/
def fors.compute_fors_root
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (ht_idx : Std.U32) (tree_idx : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  let n_leaves ← params.FORS_LEAVES
  let a := Array.repeat 16#usize 0#u8
  let stack := Array.repeat 12#usize a
  let stack_heights := Array.repeat 12#usize 0#u32
  let (stack1, stack_heights1, sp) ←
    fors.compute_fors_root_loop0 { start := 0#usize, «end» := n_leaves } seed
      sk_seed ht_idx tree_idx stack stack_heights 0#usize
  massert (sp = 1#usize)
  let right_val ← lift (UScalar.cast .U32 params.A)
  let left_val ← Array.index_usize stack_heights1 0#usize
  massert (left_val = right_val)
  Array.index_usize stack1 0#usize

end sphincs_c10
