// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {Test} from "forge-std/Test.sol";
import {UserOperation} from "account-abstraction/interfaces/UserOperation.sol";
import {PQCoinbaseSmartWallet} from "../src/PQCoinbaseSmartWallet.sol";
import {PQCoinbaseSmartWalletFactory} from "../src/PQCoinbaseSmartWalletFactory.sol";
import {SphincsC7Asm} from "../src/verifiers/SphincsC7Asm.sol";
import {ISPHINCSVerifier} from "../src/verifiers/ISPHINCSVerifier.sol";

/// @notice Gas benchmarks using the REAL SphincsC7Asm verifier and genuine
///         SPHINCS+C7 signatures generated by the Python reference signer.
///
///         Run: `forge test --mc GasBenchmarkReal -vvv`
///
///         Test vectors are loaded from test/test_vectors.json, generated by:
///         `python3 script/gen_test_vectors.py > test/test_vectors.json`
contract GasBenchmarkRealTest is Test {
    SphincsC7Asm internal verifier;
    PQCoinbaseSmartWallet internal implementation;
    PQCoinbaseSmartWalletFactory internal factory;
    PQCoinbaseSmartWallet internal wallet;

    address internal constant ENTRY_POINT = 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789;

    // Keys loaded from test vectors
    bytes32 internal bootstrapPkSeed;
    bytes32 internal bootstrapPkRoot;
    bytes32 internal mainPkSeed;
    bytes32 internal mainPkRoot;

    // Signatures loaded from test vectors
    bytes internal bootstrapSig;    // signs factory auth message
    bytes internal mainSig;         // signs userOpHash
    bytes internal bootstrapSig2;   // signs rotation hash
    bytes32 internal userOpHash;
    bytes32 internal rotationHash;

    function setUp() public {
        // Load test vectors from JSON
        string memory json = vm.readFile("test/test_vectors.json");

        bootstrapPkSeed = vm.parseJsonBytes32(json, ".bootstrap.pkSeed");
        bootstrapPkRoot = vm.parseJsonBytes32(json, ".bootstrap.pkRoot");
        mainPkSeed = vm.parseJsonBytes32(json, ".main.pkSeed");
        mainPkRoot = vm.parseJsonBytes32(json, ".main.pkRoot");

        bootstrapSig = vm.parseJsonBytes(json, ".bootstrapSig");
        mainSig = vm.parseJsonBytes(json, ".mainSig");
        bootstrapSig2 = vm.parseJsonBytes(json, ".bootstrapSig2");
        userOpHash = vm.parseJsonBytes32(json, ".userOpHash");
        rotationHash = vm.parseJsonBytes32(json, ".rotationHash");

        // Deploy real C7 verifier
        verifier = new SphincsC7Asm();
        vm.label(address(verifier), "SphincsC7Verifier");

        implementation = new PQCoinbaseSmartWallet(ISPHINCSVerifier(address(verifier)));
        vm.label(address(implementation), "Implementation");

        factory = new PQCoinbaseSmartWalletFactory(address(implementation), ISPHINCSVerifier(address(verifier)));
        vm.label(address(factory), "Factory");

        // Deploy wallet via factory with real bootstrap signature
        wallet = factory.createAccount(
            bootstrapPkSeed, bootstrapPkRoot,
            mainPkSeed, mainPkRoot,
            bootstrapSig
        );
        vm.label(address(wallet), "Wallet");

        vm.deal(address(wallet), 100 ether);
        vm.deal(ENTRY_POINT, 100 ether);
    }

    // ── Verifier standalone ───────────────────────────────────────────

    function test_real_verifier_standalone() public {
        // Verify the main signature directly against the verifier
        uint256 gasBefore = gasleft();
        bool valid = verifier.verify(mainPkSeed, mainPkRoot, userOpHash, mainSig);
        uint256 gasUsed = gasBefore - gasleft();

        assertTrue(valid, "Main signature must verify");
        emit log_named_uint("gas_verifier_standalone_main", gasUsed);
    }

    function test_real_verifier_standalone_bootstrap() public {
        bytes32 authMsg = keccak256(abi.encodePacked("PQWALLET_INIT_V1", mainPkSeed, mainPkRoot));

        uint256 gasBefore = gasleft();
        bool valid = verifier.verify(bootstrapPkSeed, bootstrapPkRoot, authMsg, bootstrapSig);
        uint256 gasUsed = gasBefore - gasleft();

        assertTrue(valid, "Bootstrap signature must verify");
        emit log_named_uint("gas_verifier_standalone_bootstrap", gasUsed);
    }

    // ── createAccount ─────────────────────────────────────────────────

    function test_real_gas_createAccount() public {
        // Deploy a fresh wallet with different bootstrap key to get a new CREATE2
        // We need a real bootstrap sig for the new key, so we use the existing
        // wallet's factory and measure an idempotent call
        uint256 gasBefore = gasleft();
        factory.createAccount(
            bootstrapPkSeed, bootstrapPkRoot,
            mainPkSeed, mainPkRoot,
            bootstrapSig
        );
        uint256 gasUsed = gasBefore - gasleft();

        emit log_named_uint("gas_createAccount_existing_realSig", gasUsed);
    }

    // ── validateUserOp with MAIN signer ───────────────────────────────

    function test_real_gas_validateUserOp_mainSigner() public {
        bytes memory wrappedSig = abi.encode(PQCoinbaseSmartWallet.PQSignatureWrapper({
            signerType: PQCoinbaseSmartWallet.SignerType.MAIN,
            keyIndex: 0,
            otsIndex: 0,
            pkSeed: mainPkSeed,
            pkRoot: mainPkRoot,
            signature: mainSig
        }));

        UserOperation memory op;
        op.sender = address(wallet);
        op.nonce = 0;
        op.initCode = "";
        op.callData = abi.encodeCall(
            PQCoinbaseSmartWallet.execute,
            (address(0xbeef), 0, "")
        );
        op.callGasLimit = 100_000;
        op.verificationGasLimit = 500_000;
        op.preVerificationGas = 21_000;
        op.maxFeePerGas = 50 gwei;
        op.maxPriorityFeePerGas = 2 gwei;
        op.paymasterAndData = "";
        op.signature = wrappedSig;

        vm.prank(ENTRY_POINT);
        uint256 gasBefore = gasleft();
        uint256 result = wallet.validateUserOp(op, userOpHash, 0);
        uint256 gasUsed = gasBefore - gasleft();

        assertEq(result, 0, "Signature validation must succeed");
        assertEq(wallet.currentOTSIndex(), 1, "OTS must be consumed");
        emit log_named_uint("gas_validateUserOp_main_realSig", gasUsed);
    }

    // ── validateUserOp with BOOTSTRAP signer ──────────────────────────

    function test_real_gas_validateUserOp_bootstrapSigner() public {
        bytes memory wrappedSig = abi.encode(PQCoinbaseSmartWallet.PQSignatureWrapper({
            signerType: PQCoinbaseSmartWallet.SignerType.BOOTSTRAP,
            keyIndex: 0,
            otsIndex: 0,
            pkSeed: bootstrapPkSeed,
            pkRoot: bootstrapPkRoot,
            signature: bootstrapSig2
        }));

        UserOperation memory op;
        op.sender = address(wallet);
        op.nonce = 0;
        op.initCode = "";
        op.callData = abi.encodeCall(
            PQCoinbaseSmartWallet.execute,
            (address(0xbeef), 0, "")
        );
        op.callGasLimit = 100_000;
        op.verificationGasLimit = 500_000;
        op.preVerificationGas = 21_000;
        op.maxFeePerGas = 50 gwei;
        op.maxPriorityFeePerGas = 2 gwei;
        op.paymasterAndData = "";
        op.signature = wrappedSig;

        vm.prank(ENTRY_POINT);
        uint256 gasBefore = gasleft();
        uint256 result = wallet.validateUserOp(op, rotationHash, 0);
        uint256 gasUsed = gasBefore - gasleft();

        assertEq(result, 0, "Bootstrap signature validation must succeed");
        assertEq(wallet.bootstrapOTSIndex(), 1, "Bootstrap OTS must be consumed");
        emit log_named_uint("gas_validateUserOp_bootstrap_realSig", gasUsed);
    }

    // ── Full UserOp with real verification ────────────────────────────

    function test_real_gas_fullUserOp_mainSigner() public {
        bytes memory wrappedSig = abi.encode(PQCoinbaseSmartWallet.PQSignatureWrapper({
            signerType: PQCoinbaseSmartWallet.SignerType.MAIN,
            keyIndex: 0,
            otsIndex: 0,
            pkSeed: mainPkSeed,
            pkRoot: mainPkRoot,
            signature: mainSig
        }));

        UserOperation memory op;
        op.sender = address(wallet);
        op.nonce = 0;
        op.initCode = "";
        op.callData = abi.encodeCall(
            PQCoinbaseSmartWallet.execute,
            (address(0xbeef), 1 ether, "")
        );
        op.callGasLimit = 100_000;
        op.verificationGasLimit = 500_000;
        op.preVerificationGas = 21_000;
        op.maxFeePerGas = 50 gwei;
        op.maxPriorityFeePerGas = 2 gwei;
        op.paymasterAndData = "";
        op.signature = wrappedSig;

        // Validate
        vm.prank(ENTRY_POINT);
        uint256 gasBefore = gasleft();
        wallet.validateUserOp(op, userOpHash, 0);
        uint256 validateGas = gasBefore - gasleft();

        // Execute
        vm.prank(ENTRY_POINT);
        gasBefore = gasleft();
        wallet.execute(address(0xbeef), 1 ether, "");
        uint256 executeGas = gasBefore - gasleft();

        emit log_named_uint("gas_fullUserOp_main_validate_real", validateGas);
        emit log_named_uint("gas_fullUserOp_main_execute_real", executeGas);
        emit log_named_uint("gas_fullUserOp_main_total_real", validateGas + executeGas);
    }

    // ── Calldata cost estimation ──────────────────────────────────────

    function test_real_calldata_costs() public pure {
        // C7 signature = 3704 bytes
        // PQSignatureWrapper ABI-encoded overhead: ~256 bytes (struct fields + offsets)
        // Total calldata ≈ 3704 + 256 = ~3960 bytes
        //
        // Calldata cost: 16 gas/non-zero byte, 4 gas/zero byte
        // For 3704-byte sig, roughly ~90% non-zero = 3334 * 16 + 370 * 4 ≈ 54,824 gas
        //
        // Compare to old SLH-DSA-SHA2-128f: 17088 bytes → ~250K gas for calldata alone
        //
        // Savings: ~195K gas just from smaller signatures
    }
}
