// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import {Test} from "forge-std/Test.sol";
import {JardinForsCVerifier} from "../src/verifiers/JardinForsCVerifier.sol";

/// @notice Tests for the JARDIN FORS+C verifier using Rust-generated test vectors.
contract JardinFoscVerifierTest is Test {
    JardinForsCVerifier internal verifier;

    // Test vector data (generated by jardin-fosc/tests/gen_test_vectors.rs)
    bytes32 constant PK_SEED = 0xcc67318434d2b168bba6ebbec6b0af5a00000000000000000000000000000000;
    bytes32 constant PK_ROOT = 0x3a8a0b11b7d724527b0df54d89a17c8300000000000000000000000000000000;

    function setUp() public {
        verifier = new JardinForsCVerifier();
    }

    /// @notice Load a test vector signature from the JSON file.
    function _loadSig(uint256 index) internal view returns (bytes32 message, bytes memory sig) {
        string memory json = vm.readFile("test/jardin_test_vectors.json");
        string memory base = string.concat(".signatures[", vm.toString(index), "]");

        message = vm.parseJsonBytes32(json, string.concat(base, ".message"));
        sig = vm.parseJsonBytes(json, string.concat(base, ".signature"));
    }

    /// @notice Verify q=1 signature (minimum size: 2468 bytes).
    function test_verifyQ1() public view {
        (bytes32 message, bytes memory sig) = _loadSig(0);
        assertEq(sig.length, 2468, "q=1 sig should be 2468 bytes");
        assertTrue(verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, message, sig));
    }

    /// @notice Verify q=2 signature (2484 bytes).
    function test_verifyQ2() public view {
        (bytes32 message, bytes memory sig) = _loadSig(1);
        assertEq(sig.length, 2484, "q=2 sig should be 2484 bytes");
        assertTrue(verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, message, sig));
    }

    /// @notice Verify q=50 signature (3252 bytes).
    function test_verifyQ50() public view {
        (bytes32 message, bytes memory sig) = _loadSig(2);
        assertEq(sig.length, 3252, "q=50 sig should be 3252 bytes");
        assertTrue(verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, message, sig));
    }

    /// @notice Gas benchmark for q=1 (minimum gas).
    function test_gasQ1() public {
        (bytes32 message, bytes memory sig) = _loadSig(0);
        uint256 gasBefore = gasleft();
        bool valid = verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, message, sig);
        uint256 gasUsed = gasBefore - gasleft();
        assertTrue(valid);
        emit log_named_uint("Gas q=1", gasUsed);
    }

    /// @notice Gas benchmark for q=50 (mid-range).
    function test_gasQ50() public {
        (bytes32 message, bytes memory sig) = _loadSig(2);
        uint256 gasBefore = gasleft();
        bool valid = verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, message, sig);
        uint256 gasUsed = gasBefore - gasleft();
        assertTrue(valid);
        emit log_named_uint("Gas q=50", gasUsed);
    }

    /// @notice Wrong message should fail (revert on forced-zero check or return false).
    function test_wrongMessageFails() public {
        (, bytes memory sig) = _loadSig(0);
        bytes32 wrongMsg = bytes32(uint256(0xDEADBEEF));
        // A wrong message changes the digest — the forced-zero check may revert,
        // or verification may proceed and return false. Both are correct rejections.
        try verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, wrongMsg, sig) returns (bool valid) {
            assertFalse(valid, "wrong message should not verify");
        } catch {
            // Revert is also a valid rejection (forced-zero check failed)
        }
    }

    /// @notice Wrong pkSeed should fail.
    function test_wrongPkSeedFails() public {
        (bytes32 message, bytes memory sig) = _loadSig(0);
        bytes32 wrongSeed = bytes32(uint256(0x1234));
        try verifier.verifyForsCUnbalanced(wrongSeed, PK_ROOT, message, sig) returns (bool valid) {
            assertFalse(valid, "wrong pkSeed should not verify");
        } catch {
            // Revert is also a valid rejection
        }
    }

    /// @notice Wrong pkRoot should fail.
    function test_wrongPkRootFails() public {
        (bytes32 message, bytes memory sig) = _loadSig(0);
        bytes32 wrongRoot = bytes32(uint256(0x5678));
        try verifier.verifyForsCUnbalanced(PK_SEED, wrongRoot, message, sig) returns (bool valid) {
            assertFalse(valid, "wrong pkRoot should not verify");
        } catch {
            // Revert is also a valid rejection
        }
    }

    /// @notice Signature too short should revert.
    function test_sigTooShortReverts() public {
        bytes memory shortSig = new bytes(100);
        vm.expectRevert();
        verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, bytes32(0), shortSig);
    }

    /// @notice Signature length not aligned to 16 after body should revert.
    function test_sigMisalignedReverts() public {
        bytes memory badSig = new bytes(2460); // 2452 + 8 (not multiple of 16)
        vm.expectRevert();
        verifier.verifyForsCUnbalanced(PK_SEED, PK_ROOT, bytes32(0), badSig);
    }
}
