#!/usr/bin/env python3
"""
UI fingerprint fixture comparator.

Parses [UI-FP] lines from stdin (typical usage: piped from `make e2e`
with the ui-capture feature enabled), then either:

  * --regenerate      write the captured hashes to a fresh fixtures file
  * --check <path>    compare captured hashes against the fixtures file
                      and exit 1 on any mismatch
  * default           print captured fingerprints one per line

The on-device producer is `secure/src/ui/capture.rs`. Each line the
firmware emits looks like:

    [UI-FP] 0000  a1b2c3d4...   (64 hex chars)

Lines that don't match that shape are ignored, so the script is
safe to feed raw semihosting log output.

See docs/trezor-comparison.md §2.3 for the design context.

Examples:

  # First run — capture fingerprints and dump to stdout
  make e2e 2>&1 | tools/ui_fixture.py

  # Regenerate fixtures from a clean run
  make e2e 2>&1 | tools/ui_fixture.py --regenerate tests/ui_fixtures.json

  # Check a test run against existing fixtures (CI usage)
  make e2e 2>&1 | tools/ui_fixture.py --check tests/ui_fixtures.json
"""
import argparse
import json
import os
import re
import sys

FP_RE = re.compile(r"^\[UI-FP\]\s+([0-9a-f]{4})\s+([0-9a-f]{64})\s*$")


def parse_stream(stream):
    """Yield (index, hash) tuples from every matching [UI-FP] line."""
    for line in stream:
        m = FP_RE.match(line.strip())
        if not m:
            continue
        idx = int(m.group(1), 16)
        digest = m.group(2)
        yield idx, digest


def cmd_regenerate(args, fingerprints):
    """Write fresh fixtures — overwrites any existing file."""
    if not fingerprints:
        print("error: no [UI-FP] lines seen on stdin", file=sys.stderr)
        sys.exit(2)
    payload = {
        "version": 1,
        "description": (
            "Generated by tools/ui_fixture.py --regenerate. "
            "Each key is the hex frame index emitted by "
            "secure/src/ui/capture.rs; value is the SHA-256 of the "
            "frame's backend-specific bytes. Regenerate on intentional "
            "UI changes."
        ),
        "fixtures": {f"{idx:04x}": digest for idx, digest in fingerprints},
    }
    with open(args.path, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")
    print(f"wrote {len(fingerprints)} fixtures to {args.path}", file=sys.stderr)


def cmd_check(args, fingerprints):
    """Compare against an existing fixtures file. Exit 1 on any diff."""
    if not os.path.exists(args.path):
        print(
            f"error: fixtures file not found at {args.path}. "
            f"Run --regenerate first.",
            file=sys.stderr,
        )
        sys.exit(2)
    with open(args.path) as f:
        stored = json.load(f)
    expected = stored.get("fixtures", {})
    mismatches = []
    captured = {f"{idx:04x}": digest for idx, digest in fingerprints}
    # Every expected fingerprint must appear and match.
    for key, want in sorted(expected.items()):
        got = captured.get(key)
        if got is None:
            mismatches.append(f"[{key}] missing in capture (expected {want[:16]}…)")
        elif got != want:
            mismatches.append(
                f"[{key}] mismatch: want {want[:16]}… got {got[:16]}…"
            )
    # Every captured fingerprint must have a fixture.
    for key in sorted(captured):
        if key not in expected:
            mismatches.append(
                f"[{key}] unexpected new frame: {captured[key][:16]}…"
            )
    if mismatches:
        print(
            f"UI regression check FAILED ({len(mismatches)} issue(s)):",
            file=sys.stderr,
        )
        for m in mismatches:
            print(f"  {m}", file=sys.stderr)
        sys.exit(1)
    print(
        f"UI regression check OK ({len(captured)} frames matched)",
        file=sys.stderr,
    )


def main():
    ap = argparse.ArgumentParser(
        description="UI fingerprint fixture manager.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = ap.add_subparsers(dest="cmd")

    ap_re = sub.add_parser("regenerate", help="write fresh fixtures")
    ap_re.add_argument("path", help="fixtures JSON to write")

    ap_chk = sub.add_parser("check", help="compare against fixtures")
    ap_chk.add_argument("path", help="fixtures JSON to compare against")

    # Allow --regenerate/--check as shorthand for the subcommands above.
    ap.add_argument("--regenerate", metavar="PATH",
                    help="shorthand for `regenerate PATH`")
    ap.add_argument("--check", metavar="PATH",
                    help="shorthand for `check PATH`")

    args = ap.parse_args()
    fingerprints = list(parse_stream(sys.stdin))

    if args.regenerate:
        args.path = args.regenerate
        return cmd_regenerate(args, fingerprints)
    if args.check:
        args.path = args.check
        return cmd_check(args, fingerprints)
    if args.cmd == "regenerate":
        return cmd_regenerate(args, fingerprints)
    if args.cmd == "check":
        return cmd_check(args, fingerprints)

    # Default: just echo the captured fingerprints.
    if not fingerprints:
        print("no [UI-FP] lines seen on stdin", file=sys.stderr)
        sys.exit(2)
    for idx, digest in fingerprints:
        print(f"{idx:04x}  {digest}")


if __name__ == "__main__":
    main()
