-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.WotsSign.Types
import Extracted.WotsSign.FunsExternal
import Extracted.PkFromSig.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::wots::sign_with_shuffle]: loop body 0:
    Source: 'sphincs-c10/src/wots.rs', lines 149:4-154:5 -/
@[rust_loop_body]
def wots.sign_with_shuffle_loop.body
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (kp : Std.U32)
  (digits : Array Std.U8 43#usize) (base_adrs : Array Std.U8 32#usize)
  (chain_order : Array Std.U8 64#usize) (iter : core.ops.range.Range Std.Usize)
  (sigma : Array (Array Std.U8 16#usize) 43#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array (Array Std.U8
    16#usize) 43#usize)) (Array (Array Std.U8 16#usize) 43#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done sigma)
  | some step =>
    let i ← Array.index_usize chain_order step
    let i1 ← lift (UScalar.cast .Usize i)
    let i2 ← lift (UScalar.cast .U32 i1)
    let sk_i ← hash.wots_secret sk_seed layer tree kp i2
    let i3 ← lift (UScalar.cast .U32 i1)
    let chain_adrs ← address.set_chain_index base_adrs i3
    let i4 ← Array.index_usize digits i1
    let i5 ← lift (UScalar.cast .U32 i4)
    let a ← hash.chain_hash seed chain_adrs sk_i 0#u32 i5
    let a1 ← Array.update sigma i1 a
    ok (cont (iter1, a1))

/-- [sphincs_c10::wots::sign_with_shuffle]: loop 0:
    Source: 'sphincs-c10/src/wots.rs', lines 149:4-154:5 -/
@[rust_loop]
def wots.sign_with_shuffle_loop
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (sk_seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (kp : Std.U32) (digits : Array Std.U8 43#usize)
  (base_adrs : Array Std.U8 32#usize)
  (sigma : Array (Array Std.U8 16#usize) 43#usize)
  (chain_order : Array Std.U8 64#usize) :
  Result (Array (Array Std.U8 16#usize) 43#usize)
  := do
  loop
    (fun (iter1, sigma1) => wots.sign_with_shuffle_loop.body seed sk_seed layer
      tree kp digits base_adrs chain_order iter1 sigma1)
    (iter, sigma)

/-- [sphincs_c10::wots::sign_with_shuffle]:
    Source: 'sphincs-c10/src/wots.rs', lines 130:0-156:1 -/
def wots.sign_with_shuffle
  (seed : Array Std.U8 32#usize) (sk_seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64) (kp : Std.U32)
  (msg_hash : Array Std.U8 16#usize) (shuffle_seed : Array Std.U8 32#usize)
  (progress : hypertree.ProgressSink) (pct : Std.U8) :
  Result ((Array (Array Std.U8 16#usize) 43#usize) × Std.U32)
  := do
  let padded ← hash.pad16 msg_hash
  let (count, _, digits) ←
    wots.find_count seed layer tree kp padded progress pct
  let base_adrs ←
    address.make_adrs layer tree params.ADRS_WOTS kp 0#u32 0#u32 0#u32
  let a := Array.repeat 16#usize 0#u8
  let sigma := Array.repeat 43#usize a
  let chain_order ← shuffle.fisher_yates shuffle_seed params.L
  let sigma1 ←
    wots.sign_with_shuffle_loop { start := 0#usize, «end» := params.L } seed
      sk_seed layer tree kp digits base_adrs sigma chain_order
  ok (sigma1, count)

end sphincs_c10
