-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sphincs_c10]: function definitions
import Aeneas
import Extracted.Merkle.Types
import Extracted.Merkle.FunsExternal
import Extracted.Adrs
import Extracted.Fors.Funs
import Extracted.Hash.Funs
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sphincs_c10

/-- [sphincs_c10::params::ADRS_TREE]
    Source: 'sphincs-c10/src/params.rs', lines 99:0-99:29
    Visibility: public -/
@[global_simps, irreducible] def params.ADRS_TREE : Std.U32 := 2#u32

/-- [sphincs_c10::params::D]
    Source: 'sphincs-c10/src/params.rs', lines 25:0-25:23
    Visibility: public -/
@[global_simps, irreducible] def params.D : Std.Usize := 2#usize

/-- [sphincs_c10::params::SUBTREE_H]
    Source: 'sphincs-c10/src/params.rs', lines 28:0-28:35
    Visibility: public -/
@[global_simps, irreducible]
def params.SUBTREE_H : Result Std.Usize := params.H / params.D

/-- [sphincs_c10::merkle::verify_auth_path]: loop body 0:
    Source: 'sphincs-c10/src/merkle.rs', lines 167:4-177:5
    Visibility: public -/
@[rust_loop_body]
def merkle.verify_auth_path_loop.body
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize)
  (iter : core.ops.range.Range Std.Usize) (node : Array Std.U8 16#usize)
  (idx : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U8
    16#usize) × Std.U32) (Array Std.U8 16#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done node)
  | some h =>
    let parent_idx ← idx >>> 1#i32
    let i ← h + 1#usize
    let i1 ← lift (UScalar.cast .U32 i)
    let adrs ←
      address.make_adrs layer tree params.ADRS_TREE 0#u32 0#u32 i1 parent_idx
    let sibling ← Array.index_usize auth_path h
    let i2 ← lift (idx &&& 1#u32)
    let node1 ←
      if i2 = 0#u32
      then
        do
        let a ← hash.pad16 node
        let a1 ← hash.pad16 sibling
        hash.th_pair seed adrs a a1
      else
        do
        let a ← hash.pad16 sibling
        let a1 ← hash.pad16 node
        hash.th_pair seed adrs a a1
    ok (cont (iter1, node1, parent_idx))

/-- [sphincs_c10::merkle::verify_auth_path]: loop 0:
    Source: 'sphincs-c10/src/merkle.rs', lines 167:4-177:5
    Visibility: public -/
@[rust_loop]
def merkle.verify_auth_path_loop
  (iter : core.ops.range.Range Std.Usize) (seed : Array Std.U8 32#usize)
  (layer : Std.U32) (tree : Std.U64)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize)
  (node : Array Std.U8 16#usize) (idx : Std.U32) :
  Result (Array Std.U8 16#usize)
  := do
  loop
    (fun (iter1, node1, idx1) => merkle.verify_auth_path_loop.body seed layer
      tree auth_path iter1 node1 idx1)
    (iter, node, idx)

/-- [sphincs_c10::merkle::verify_auth_path]:
    Source: 'sphincs-c10/src/merkle.rs', lines 157:0-179:1
    Visibility: public -/
def merkle.verify_auth_path
  (seed : Array Std.U8 32#usize) (layer : Std.U32) (tree : Std.U64)
  (leaf_node : Array Std.U8 16#usize) (leaf_idx : Std.U32)
  (auth_path : Array (Array Std.U8 16#usize) 9#usize) :
  Result (Array Std.U8 16#usize)
  := do
  let i ← params.SUBTREE_H
  merkle.verify_auth_path_loop { start := 0#usize, «end» := i } seed layer
    tree auth_path leaf_node leaf_idx

end sphincs_c10
