/-!
# PQSigner.Common — shared types and protocol constants

Lean mirror of `contracts/smart-wallet/src/generated/PqsignerProto.sol`,
which is itself auto-generated from `proto/src/lib.rs`. The single source
of truth remains the Rust crate; this file is regenerated by the
companion `xtask gen-lean-constants` subcommand (TODO — see README §5).

**Do not edit by hand.** A regression here would silently desync the
Lean theorems from what the deployed verifier checks.
-/

import Verity.Prelude

namespace PQSigner.Common

/-! ## Signature sizes -/

/-- Exact length of a SPHINCS+C10 signature, in bytes. -/
def C10_SIG_LEN : Nat := 4008

/-- ABI-encoded `(uint256 ownerIndex, bytes innerSig)` wrapper length.
    Layout: 32 (ownerIndex) + 32 (offset = 0x40) + 32 (length) + ceil(C10_SIG_LEN/32)*32. -/
def SIG_WRAPPER_LEN : Nat := 4128

/-! ## Per-chain usage caps (invariant #7) -/

/-- Type 1 (bootstrap, ownerIndex == 0) sig cap, per chain. -/
def MAX_BOOTSTRAP_USES : Nat := 65536

/-- Type 2 (slot, ownerIndex >= 1) on-chain sig cap, per slot, per chain.
    Shared budget with off-chain EIP-1271 sigs via the combined invariant
    `slotUses[i] + offchainSigCount[i] <= MAX_SLOT_USES`. -/
def MAX_SLOT_USES : Nat := 65536

/-- Max unbacked off-chain sig gap before the firmware refuses a new
    EIP-1271 sig. Firmware-side knob, exposed here for spec coverage of
    `CMD_SIGN_OFFCHAIN` (not currently a Lean theorem target). -/
def MAX_OFFCHAIN_GAP : Nat := 100

/-! ## Wallet storage layout -/

/-- Owner bytes are `pkSeed (32) || pkRoot (32)`. -/
def OWNER_BYTES_LEN : Nat := 64

/-! ## Selectors (Type 2 allowlist) -/

/-- `addOwnerBytes(bytes)` selector. The ONLY selector permitted under
    `ownerIndex == 0`. -/
def ADD_OWNER_BYTES_SELECTOR : UInt32 := 0xdc8b8c1c  -- TODO confirm via `cast sig`

/-- `executeWithOffchainCount(uint256,uint256,address,uint256,bytes)`. -/
def EXECUTE_WITH_OFFCHAIN_COUNT_SELECTOR : UInt32 := 0x14443c57

/-- `executeBatchWithOffchainCount(uint256,uint256,(address,uint256,bytes)[])`. -/
def EXECUTE_BATCH_WITH_OFFCHAIN_COUNT_SELECTOR : UInt32 := 0x7a389933

/-- `removeOwnerAtIndex(uint256,bytes)`. Permitted under Type 2 so the
    firmware can rotate a compromised slot key via a UserOp signed by a
    DIFFERENT slot (typically the bootstrap-installed slot 0 acting as
    "secondary"). -/
def REMOVE_OWNER_AT_INDEX_SELECTOR : UInt32 := 0xfbf60db8  -- TODO confirm via `cast sig`

/-! ## Domain tags -/

/-- ASCII `"pqwallet-factory-add-slot"`. The bootstrap key signs
    `sha256(this || chainId_be8 || slot0PkSeed || slot0PkRoot)` to
    authorise CREATE2 of a wallet that opens with the given slot 0 on
    the given chain. Squat-defence — see
    `PQSmartWalletFactory.addSlot0Digest`. -/
def FACTORY_ADD_SLOT_DOMAIN : ByteVec :=
  ByteVec.ofString "pqwallet-factory-add-slot"

/-! ## ERC-4337 v0.6 sentinels for `validateUserOp` -/

def SIG_VALIDATION_SUCCESS : Nat := 0
def SIG_VALIDATION_FAILED : Nat := 1

/-! ## ERC-7201 storage location for `PQMultiOwnable`

    Derivation: `keccak256(abi.encode(uint256(keccak256("pqsigner.storage.PQMultiOwnable")) - 1)) & ~bytes32(uint256(0xff))`.
    Mirrors `_PQ_MULTI_OWNABLE_STORAGE_LOCATION` at
    `contracts/smart-wallet/src/PQMultiOwnable.sol:63-64`. The literal
    value is load-bearing for invariant #6: any change here renames the
    storage namespace, which alters the deployed bytecode and therefore
    the CREATE2 address. -/
def PQ_MULTI_OWNABLE_STORAGE_LOCATION : Bytes32 :=
  Bytes32.ofHex "0x470749eea5ac4a541d6582e535445f94e7300bac9e0e4e5577fd3336b407d000"

/-! ## Owner bytes shape

    An owner is `pkSeed (32) || pkRoot (32)`, both N-masked: the top 16
    bytes carry the actual SPHINCS+C10 128-bit value, the bottom 16
    bytes are zero. The firmware always emits this shape; the on-chain
    verifier feeds the full 32 bytes of each into SHA-256, so a non-zero
    bottom half would simply waste a slot index. -/
structure OwnerBytes where
  pkSeed : Bytes32
  pkRoot : Bytes32
  -- Both halves are required to obey the N-mask. We expose this as a
  -- Prop so callers must prove it before constructing.
  pkSeedNMask : pkSeed.lowHalf = Bytes16.zero
  pkRootNMask : pkRoot.lowHalf = Bytes16.zero

/-- Concatenate to the 64-byte ABI shape stored in `ownerAtIndex`. -/
def OwnerBytes.toBytes (o : OwnerBytes) : ByteVec :=
  o.pkSeed.toByteVec ++ o.pkRoot.toByteVec

end PQSigner.Common
