//! Merkle roots of the (host-side) ERC20 + Names + Selectors + ERC-7730 databases.
//!
//! Generated by `cargo run -p dbgen` from secure/data/erc20.json,
//! secure/data/names.json, secure/data/selectors.json,
//! secure/data/erc7730-registry/registry/**/*.json,
//! secure/data/erc7730-registry/ercs/**/*.json,
//! secure/data/erc7730-e2e/*.json, and secure/data/erc7730/policy.toml.
//! DO NOT EDIT BY HAND.
//!
//! NONE of the DB blobs ship in the firmware image. The ERC20 /
//! Names / Selectors / ERC-7730 blobs all live on the host (companion
//! app) under `tools/companion-stub/` and are forwarded over USB as
//! per-tx `(entry, merkle_proof, leaf_index)` bundles. The secure
//! world holds the 32-byte roots plus the generated real ERC-7730 leaf
//! count; everything received from NS or the host is verified against
//! those firmware-pinned values. A malicious companion cannot
//! forge an entry (that needs a SHA-256 second-preimage). Withholding
//! ERC20 / Names / Selectors metadata degrades to the corresponding
//! fail-safe render. A registry-known call requires independently
//! authenticated semantics: normally an exactly bound ERC-7730 descriptor;
//! the explicitly enumerated Safe exception is strict native ERC-20 decoding
//! with exact chain/contract-bound Merkle metadata, re-attributed per direct
//! call or MultiSend record. Without either capability, signing refuses. Only
//! calls absent from the authenticated known-call set may use the generic or
//! blind-sign fallback.
//!
//! `NAMES_DB_ROOT` anchors the address-name DB. Every trusted-UI
//! address render consults this root before a human-readable
//! name is allowed to replace the raw 40-hex address.
//!
//! `SELECTOR_DB_ROOT` anchors the function-selector → text-signature
//! DB. The blob is held by the (untrusted) companion app; bundles
//! crossing the gateway are Merkle-verified against this root and
//! cross-checked against `calldata[0..4]` before any text-sig
//! reaches the trusted UI. Production builds (no `e2e-test`
//! feature) use the full curated set; `e2e-test` builds swap in
//! the smaller `selectors-e2e.json` fixture root so the QEMU NS
//! test driver can bake a tiny companion-stub blob without
//! overflowing flash.
//!
//! `ERC7730_DESCRIPTORS_ROOT` anchors the ERC-7730 clear-signing
//! descriptor catalogue. Same trust model as the Selectors DB —
//! the blob lives host-side under `tools/companion-stub/`, and
//! every bundle crossing the gateway is Merkle-verified against this
//! root and constrained to the generated catalogue count by the secure
//! `crate::tx::erc7730::verify_erc7730_bundle` wrapper.
//! The generated `ERC7730_CATALOGUE_PROVENANCE` constant records whether the
//! exact root was produced by real ERC-8176 verification or by the explicitly
//! dev-only unattested path. Generated compile fences prevent a dev-unattested
//! root from being used without its warning feature and always reject it under
//! `mode-production`. ERC-8176 verification remains host-side (preserving
//! invariant #5 — no classical signer on-device).

#[cfg(not(feature = "e2e-test"))]
pub static ERC20_DB_ROOT: [u8; 32] = [
    0x31, 0x59, 0x55, 0x28, 0xb1, 0x7b, 0x9e, 0x69,
    0x1b, 0x3e, 0x03, 0xd2, 0xd2, 0x6f, 0x66, 0x10,
    0x68, 0x2e, 0x77, 0x06, 0x1d, 0x6a, 0x4a, 0x92,
    0x63, 0x87, 0x46, 0xf0, 0x46, 0xb5, 0x59, 0x90,
];

#[cfg(feature = "e2e-test")]
pub static ERC20_DB_ROOT: [u8; 32] = [
    0x5f, 0xcd, 0xff, 0x07, 0x2d, 0x8e, 0x29, 0x44,
    0xbf, 0x65, 0x47, 0xe5, 0xe4, 0x63, 0x29, 0x28,
    0x0d, 0x23, 0x7d, 0x24, 0xd4, 0x2d, 0xdb, 0x87,
    0x40, 0xac, 0xe2, 0xba, 0x23, 0x09, 0x9c, 0xca,
];

#[cfg(not(feature = "e2e-test"))]
pub static NAMES_DB_ROOT: [u8; 32] = [
    0x53, 0x20, 0xd4, 0xc4, 0x0d, 0xeb, 0x7a, 0xee,
    0xff, 0xd3, 0xae, 0x9b, 0x99, 0x5c, 0xc1, 0xfc,
    0x18, 0x18, 0xdf, 0x03, 0x41, 0x34, 0x1f, 0x68,
    0x2f, 0x20, 0x8e, 0xff, 0x5f, 0x1d, 0x6a, 0xbc,
];

#[cfg(feature = "e2e-test")]
pub static NAMES_DB_ROOT: [u8; 32] = [
    0xbd, 0x47, 0xbf, 0xe6, 0x67, 0xf7, 0x3a, 0xb9,
    0x50, 0x77, 0xae, 0xfc, 0xb3, 0x5c, 0x8f, 0xb8,
    0x74, 0x69, 0x61, 0x53, 0xad, 0x43, 0xbc, 0x69,
    0x60, 0x91, 0xf5, 0xa8, 0xcd, 0x43, 0xb8, 0x8b,
];

#[cfg(not(feature = "e2e-test"))]
pub static SELECTOR_DB_ROOT: [u8; 32] = [
    0x75, 0x1c, 0xaf, 0x52, 0x05, 0xa4, 0xff, 0x59,
    0x01, 0xab, 0x64, 0x78, 0xaf, 0x91, 0xff, 0x36,
    0x33, 0x8f, 0x87, 0x4b, 0x86, 0x83, 0x78, 0xc6,
    0x10, 0xb6, 0x93, 0x94, 0x74, 0x56, 0xe4, 0x6a,
];

#[cfg(feature = "e2e-test")]
pub static SELECTOR_DB_ROOT: [u8; 32] = [
    0xbd, 0x11, 0x0c, 0xa4, 0xc9, 0x16, 0x11, 0x7f,
    0xe5, 0x11, 0x69, 0x06, 0x2d, 0x5f, 0xea, 0xc0,
    0x97, 0x8c, 0x41, 0x1f, 0x45, 0xea, 0xd0, 0xdc,
    0xc0, 0x32, 0x9e, 0xb7, 0x0c, 0x14, 0xc1, 0x99,
];

// BEGIN GENERATED ERC7730 SECURITY TAIL - DO NOT EDIT
#[doc(hidden)]
pub const ERC7730_GENERATED_SECURITY_TAIL_ANCHOR: () = ();

#[doc(hidden)]
extern crate core as __pqsigner_erc7730_core;

#[cfg(not(feature = "e2e-test"))]
pub static ERC7730_DESCRIPTORS_ROOT: [u8; 32] = [
    0x99, 0xe4, 0xb2, 0x55, 0x6f, 0x5a, 0x77, 0xd6,
    0xe7, 0xd9, 0xb8, 0xf0, 0x7b, 0x06, 0x7e, 0x9b,
    0x87, 0xa4, 0x18, 0x7b, 0x3e, 0x47, 0x23, 0x75,
    0xe6, 0x02, 0x87, 0x7a, 0x28, 0x10, 0xbc, 0xfe,
];

#[cfg(feature = "e2e-test")]
pub static ERC7730_DESCRIPTORS_ROOT: [u8; 32] = [
    0xa2, 0xbd, 0xe3, 0xae, 0x90, 0x9a, 0x23, 0xa1,
    0xab, 0x45, 0xc5, 0x33, 0xff, 0xcb, 0xcd, 0xfb,
    0x35, 0x34, 0x51, 0x01, 0xee, 0x75, 0x0d, 0xa9,
    0x6a, 0x3c, 0xd6, 0xf8, 0x90, 0x04, 0x0c, 0xb4,
];

#[cfg(not(feature = "e2e-test"))]
pub const ERC7730_DESCRIPTOR_COUNT: usize = 437;

#[cfg(feature = "e2e-test")]
pub const ERC7730_DESCRIPTOR_COUNT: usize = 8;

#[cfg(not(feature = "e2e-test"))]
pub static ERC7730_KNOWN_CALLS_BLOOM: &[u8; pqsigner_erc7730::known_calls::BLOOM_BYTES] =
self::__pqsigner_erc7730_core::include_bytes!("../data/erc7730-known-calls.bloom");

#[cfg(feature = "e2e-test")]
pub static ERC7730_KNOWN_CALLS_BLOOM: &[u8; pqsigner_erc7730::known_calls::BLOOM_BYTES] =
self::__pqsigner_erc7730_core::include_bytes!("../data/erc7730-known-calls-e2e.bloom");

#[cfg(not(feature = "e2e-test"))]
pub const ERC7730_CATALOGUE_PROVENANCE: &str = "dev-unattested";

#[cfg(all(not(feature = "e2e-test"), feature = "mode-production"))]
self::__pqsigner_erc7730_core::compile_error!("mode-production cannot embed the dev-unattested ERC-7730 catalogue. Implement and run real ERC-8176 EAS verification, regenerate db_roots.rs, and only then build production firmware.");

#[cfg(all(not(feature = "e2e-test"), not(feature = "mode-production"), not(feature = "erc7730-dev-unattested"), not(test)))]
self::__pqsigner_erc7730_core::compile_error!("the pinned ERC-7730 catalogue is dev-unattested; enable erc7730-dev-unattested so the trusted display shows the provenance warning, or regenerate from a genuinely ERC-8176-verified corpus");

#[cfg(feature = "e2e-test")]
pub const ERC7730_CATALOGUE_PROVENANCE: &str = "dev-unattested";

#[cfg(all(feature = "e2e-test", not(feature = "erc7730-dev-unattested"), not(test)))]
self::__pqsigner_erc7730_core::compile_error!("the e2e ERC-7730 fixture catalogue is dev-unattested; e2e builds must enable erc7730-dev-unattested so the display warning matches its provenance");

